<?php
declare(strict_types=1);
$cfg = require '/home/u856637812/config/speaking_club_config.php';
$pdo = new PDO("mysql:host={$cfg['db_host']};dbname={$cfg['db_name']};charset=utf8mb4", $cfg['db_user'], $cfg['db_pass'], [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);

function T(string $en, string $ru, string $kz): array { return ['en' => $en, 'ru' => $ru, 'kz' => $kz]; }

// Topic name -> RU/KZ short phrase, used to fill {topic} in the templates below.
// Falls back to the English topic name itself if a lesson's topic isn't in this map.
$TOPIC_TR = [
    'Family' => ['ru' => 'семья', 'kz' => 'отбасы'],
    'Daily Routine' => ['ru' => 'распорядок дня', 'kz' => 'күнделікті тәртіп'],
    'Food and Drinks' => ['ru' => 'еда и напитки', 'kz' => 'тамақ пен сусындар'],
    'My House' => ['ru' => 'мой дом', 'kz' => 'менің үйім'],
    'Weather' => ['ru' => 'погода', 'kz' => 'ауа райы'],
    'Colors and Clothes' => ['ru' => 'цвета и одежда', 'kz' => 'түстер мен киім'],
    'Animals' => ['ru' => 'животные', 'kz' => 'жануарлар'],
    'Numbers and Time' => ['ru' => 'числа и время', 'kz' => 'сандар мен уақыт'],
    'Hobbies' => ['ru' => 'хобби', 'kz' => 'хобби'],
    'Body Parts' => ['ru' => 'части тела', 'kz' => 'дене мүшелері'],
    'School' => ['ru' => 'школа', 'kz' => 'мектеп'],
    'Getting Around Town' => ['ru' => 'передвижение по городу', 'kz' => 'қала бойынша жүру'],
    'At the Market' => ['ru' => 'рынок', 'kz' => 'базар'],
    'Feelings and Emotions' => ['ru' => 'чувства и эмоции', 'kz' => 'сезімдер мен эмоциялар'],
    'Days of the Week' => ['ru' => 'дни недели', 'kz' => 'апта күндері'],
    'Places in Town' => ['ru' => 'места в городе', 'kz' => 'қаладағы орындар'],
    'Basic Actions' => ['ru' => 'основные действия', 'kz' => 'негізгі әрекеттер'],
    'Toys and Games' => ['ru' => 'игрушки и игры', 'kz' => 'ойыншықтар мен ойындар'],
    'Fruits and Vegetables' => ['ru' => 'фрукты и овощи', 'kz' => 'жемістер мен көкөністер'],
    'Places for Fun' => ['ru' => 'места для развлечений', 'kz' => 'көңіл көтеру орындары'],
    'Clothes Shopping' => ['ru' => 'покупка одежды', 'kz' => 'киім сатып алу'],
    'Cooking Basics' => ['ru' => 'основы готовки', 'kz' => 'тамақ пісірудің негіздері'],
    'My Neighborhood' => ['ru' => 'мой район', 'kz' => 'менің ауданым'],
    'Talking About Age' => ['ru' => 'разговор о возрасте', 'kz' => 'жас туралы әңгіме'],
    'Simple Directions' => ['ru' => 'простые направления', 'kz' => 'қарапайым бағыттар'],
    'The Human Senses' => ['ru' => 'органы чувств человека', 'kz' => 'адамның сезім мүшелері'],
    'Money and Prices' => ['ru' => 'деньги и цены', 'kz' => 'ақша мен бағалар'],
    'Common Illnesses' => ['ru' => 'распространённые болезни', 'kz' => 'жиі кездесетін аурулар'],
    'Simple Travel Phrases' => ['ru' => 'простые фразы для путешествий', 'kz' => 'саяхатқа арналған қарапайым сөздер'],
    'My Favorite Things' => ['ru' => 'мои любимые вещи', 'kz' => 'менің сүйікті заттарым'],
    'Weekend Plans' => ['ru' => 'планы на выходные', 'kz' => 'демалыс күндеріне жоспар'],
    'Simple Chores at Home' => ['ru' => 'простые домашние дела', 'kz' => 'үйдегі қарапайым шаруалар'],
    'Basic Shapes and Sizes' => ['ru' => 'основные формы и размеры', 'kz' => 'негізгі пішіндер мен өлшемдер'],
    'Talking About Jobs' => ['ru' => 'разговор о профессиях', 'kz' => 'кәсіптер туралы әңгіме'],
    'Common Adjectives' => ['ru' => 'распространённые прилагательные', 'kz' => 'жиі қолданылатын сын есімдер'],
    'My Body and Health Habits' => ['ru' => 'моё тело и привычки здоровья', 'kz' => 'менің денем және денсаулық әдеттері'],
    'In the Classroom' => ['ru' => 'в классе', 'kz' => 'сыныпта'],
    'Simple Recipes' => ['ru' => 'простые рецепты', 'kz' => 'қарапайым рецепттер'],
    'My Daily Schedule' => ['ru' => 'мой распорядок дня', 'kz' => 'менің күнделікті кестем'],
    'Talking About the Past' => ['ru' => 'разговор о прошлом', 'kz' => 'өткен туралы әңгіме'],
    'Talking About the Future' => ['ru' => 'разговор о будущем', 'kz' => 'болашақ туралы әңгіме'],
    'Common Sounds and Noises' => ['ru' => 'распространённые звуки и шумы', 'kz' => 'жиі кездесетін дыбыстар мен шулар'],
    'Simple Wishes and Dreams' => ['ru' => 'простые желания и мечты', 'kz' => 'қарапайым тілектер мен армандар'],
    'At the Post Office' => ['ru' => 'почта', 'kz' => 'пошта'],
    'School Subjects' => ['ru' => 'школьные предметы', 'kz' => 'мектеп пәндері'],
    'Simple Comparisons' => ['ru' => 'простые сравнения', 'kz' => 'қарапайым салыстырулар'],
    'Family Roles' => ['ru' => 'роли в семье', 'kz' => 'отбасындағы рөлдер'],
    'Rooms and Furniture' => ['ru' => 'комнаты и мебель', 'kz' => 'бөлмелер мен жиһаз'],
    'Travel Items' => ['ru' => 'вещи для путешествий', 'kz' => 'саяхатқа арналған заттар'],
    'Talking About the Weather Today' => ['ru' => 'разговор о сегодняшней погоде', 'kz' => 'бүгінгі ауа райы туралы әңгіме'],
    'Talking About Pets' => ['ru' => 'разговор о домашних животных', 'kz' => 'үй жануарлары туралы әңгіме'],
    'My Favorite Season' => ['ru' => 'моё любимое время года', 'kz' => 'менің сүйікті мезгілім'],
    'At the Restaurant' => ['ru' => 'ресторан', 'kz' => 'мейрамхана'],
    'Simple Sports' => ['ru' => 'простые виды спорта', 'kz' => 'қарапайым спорт түрлері'],
    'My Neighbors' => ['ru' => 'мои соседи', 'kz' => 'менің көршілерім'],
    'Talking About Health' => ['ru' => 'разговор о здоровье', 'kz' => 'денсаулық туралы әңгіме'],
    'My Favorite Movies' => ['ru' => 'мои любимые фильмы', 'kz' => 'менің сүйікті фильмдерім'],
    'Simple Technology' => ['ru' => 'простые технологии', 'kz' => 'қарапайым технологиялар'],
    'At the Beach' => ['ru' => 'пляж', 'kz' => 'жағажай'],
    'Talking About Music' => ['ru' => 'разговор о музыке', 'kz' => 'музыка туралы әңгіме'],
    'Simple Farewells' => ['ru' => 'простые прощания', 'kz' => 'қарапайым қоштасулар'],
    'My City' => ['ru' => 'мой город', 'kz' => 'менің қалам'],
    'Talking About Friends' => ['ru' => 'разговор о друзьях', 'kz' => 'достар туралы әңгіме'],
    'Simple Shopping List' => ['ru' => 'простой список покупок', 'kz' => 'қарапайым сатып алу тізімі'],
    'My Free Time' => ['ru' => 'моё свободное время', 'kz' => 'менің бос уақытым'],

    'Travel and Transportation' => ['ru' => 'путешествия и транспорт', 'kz' => 'саяхат және көлік'],
    'Shopping' => ['ru' => 'шопинг', 'kz' => 'сауда жасау'],
    'Health and Body' => ['ru' => 'здоровье и тело', 'kz' => 'денсаулық және дене'],
    'Sports' => ['ru' => 'спорт', 'kz' => 'спорт'],
    'Seasons and Holidays' => ['ru' => 'времена года и праздники', 'kz' => 'жыл мезгілдері мен мерекелер'],
    'Technology' => ['ru' => 'технологии', 'kz' => 'технологиялар'],
    'City and Directions' => ['ru' => 'город и направления', 'kz' => 'қала және бағыттар'],
    'Jobs and Careers' => ['ru' => 'работа и карьера', 'kz' => 'жұмыс және мансап'],
    'Free Time Activities' => ['ru' => 'занятия в свободное время', 'kz' => 'бос уақыттағы әрекеттер'],
    'Restaurants and Eating Out' => ['ru' => 'рестораны и еда вне дома', 'kz' => 'мейрамханалар және сыртта тамақтану'],
    'Neighbors and Community' => ['ru' => 'соседи и сообщество', 'kz' => 'көршілер және қауымдастық'],
    'Cooking and Recipes' => ['ru' => 'готовка и рецепты', 'kz' => 'тамақ пісіру және рецепттер'],
    'At the Bank' => ['ru' => 'банк', 'kz' => 'банк'],
    'Pets and Pet Care' => ['ru' => 'домашние животные и уход за ними', 'kz' => 'үй жануарлары және оларға күтім'],
    'Celebrations Around the World' => ['ru' => 'праздники по всему миру', 'kz' => 'бүкіл әлемдегі мерекелер'],
    'Household Chores' => ['ru' => 'домашние дела', 'kz' => 'үй жұмыстары'],
    'At the Airport and Hotel' => ['ru' => 'аэропорт и отель', 'kz' => 'әуежай және қонақүй'],
    'Music and Instruments' => ['ru' => 'музыка и инструменты', 'kz' => 'музыка және аспаптар'],
    'Emergency Situations' => ['ru' => 'чрезвычайные ситуации', 'kz' => 'төтенше жағдайлар'],
    'Farm and Countryside' => ['ru' => 'ферма и сельская местность', 'kz' => 'ферма және ауыл жері'],
    'Bills and Utilities' => ['ru' => 'счета и коммунальные услуги', 'kz' => 'шоттар мен коммуналдық қызметтер'],
    'Weather Forecasts' => ['ru' => 'прогнозы погоды', 'kz' => 'ауа райы болжамдары'],
    "Doctor's Appointment" => ['ru' => 'приём у врача', 'kz' => 'дәрігерге қабылдау'],
    'Public Transport Etiquette' => ['ru' => 'этикет в общественном транспорте', 'kz' => 'қоғамдық көліктегі әдеп'],
    'Online Shopping' => ['ru' => 'онлайн-покупки', 'kz' => 'онлайн сауда'],
    'Café Culture' => ['ru' => 'культура кафе', 'kz' => 'кафе мәдениеті'],
    'Sports Equipment' => ['ru' => 'спортивное снаряжение', 'kz' => 'спорттық жабдық'],
    'Weekend Getaways' => ['ru' => 'поездки на выходные', 'kz' => 'демалыс күндеріндегі сапарлар'],
    'Office Life' => ['ru' => 'жизнь в офисе', 'kz' => 'офистегі өмір'],
    'Fitness Classes' => ['ru' => 'фитнес-занятия', 'kz' => 'фитнес сабақтары'],
    'Home Repairs' => ['ru' => 'ремонт дома', 'kz' => 'үй жөндеу'],
    'Birthday Parties' => ['ru' => 'дни рождения', 'kz' => 'туған күн мерекелері'],
    'Photography as a Hobby' => ['ru' => 'фотография как хобби', 'kz' => 'хобби ретінде фотография'],
    'Job Interviews' => ['ru' => 'собеседования на работу', 'kz' => 'жұмысқа сұхбат'],
    'Renting an Apartment' => ['ru' => 'аренда квартиры', 'kz' => 'пәтер жалдау'],
    'At the Gym' => ['ru' => 'спортзал', 'kz' => 'спортзал'],
    'Weather and Clothing' => ['ru' => 'погода и одежда', 'kz' => 'ауа райы және киім'],
    'Learning a New Language' => ['ru' => 'изучение нового языка', 'kz' => 'жаңа тіл үйрену'],
    'Car Ownership' => ['ru' => 'владение автомобилем', 'kz' => 'автокөлікке ие болу'],
    'Recycling and Waste' => ['ru' => 'переработка и отходы', 'kz' => 'қайта өңдеу және қалдықтар'],
    'Online Dating' => ['ru' => 'онлайн-знакомства', 'kz' => 'онлайн таныстық'],
    'Home Cooking vs Takeout' => ['ru' => 'домашняя еда против еды на вынос', 'kz' => 'үйде пісірілген тамақ пен әкетілетін тамақ'],
    'Personal Finance Basics' => ['ru' => 'основы личных финансов', 'kz' => 'жеке қаржының негіздері'],
    'Weekend Markets' => ['ru' => 'рынки выходного дня', 'kz' => 'демалыс күндеріндегі базарлар'],
    'City Landmarks' => ['ru' => 'городские достопримечательности', 'kz' => 'қала көрікті жерлері'],
    'Volunteering Locally' => ['ru' => 'волонтёрство в своём городе', 'kz' => 'жергілікті еріктілік'],
    'Weather Emergencies' => ['ru' => 'погодные чрезвычайные ситуации', 'kz' => 'ауа райы төтенше жағдайлары'],
    'Learning to Drive' => ['ru' => 'обучение вождению', 'kz' => 'жүргізуді үйрену'],
    'Neighborhood Watch' => ['ru' => 'соседский дозор', 'kz' => 'көрші бақылауы'],
    'Seasonal Jobs' => ['ru' => 'сезонная работа', 'kz' => 'маусымдық жұмыс'],
    'Coffee vs Tea Culture' => ['ru' => 'культура кофе против чая', 'kz' => 'кофе мен шай мәдениеті'],
    'Public Speaking Basics' => ['ru' => 'основы публичных выступлений', 'kz' => 'көпшілік алдында сөйлеудің негіздері'],
    'Weekend Chores' => ['ru' => 'домашние дела на выходных', 'kz' => 'демалыс күндеріндегі шаруалар'],
    'Local Wildlife' => ['ru' => 'местная дикая природа', 'kz' => 'жергілікті жабайы табиғат'],
    'Learning to Swim' => ['ru' => 'обучение плаванию', 'kz' => 'жүзуді үйрену'],
    'City Nightlife' => ['ru' => 'ночная жизнь города', 'kz' => 'қаланың түнгі өмірі'],
    'Home Gardening' => ['ru' => 'домашнее садоводство', 'kz' => 'үй бақшашылығы'],
    'Public Libraries' => ['ru' => 'публичные библиотеки', 'kz' => 'көпшілік кітапханалар'],
    'Weekend Sports Leagues' => ['ru' => 'спортивные лиги выходного дня', 'kz' => 'демалыс күндеріндегі спорт лигалары'],
    'Travel Insurance and Safety' => ['ru' => 'страхование путешествий и безопасность', 'kz' => 'саяхат сақтандыруы және қауіпсіздік'],
    'Renovating a Home' => ['ru' => 'ремонт дома', 'kz' => 'үйді жаңарту'],
    'Digital Photography Tips' => ['ru' => 'советы по цифровой фотографии', 'kz' => 'цифрлық фотография бойынша кеңестер'],
    'Learning an Instrument' => ['ru' => 'обучение игре на инструменте', 'kz' => 'аспапта ойнауды үйрену'],
    'Weekend Volunteering Trips' => ['ru' => 'волонтёрские поездки на выходных', 'kz' => 'демалыс күндеріндегі еріктілік сапарлары'],
    'Public Speaking Anxiety' => ['ru' => 'страх публичных выступлений', 'kz' => 'көпшілік алдында сөйлеу қорқынышы'],

    'Environment and Nature' => ['ru' => 'окружающая среда и природа', 'kz' => 'қоршаған орта және табиғат'],
    'Friendship and Relationships' => ['ru' => 'дружба и отношения', 'kz' => 'достық және қарым-қатынас'],
    'Movies and Entertainment' => ['ru' => 'фильмы и развлечения', 'kz' => 'фильмдер және ойын-сауық'],
    'Social Media' => ['ru' => 'социальные сети', 'kz' => 'әлеуметтік желілер'],
    'Money and Shopping Habits' => ['ru' => 'деньги и привычки покупок', 'kz' => 'ақша және сатып алу әдеттері'],
    'Education Systems' => ['ru' => 'системы образования', 'kz' => 'білім беру жүйелері'],
    'Culture and Traditions' => ['ru' => 'культура и традиции', 'kz' => 'мәдениет және дәстүрлер'],
    'Dreams and Ambitions' => ['ru' => 'мечты и амбиции', 'kz' => 'армандар мен мақсаттар'],
    'Crime and Safety' => ['ru' => 'преступность и безопасность', 'kz' => 'қылмыс және қауіпсіздік'],
    'Travel Experiences Abroad' => ['ru' => 'опыт путешествий за границу', 'kz' => 'шетелге саяхат тәжірибесі'],
    'Health and Fitness Trends' => ['ru' => 'тенденции здоровья и фитнеса', 'kz' => 'денсаулық және фитнес трендтері'],
    'The World of Work' => ['ru' => 'мир работы', 'kz' => 'жұмыс әлемі'],
    'Consumerism and Advertising' => ['ru' => 'потребительство и реклама', 'kz' => 'тұтынушылық және жарнама'],
    'Urban vs Rural Life' => ['ru' => 'городская жизнь против сельской', 'kz' => 'қалалық және ауылдық өмір'],
    'Generation Gap' => ['ru' => 'разрыв поколений', 'kz' => 'буын алшақтығы'],
    'Volunteering and Charity' => ['ru' => 'волонтёрство и благотворительность', 'kz' => 'еріктілік және қайырымдылық'],
    'Fashion and Self-Expression' => ['ru' => 'мода и самовыражение', 'kz' => 'сән және өзін-өзі көрсету'],
    'Space and Astronomy' => ['ru' => 'космос и астрономия', 'kz' => 'ғарыш және астрономия'],
    'Books and Reading Habits' => ['ru' => 'книги и привычки чтения', 'kz' => 'кітаптар және оқу әдеттері'],
    'Public Speaking and Communication' => ['ru' => 'публичные выступления и общение', 'kz' => 'көпшілік алдында сөйлеу және қарым-қатынас'],
    'Beauty Standards and Self-Image' => ['ru' => 'стандарты красоты и самооценка', 'kz' => 'сұлулық стандарттары және өзін-өзі бағалау'],
    'The Power of Habits' => ['ru' => 'сила привычек', 'kz' => 'әдеттердің күші'],
    'Traditional vs Modern Medicine' => ['ru' => 'традиционная и современная медицина', 'kz' => 'дәстүрлі және заманауи медицина'],
    'The Sharing Economy' => ['ru' => 'экономика совместного использования', 'kz' => 'бөлісу экономикасы'],
    'Animal Rights and Ethics' => ['ru' => 'права животных и этика', 'kz' => 'жануарлар құқығы және этика'],
    'The Art of Negotiation' => ['ru' => 'искусство переговоров', 'kz' => 'келіссөз өнері'],
    'Digital Detox' => ['ru' => 'цифровой детокс', 'kz' => 'цифрлық детокс'],
    'Cultural Festivals and Events' => ['ru' => 'культурные фестивали и события', 'kz' => 'мәдени фестивальдер мен іс-шаралар'],
    'The Rise of Remote Learning' => ['ru' => 'рост дистанционного обучения', 'kz' => 'қашықтықтан оқытудың өсуі'],
    'Wildlife Conservation' => ['ru' => 'охрана дикой природы', 'kz' => 'жабайы табиғатты қорғау'],
    'The Psychology of Color' => ['ru' => 'психология цвета', 'kz' => 'түс психологиясы'],
    'Workplace Diversity' => ['ru' => 'разнообразие на рабочем месте', 'kz' => 'жұмыс орнындағы әртүрлілік'],
    'The History of the Internet' => ['ru' => 'история интернета', 'kz' => 'интернеттің тарихы'],
    'Extreme Sports and Risk-Taking' => ['ru' => 'экстремальные виды спорта и риск', 'kz' => 'экстремалды спорт және тәуекел'],
    'The Future of Transportation' => ['ru' => 'будущее транспорта', 'kz' => 'көліктің болашағы'],
    'The Ethics of Eating Meat' => ['ru' => 'этика употребления мяса', 'kz' => 'ет жеудің этикасы'],
    'Language Loss and Revival' => ['ru' => 'утрата и возрождение языков', 'kz' => 'тілдің жоғалуы және жаңғыруы'],
    'The Life of a Content Creator' => ['ru' => 'жизнь создателя контента', 'kz' => 'контент жасаушының өмірі'],
    'Minimalism and Decluttering' => ['ru' => 'минимализм и избавление от лишнего', 'kz' => 'минимализм және артықты жою'],
    'The Psychology of Procrastination' => ['ru' => 'психология прокрастинации', 'kz' => 'прокрастинация психологиясы'],
    'Urban Wildlife' => ['ru' => 'городская дикая природа', 'kz' => 'қалалық жабайы табиғат'],
    'The Rise of Plant-Based Diets' => ['ru' => 'рост популярности растительного питания', 'kz' => 'өсімдік негізіндегі тағамның өсуі'],
    'Public Art and Graffiti' => ['ru' => 'публичное искусство и граффити', 'kz' => 'көпшілік өнері және графити'],
    'The Etiquette of Tipping' => ['ru' => 'этикет чаевых', 'kz' => 'кеңес ақы этикеті'],
    'Living with Roommates' => ['ru' => 'жизнь с соседями по квартире', 'kz' => 'пәтерлестермен өмір сүру'],
    'The World of Podcasts' => ['ru' => 'мир подкастов', 'kz' => 'подкасттар әлемі'],
    'Second-Hand and Vintage Shopping' => ['ru' => 'покупка одежды с рук и винтаж', 'kz' => 'қолданылған және винтаж заттарды сатып алу'],
    'The Science of Sleep' => ['ru' => 'наука о сне', 'kz' => 'ұйқы туралы ғылым'],
    'Body Language and First Impressions' => ['ru' => 'язык тела и первое впечатление', 'kz' => 'дене тілі және алғашқы әсер'],
    'The Rise of Remote Teams' => ['ru' => 'рост удалённых команд', 'kz' => 'қашықтағы командалардың өсуі'],
    'The Ethics of Gift-Giving' => ['ru' => 'этика дарения подарков', 'kz' => 'сыйлық берудің этикасы'],
    'Coffee Shop Economy' => ['ru' => 'экономика кофеен', 'kz' => 'кофехана экономикасы'],
    'The Rise of Solo Travel' => ['ru' => 'рост популярности одиночных путешествий', 'kz' => 'жалғыз саяхаттың өсуі'],
    'Workplace Burnout Prevention' => ['ru' => 'профилактика выгорания на работе', 'kz' => 'жұмыстағы күйзелістің алдын алу'],
    'The Culture of Complaining' => ['ru' => 'культура жалоб', 'kz' => 'шағымдану мәдениеті'],
    'Family Traditions and Change' => ['ru' => 'семейные традиции и перемены', 'kz' => 'отбасылық дәстүрлер және өзгерістер'],
    'The Psychology of Nostalgia' => ['ru' => 'психология ностальгии', 'kz' => 'ностальгия психологиясы'],
    'Urban Green Spaces' => ['ru' => 'городские зелёные зоны', 'kz' => 'қалалық жасыл аймақтар'],
    'The Art of Small Talk' => ['ru' => 'искусство светской беседы', 'kz' => 'жеңіл әңгіме өнері'],
    'Ethical Consumerism' => ['ru' => 'этичное потребление', 'kz' => 'этикалық тұтыну'],
    'The Science of Habit Formation' => ['ru' => 'наука о формировании привычек', 'kz' => 'әдет қалыптастыру ғылымы'],
    'Language and Thought' => ['ru' => 'язык и мышление', 'kz' => 'тіл және ойлау'],
    'The Rise of Co-Living Spaces' => ['ru' => 'рост популярности ко-ливинга', 'kz' => 'бірлескен тұрғын үй кеңістігінің өсуі'],
    'Sports Fandom and Identity' => ['ru' => 'спортивный фанатизм и идентичность', 'kz' => 'спорттық жанкүйерлік және сәйкестік'],
    'The Ethics of Reality TV' => ['ru' => 'этика реалити-шоу', 'kz' => 'реалити-шоу этикасы'],

    'Globalization' => ['ru' => 'глобализация', 'kz' => 'жаһандану'],
    'Artificial Intelligence and the Future' => ['ru' => 'искусственный интеллект и будущее', 'kz' => 'жасанды интеллект және болашақ'],
    'Mental Health and Wellbeing' => ['ru' => 'психическое здоровье и благополучие', 'kz' => 'психикалық денсаулық және әл-ауқат'],
    'Work-Life Balance' => ['ru' => 'баланс между работой и жизнью', 'kz' => 'жұмыс пен өмір теңгерімі'],
    'Climate Change' => ['ru' => 'изменение климата', 'kz' => 'климаттың өзгеруі'],
    'Media and Misinformation' => ['ru' => 'СМИ и дезинформация', 'kz' => 'БАҚ және жалған ақпарат'],
    'Cultural Identity' => ['ru' => 'культурная идентичность', 'kz' => 'мәдени сәйкестік'],
    'Ethics and Moral Dilemmas' => ['ru' => 'этика и моральные дилеммы', 'kz' => 'этика және моральдық дилеммалар'],
    'Urbanization' => ['ru' => 'урбанизация', 'kz' => 'урбандану'],
    'The Future of Education' => ['ru' => 'будущее образования', 'kz' => 'білім берудің болашағы'],
    'The Gig Economy' => ['ru' => 'гиг-экономика', 'kz' => 'гиг-экономика'],
    'Consumer Culture and Materialism' => ['ru' => 'потребительская культура и материализм', 'kz' => 'тұтынушылық мәдениет және материализм'],
    'Genetic Engineering and Bioethics' => ['ru' => 'генная инженерия и биоэтика', 'kz' => 'генетикалық инженерия және биоэтика'],
    'The Justice System' => ['ru' => 'система правосудия', 'kz' => 'әділет жүйесі'],
    'Immigration and National Identity' => ['ru' => 'иммиграция и национальная идентичность', 'kz' => 'иммиграция және ұлттық сәйкестік'],
    'Consumer Technology and Privacy' => ['ru' => 'потребительские технологии и приватность', 'kz' => 'тұтынушылық технологиялар және жекеменшік'],
    'Political Systems and Democracy' => ['ru' => 'политические системы и демократия', 'kz' => 'саяси жүйелер және демократия'],
    'The Ageing Population' => ['ru' => 'стареющее население', 'kz' => 'қартаятын халық'],
    'Language and Communication in a Digital Age' => ['ru' => 'язык и общение в цифровую эпоху', 'kz' => 'цифрлық дәуірдегі тіл және байланыс'],
    'Space Exploration and Colonization' => ['ru' => 'освоение и колонизация космоса', 'kz' => 'ғарышты игеру және отарлау'],
    'Economic Inequality' => ['ru' => 'экономическое неравенство', 'kz' => 'экономикалық теңсіздік'],
    'The Philosophy of Happiness' => ['ru' => 'философия счастья', 'kz' => 'бақыт философиясы'],
    'Technology Addiction' => ['ru' => 'технологическая зависимость', 'kz' => 'технологияға тәуелділік'],
    'Freedom of Speech' => ['ru' => 'свобода слова', 'kz' => 'сөз бостандығы'],
    'The Nature vs Nurture Debate' => ['ru' => 'спор о природе и воспитании', 'kz' => 'табиғат пен тәрбие туралы пікірталас'],
    'Automation and Job Displacement' => ['ru' => 'автоматизация и потеря рабочих мест', 'kz' => 'автоматтандыру және жұмыс орындарының жоғалуы'],
    'Global Health Crises' => ['ru' => 'глобальные кризисы здравоохранения', 'kz' => 'жаһандық денсаулық сақтау дағдарыстары'],
    'The Ethics of Surveillance' => ['ru' => 'этика слежки', 'kz' => 'бақылаудың этикасы'],
    'Corporate Social Responsibility' => ['ru' => 'корпоративная социальная ответственность', 'kz' => 'корпоративтік әлеуметтік жауапкершілік'],
    'The Future of Work' => ['ru' => 'будущее работы', 'kz' => 'жұмыстың болашағы'],
    'Historical Memory and Monuments' => ['ru' => 'историческая память и памятники', 'kz' => 'тарихи жады және ескерткіштер'],
    'The Rise of E-Sports' => ['ru' => 'рост киберспорта', 'kz' => 'киберспорттың өсуі'],
    'Water Scarcity and Resources' => ['ru' => 'нехватка воды и ресурсы', 'kz' => 'су тапшылығы және ресурстар'],
    'The Psychology of Persuasion' => ['ru' => 'психология убеждения', 'kz' => 'сендіру психологиясы'],
    'Artificial Intelligence in Everyday Life' => ['ru' => 'искусственный интеллект в повседневной жизни', 'kz' => 'күнделікті өмірдегі жасанды интеллект'],
    'The Attention Economy' => ['ru' => 'экономика внимания', 'kz' => 'назар аудару экономикасы'],
    'Universal Basic Income' => ['ru' => 'безусловный базовый доход', 'kz' => 'әмбебап негізгі табыс'],
    'The Ethics of Zoos and Aquariums' => ['ru' => 'этика зоопарков и океанариумов', 'kz' => 'хайуанаттар бағы мен аквариумдардың этикасы'],
    'Cultural Appropriation vs Appreciation' => ['ru' => 'культурное присвоение против признательности', 'kz' => 'мәдени иемдену және құрметтеу'],
    'The Housing Crisis' => ['ru' => 'жилищный кризис', 'kz' => 'тұрғын үй дағдарысы'],
    'Deepfakes and Digital Trust' => ['ru' => 'дипфейки и цифровое доверие', 'kz' => 'дипфейктер және цифрлық сенім'],
    'The Ethics of Self-Driving Cars' => ['ru' => 'этика беспилотных автомобилей', 'kz' => 'өзін-өзі басқаратын көліктердің этикасы'],
    'Cancel Culture' => ['ru' => 'культура отмены', 'kz' => 'болдырмау мәдениеті'],
    'The Psychology of Social Comparison' => ['ru' => 'психология социального сравнения', 'kz' => 'әлеуметтік салыстыру психологиясы'],
    'Renewable Energy Transition' => ['ru' => 'переход на возобновляемую энергию', 'kz' => 'жаңартылатын энергияға көшу'],
    'The Rise of Micro-Influencers' => ['ru' => 'рост микро-инфлюенсеров', 'kz' => 'микро-инфлюенсерлердің өсуі'],
    'Work Burnout Culture' => ['ru' => 'культура выгорания на работе', 'kz' => 'жұмыстағы күйзеліс мәдениеті'],
    'The Future of Currency' => ['ru' => 'будущее валюты', 'kz' => 'валютаның болашағы'],
    'Parenting in the Digital Age' => ['ru' => 'родительство в цифровую эпоху', 'kz' => 'цифрлық дәуірдегі ата-аналық'],
    'The Meaning of Success' => ['ru' => 'значение успеха', 'kz' => 'табыстың мағынасы'],
    'The Paradox of Choice' => ['ru' => 'парадокс выбора', 'kz' => 'таңдау парадоксы'],
    'Digital Colonialism' => ['ru' => 'цифровой колониализм', 'kz' => 'цифрлық отаршылдық'],
    'The Ethics of Longevity Science' => ['ru' => 'этика науки долголетия', 'kz' => 'ұзақ өмір сүру ғылымының этикасы'],
    'Neurodiversity in the Workplace' => ['ru' => 'нейроразнообразие на рабочем месте', 'kz' => 'жұмыс орнындағы нейроалуандық'],
    'The Politics of Language' => ['ru' => 'политика языка', 'kz' => 'тіл саясаты'],
    'Post-Truth Society' => ['ru' => 'постправдивое общество', 'kz' => 'посташиқат қоғам'],
    'The Economics of Attention' => ['ru' => 'экономика внимания', 'kz' => 'назар экономикасы'],
    'Techno-Optimism vs Techno-Skepticism' => ['ru' => 'технооптимизм против техноскептицизма', 'kz' => 'техно-оптимизм және техно-скептицизм'],
    'The Culture of Overwork in Different Countries' => ['ru' => 'культура переработки в разных странах', 'kz' => 'әртүрлі елдердегі шамадан тыс жұмыс мәдениеті'],
    'Rewilding and Ecological Restoration' => ['ru' => 'реставрация дикой природы и восстановление экосистем', 'kz' => 'жабайы табиғатты қалпына келтіру'],
    'The Ethics of Wealth Inheritance' => ['ru' => 'этика наследования богатства', 'kz' => 'байлықты мұраға алу этикасы'],
    'Digital Nomadism and Global Inequality' => ['ru' => 'цифровое кочевничество и глобальное неравенство', 'kz' => 'цифрлық көшпенділік және жаһандық теңсіздік'],
];

// "{topic} — question" label format: the topic is a clean, uninflected label
// (safe for Russian/Kazakh grammatical case and agglutination), and the
// question itself is fully self-contained via invariant pronouns (this/это/бұл)
// that refer back to the label right beside them, not to another question.
$TEMPLATES = [
    T("{topic} — what is your personal opinion, and why?", "{topic} — какое у вас личное мнение и почему?", "{topic} — жеке пікіріңіз қандай және неге?"),
    T("{topic} — how has this changed in recent years?", "{topic} — как это изменилось за последние годы?", "{topic} — соңғы жылдары бұл қалай өзгерді?"),
    T("{topic} — why do you think this matters today?", "{topic} — почему, по-вашему, это важно сегодня?", "{topic} — сіздің ойыңызша, бұл бүгін неге маңызды?"),
    T("{topic} — what is the biggest challenge here, in your view?", "{topic} — какая здесь самая большая трудность, на ваш взгляд?", "{topic} — сіздің көзқарасыңызша, мұндағы ең үлкен қиындық қандай?"),
    T("{topic} — what are the main benefits, do you think?", "{topic} — какие тут, по-вашему, главные преимущества?", "{topic} — сіздің ойыңызша, мұның негізгі артықшылықтары қандай?"),
    T("{topic} — how do people in your country generally feel about it?", "{topic} — как люди в вашей стране обычно относятся к этому?", "{topic} — еліңіздегі адамдар бұған әдетте қалай қарайды?"),
    T("{topic} — have you had any personal experience with it?", "{topic} — у вас был личный опыт, связанный с этим?", "{topic} — сізде осыған байланысты жеке тәжірибе болды ма?"),
    T("{topic} — what would you like to understand better?", "{topic} — что бы вы хотели понять лучше?", "{topic} — нені жақсырақ түсінгіңіз келеді?"),
    T("{topic} — how do you imagine this looking in ten years?", "{topic} — как вы представляете это через десять лет?", "{topic} — он жылдан кейін бұл қалай болады деп ойлайсыз?"),
    T("{topic} — what advice would you give to someone new to this?", "{topic} — какой совет вы бы дали новичку в этом?", "{topic} — бұған жаңа адамға қандай кеңес берер едіңіз?"),
    T("{topic} — what is a common misunderstanding people have?", "{topic} — какое распространённое заблуждение бывает у людей?", "{topic} — адамдарда қандай кең таралған қате түсінік болады?"),
    T("{topic} — how important is this to you personally?", "{topic} — насколько это важно лично для вас?", "{topic} — бұл сіз үшін жеке қаншалықты маңызды?"),
    T("{topic} — what role does this play in your community?", "{topic} — какую роль это играет в вашем сообществе?", "{topic} — бұл қауымдастығыңызда қандай рөл атқарады?"),
    T("{topic} — do you talk about this with friends or family? What do you say?", "{topic} — вы обсуждаете это с друзьями или семьёй? Что вы говорите?", "{topic} — мұны достарыңызбен немесе отбасыңызбен талқылайсыз ба? Не айтасыз?"),
    T("{topic} — what surprised you the most when you first learned about it?", "{topic} — что вас удивило больше всего, когда вы впервые узнали об этом?", "{topic} — бұл туралы алғаш білгенде сізді ең көп таңғалдырған не болды?"),
    T("{topic} — does this get enough attention today? Why or why not?", "{topic} — этому уделяют достаточно внимания сегодня? Почему да или нет?", "{topic} — бұған бүгінде жеткілікті назар аударыла ма? Неге ия немесе жоқ?"),
    T("{topic} — what is one thing you would change if you could?", "{topic} — что бы вы изменили, если бы могли?", "{topic} — мүмкіндік болса, не өзгертер едіңіз?"),
    T("{topic} — how do you think this compares to ten years ago?", "{topic} — как, по-вашему, это отличается от того, что было десять лет назад?", "{topic} — сіздің ойыңызша, бұл он жыл бұрынғымен салыстырғанда қандай?"),
];
$TC = count($TEMPLATES);

$stmt = $pdo->query("SELECT id, topic, questions FROM lessons WHERE id <= 260 ORDER BY id");
$rows = $stmt->fetchAll(PDO::FETCH_ASSOC);

function mb_ucfirst_word(string $s): string {
    return mb_strtoupper(mb_substr($s, 0, 1)) . mb_substr($s, 1);
}

$update = $pdo->prepare("UPDATE lessons SET questions = ? WHERE id = ?");

$fixed = 0;
$missingTopic = [];
foreach ($rows as $row) {
    $questions = json_decode($row['questions'], true);
    if (!is_array($questions) || count($questions) < 6) continue;

    $original6 = array_slice($questions, 0, 6);
    $topic = $row['topic'];
    $tr = $TOPIC_TR[$topic] ?? null;
    if (!$tr) {
        $missingTopic[] = $topic;
        $tr = ['ru' => $topic, 'kz' => $topic];
    }
    $ruLabel = mb_ucfirst_word($tr['ru']);
    $kzLabel = mb_ucfirst_word($tr['kz']);

    $start = ((int)$row['id'] * 5) % $TC;
    $newQuestions = $original6;
    for ($k = 0; $k < 9; $k++) {
        $idx = ($start + $k) % $TC;
        $tpl = $TEMPLATES[$idx];
        $newQuestions[] = [
            'en' => str_replace('{topic}', $topic, $tpl['en']),
            'ru' => str_replace('{topic}', $ruLabel, $tpl['ru']),
            'kz' => str_replace('{topic}', $kzLabel, $tpl['kz']),
        ];
    }

    $update->execute([json_encode($newQuestions, JSON_UNESCAPED_UNICODE), $row['id']]);
    $fixed++;
}

echo "Fixed: $fixed\n";
if ($missingTopic) {
    echo "Missing translations for: " . implode(' | ', array_unique($missingTopic)) . "\n";
}
