<?php
declare(strict_types=1);
// Included from seed_lessons_batch7.php — shares its scope ($lessons, function V()).

// ========================= ELEMENTARY (batch 7) — 15 questions per topic =========================

$lessons[] = ['level' => 'elementary', 'topic' => 'Choosing a College Roommate', 'background_key' => 'professional',
    'warmup' => V("Let's talk about roommates. What qualities would you look for in a college roommate?", 'Давайте поговорим о соседях по комнате. Какие качества вы бы искали в соседе по комнате в колледже?', 'Бөлме серіктері туралы сөйлесейік. Колледждегі бөлме серігінде қандай қасиеттерді іздер едіңіз?'),
    'vocab' => [V('roommate', 'сосед по комнате', 'бөлме серігі'), V('compatible', 'совместимый', 'үйлесімді'), V('messy', 'неряшливый', 'ретсіз'), V('quiet hours', 'тихие часы', 'тыныш сағаттар'), V('shared space', 'общее пространство', 'ортақ кеңістік'), V('personality', 'личность', 'жеке тұлға'), V('agreement', 'соглашение', 'келісім'), V('conflict', 'конфликт', 'қақтығыс'), V('respect', 'уважение', 'құрмет'), V('lifestyle', 'образ жизни', 'өмір салты')],
    'questions' => [
        V('What qualities would you look for in a roommate?', 'Какие качества вы бы искали в соседе по комнате?', 'Бөлме серігінде қандай қасиеттерді іздер едіңіз?'),
        V('Would you rather room with a friend or a stranger?', 'Вы бы предпочли жить с другом или незнакомцем?', 'Досыңызбен тұрғанды қалайсыз ба, әлде бейтаныс адаммен бе?'),
        V('Does a messy roommate bother you?', 'Неряшливый сосед по комнате вас беспокоит?', 'Ретсіз бөлме серігі сізді мазалай ма?'),
        V('Would you set quiet hours with a roommate?', 'Вы бы установили тихие часы с соседом по комнате?', 'Бөлме серігіңізбен тыныш сағаттар белгілер ме едіңіз?'),
        V('Have you ever shared a room with someone?', 'Вы когда-нибудь делили комнату с кем-то?', 'Біреумен бөлмені бөлістіңіз бе?'),
        V('Do you think similar personalities make better roommates?', 'Как вы думаете, похожие личности становятся лучшими соседями по комнате?', 'Ұқсас жеке тұлғалар жақсырақ бөлме серігі бола ма деп ойлайсыз ба?'),
        V('Would you make a written agreement with a roommate?', 'Вы бы заключили письменное соглашение с соседом по комнате?', 'Бөлме серігіңізбен жазбаша келісім жасар ма едіңіз?'),
        V('Have you ever had a conflict with a roommate?', 'У вас когда-нибудь был конфликт с соседом по комнате?', 'Бөлме серігіңізбен қақтығысыңыз болды ма?'),
        V('Do you respect a roommate\'s need for privacy?', 'Вы уважаете потребность соседа по комнате в уединении?', 'Бөлме серігінің жекелік қажеттілігін құрметтейсіз бе?'),
        V('Would different lifestyles cause problems between roommates?', 'Разные образы жизни вызвали бы проблемы между соседями по комнате?', 'Әртүрлі өмір салты бөлме серіктері арасында мәселе тудырар ма еді?'),
        V('Do you prefer living alone instead of with a roommate?', 'Вы предпочитаете жить одни, а не с соседом по комнате?', 'Бөлме серігімен емес, жалғыз тұрғанды ұнатасыз ба?'),
        V('What would you do if you didn\'t get along with a roommate?', 'Что бы вы сделали, если бы не поладили с соседом по комнате?', 'Бөлме серігіңізбен тіл табыса алмасаңыз, не істер едіңіз?'),
        V('Would you share food or belongings with a roommate?', 'Вы бы делились едой или вещами с соседом по комнате?', 'Бөлме серігіңізбен тамақ немесе заттарды бөлісер ме едіңіз?'),
        V('Do you think roommate relationships can turn into real friendships?', 'Как вы думаете, отношения с соседом по комнате могут перерасти в настоящую дружбу?', 'Бөлме серігімен қарым-қатынас нағыз достыққа айналуы мүмкін деп ойлайсыз ба?'),
        V('What is the biggest challenge of having a roommate?', 'Какая самая большая трудность в проживании с соседом по комнате?', 'Бөлме серігімен тұрудың ең үлкен қиындығы не?'),
    ],
];

$lessons[] = ['level' => 'elementary', 'topic' => 'Preparing for a Storm', 'background_key' => 'minimal-dark',
    'warmup' => V("Let's talk about preparing for storms. What do you do to get ready when a big storm is coming?", 'Давайте поговорим о подготовке к бурям. Что вы делаете, чтобы подготовиться, когда приближается сильная буря?', 'Дауылға дайындалу туралы сөйлесейік. Күшті дауыл жақындағанда дайындалу үшін не істейсіз?'),
    'vocab' => [V('storm warning', 'предупреждение о буре', 'дауыл туралы ескерту'), V('supplies', 'припасы', 'қажетті заттар'), V('flashlight', 'фонарик', 'фонарь'), V('power outage', 'отключение электричества', 'электр қуатының өшуі'), V('secure', 'закрепить', 'бекіту'), V('shelter', 'укрытие', 'баспана'), V('evacuate', 'эвакуироваться', 'эвакуациялану'), V('battery', 'батарея', 'батарея'), V('emergency kit', 'аварийный комплект', 'төтенше жинақ'), V('warning system', 'система оповещения', 'ескерту жүйесі')],
    'questions' => [
        V('What do you do to prepare for a big storm?', 'Что вы делаете, чтобы подготовиться к сильной буре?', 'Күшті дауылға дайындалу үшін не істейсіз?'),
        V('Do you keep an emergency kit at home?', 'У вас дома есть аварийный комплект?', 'Үйде төтенше жинағыңыз бар ма?'),
        V('Have you ever experienced a power outage during a storm?', 'Вы когда-нибудь испытывали отключение электричества во время бури?', 'Дауыл кезінде электр қуатының өшуін бастан кештіңіз бе?'),
        V('Do you own a flashlight with extra batteries?', 'У вас есть фонарик с запасными батарейками?', 'Қосымша батареялары бар фонарыңыз бар ма?'),
        V('Have you ever had to evacuate because of severe weather?', 'Вам когда-нибудь приходилось эвакуироваться из-за суровой погоды?', 'Қатты ауа райы себебінен эвакуациялануға тура келді ме?'),
        V('Do you take storm warnings seriously?', 'Вы серьёзно относитесь к предупреждениям о буре?', 'Дауыл туралы ескертулерге байыпты қарайсыз ба?'),
        V('Do you secure loose items outside before a storm?', 'Вы закрепляете свободные предметы снаружи перед бурей?', 'Дауыл алдында сыртта тұрған бос заттарды бекітесіз бе?'),
        V('Have storms ever damaged your home or property?', 'Бури когда-нибудь повреждали ваш дом или имущество?', 'Дауылдар үйіңізге немесе мүлкіңізге зиян тигізді ме?'),
        V('Do you check the weather forecast regularly during storm season?', 'Вы регулярно проверяете прогноз погоды в сезон бурь?', 'Дауыл маусымында ауа райы болжамын тұрақты тексересіз бе?'),
        V('Would you know where the nearest storm shelter is?', 'Вы бы знали, где находится ближайшее укрытие от бури?', 'Ең жақын дауылдан баспананың қайда екенін білер ме едіңіз?'),
        V('Do you stock up on food and water before a storm?', 'Вы запасаетесь едой и водой перед бурей?', 'Дауыл алдында тамақ пен суды жинайсыз ба?'),
        V('Have you ever been scared during a severe storm?', 'Вы когда-нибудь боялись во время сильной бури?', 'Қатты дауыл кезінде қорықтыңыз ба?'),
        V('Do warning systems in your area work well?', 'Системы оповещения в вашем районе работают хорошо?', 'Ауданыңыздағы ескерту жүйелері жақсы жұмыс істейді ме?'),
        V('Would you help a neighbor prepare for a storm?', 'Вы бы помогли соседу подготовиться к буре?', 'Көршіге дауылға дайындалуға көмектесер ме едіңіз?'),
        V('What is the most important item in a storm emergency kit?', 'Какой самый важный предмет в аварийном комплекте на случай бури?', 'Дауылға арналған төтенше жинақтағы ең маңызды зат қандай?'),
    ],
];

$lessons[] = ['level' => 'elementary', 'topic' => 'Choosing a Career Mentor', 'background_key' => 'professional',
    'warmup' => V("Let's talk about mentors. Have you ever had someone guide you in your career or studies?", 'Давайте поговорим о наставниках. У вас когда-нибудь был кто-то, кто направлял вас в карьере или учёбе?', 'Тәлімгерлер туралы сөйлесейік. Мансабыңызда немесе оқуыңызда бағыт беретін біреу болды ма?'),
    'vocab' => [V('mentor', 'наставник', 'тәлімгер'), V('guidance', 'руководство', 'бағыт беру'), V('experience', 'опыт', 'тәжірибе'), V('advice', 'совет', 'кеңес'), V('role model', 'образец для подражания', 'үлгі тұлға'), V('trust', 'доверие', 'сенім'), V('feedback', 'обратная связь', 'кері байланыс'), V('network', 'связи (сеть)', 'байланыс желісі'), V('inspire', 'вдохновлять', 'шабыттандыру'), V('grateful', 'благодарный', 'алғыс білдіретін')],
    'questions' => [
        V('Have you ever had a mentor? Who was it?', 'У вас когда-нибудь был наставник? Кто это был?', 'Тәлімгеріңіз болды ма? Ол кім еді?'),
        V('What qualities make a good mentor?', 'Какие качества делают наставника хорошим?', 'Тәлімгерді жақсы ететін қасиеттер қандай?'),
        V('Would you like to have a career mentor?', 'Хотели бы вы иметь наставника в карьере?', 'Мансаптық тәлімгеріңіз болғанын қалайсыз ба?'),
        V('Do you trust advice from someone more experienced than you?', 'Вы доверяете советам от кого-то более опытного, чем вы?', 'Сізден тәжірибелірек адамның кеңесіне сенесіз бе?'),
        V('Have you ever been a mentor to someone else?', 'Вы когда-нибудь были наставником для кого-то ещё?', 'Басқа біреуге тәлімгер болдыңыз ба?'),
        V('Do you have a role model who inspires you?', 'У вас есть образец для подражания, который вас вдохновляет?', 'Сізді шабыттандыратын үлгі тұлғаңыз бар ма?'),
        V('Would you feel comfortable asking someone to be your mentor?', 'Вам было бы комфортно попросить кого-то стать вашим наставником?', 'Біреуден тәлімгеріңіз болуын сұрау сізге ыңғайлы ма?'),
        V('Do you think mentorship is important early in a career?', 'Как вы думаете, наставничество важно в начале карьеры?', 'Мансап басында тәлімгерлік маңызды деп ойлайсыз ба?'),
        V('Have you ever received feedback that changed how you work?', 'Вы когда-нибудь получали обратную связь, которая изменила ваш подход к работе?', 'Жұмыс істеу тәсіліңізді өзгерткен кері байланыс алдыңыз ба?'),
        V('Do you stay in touch with people who have helped guide you?', 'Вы поддерживаете связь с людьми, которые помогали вам?', 'Сізге бағыт беруге көмектескен адамдармен байланыста боласыз ба?'),
        V('Would you rather learn from a mentor or from your own mistakes?', 'Вы бы предпочли учиться у наставника или на собственных ошибках?', 'Тәлімгерден үйренгенді қалайсыз ба, әлде өз қателеріңізден бе?'),
        V('Do you think a mentor should also be a friend?', 'Как вы думаете, наставник также должен быть другом?', 'Тәлімгер сонымен қатар дос болуы керек деп ойлайсыз ба?'),
        V('Have you ever expanded your network through a mentor?', 'Вы когда-нибудь расширяли свои связи через наставника?', 'Тәлімгер арқылы байланыс желіңізді кеңейттіңіз бе?'),
        V('Are you grateful for someone who helped shape your path?', 'Вы благодарны кому-то, кто помог сформировать ваш путь?', 'Жолыңызды қалыптастыруға көмектескен адамға алғыс білдіресіз бе?'),
        V('What advice would you give to someone looking for a mentor?', 'Какой совет вы бы дали тому, кто ищет наставника?', 'Тәлімгер іздеп жүрген адамға қандай кеңес берер едіңіз?'),
    ],
];

$lessons[] = ['level' => 'elementary', 'topic' => 'Buying Furniture', 'background_key' => 'professional',
    'warmup' => V("Let's talk about buying furniture. What do you look for when choosing furniture for your home?", 'Давайте поговорим о покупке мебели. Что вы ищете при выборе мебели для дома?', 'Жиһаз сатып алу туралы сөйлесейік. Үйге жиһаз таңдағанда нені іздейсіз?'),
    'vocab' => [V('furniture', 'мебель', 'жиһаз'), V('assemble', 'собирать', 'құрастыру'), V('durable', 'прочный', 'берік'), V('style', 'стиль', 'стиль'), V('delivery', 'доставка', 'жеткізу'), V('secondhand', 'подержанный', 'қолданылған'), V('budget', 'бюджет', 'бюджет'), V('comfortable', 'удобный', 'ыңғайлы'), V('measure', 'измерять', 'өлшеу'), V('warranty', 'гарантия', 'кепілдік')],
    'questions' => [
        V('What do you look for when buying furniture?', 'Что вы ищете при покупке мебели?', 'Жиһаз сатып алғанда нені іздейсіз?'),
        V('Do you prefer buying new furniture or secondhand?', 'Вы предпочитаете покупать новую мебель или подержанную?', 'Жаңа жиһаз сатып алғанды ұнатасыз ба, әлде қолданылғанды ма?'),
        V('Have you ever assembled furniture yourself?', 'Вы когда-нибудь собирали мебель сами?', 'Жиһазды өзіңіз құрастырдыңыз ба?'),
        V('Do you measure a room before buying furniture for it?', 'Вы измеряете комнату перед покупкой мебели для неё?', 'Оған жиһаз сатып алмас бұрын бөлмені өлшейсіз бе?'),
        V('Is comfort or style more important to you in furniture?', 'Что важнее для вас в мебели: удобство или стиль?', 'Жиһазда сіз үшін ыңғайлылық маңыздырақ па, әлде стиль ме?'),
        V('Do you check reviews before buying big furniture items?', 'Вы проверяете отзывы перед покупкой крупных предметов мебели?', 'Үлкен жиһаз заттарын сатып алмас бұрын пікірлерді тексересіз бе?'),
        V('Have you ever had furniture delivered to your home?', 'Вам когда-нибудь доставляли мебель домой?', 'Үйіңізге жиһаз жеткізілді ме?'),
        V('Do you stick to a budget when furnishing a room?', 'Вы придерживаетесь бюджета, обставляя комнату?', 'Бөлмені жиһаздағанда бюджетті ұстанасыз ба?'),
        V('Do you think furniture assembly instructions are usually clear?', 'Как вы думаете, инструкции по сборке мебели обычно понятны?', 'Жиһаз құрастыру нұсқаулары әдетте түсінікті деп ойлайсыз ба?'),
        V('Would you buy furniture without trying it out first?', 'Вы бы купили мебель, не попробовав её сначала?', 'Алдын ала сынап көрмей жиһаз сатып алар ма едіңіз?'),
        V('Do you check the warranty before purchasing furniture?', 'Вы проверяете гарантию перед покупкой мебели?', 'Жиһаз сатып алмас бұрын кепілдікті тексересіз бе?'),
        V('What is the most durable piece of furniture you own?', 'Какой самый прочный предмет мебели у вас есть?', 'Иеленген ең берік жиһаз бұйымыңыз қандай?'),
        V('Have you ever regretted buying a piece of furniture?', 'Вы когда-нибудь жалели о покупке мебели?', 'Жиһаз сатып алғаныңызға өкіндіңіз бе?'),
        V('Do you prefer minimalist or decorative furniture styles?', 'Вы предпочитаете минималистичный или декоративный стиль мебели?', 'Минималистік жиһаз стилін ұнатасыз ба, әлде декоративтіні ме?'),
        V('What piece of furniture would you like to buy next?', 'Какой предмет мебели вы хотели бы купить следующим?', 'Келесі қандай жиһаз затын сатып алғыңыз келеді?'),
    ],
];

$lessons[] = ['level' => 'elementary', 'topic' => 'Managing a Small Team', 'background_key' => 'professional',
    'warmup' => V("Let's talk about leading a team. What makes someone a good team leader?", 'Давайте поговорим о руководстве командой. Что делает человека хорошим руководителем команды?', 'Команданы басқару туралы сөйлесейік. Адамды жақсы команда жетекшісі ететін не?'),
    'vocab' => [V('team leader', 'руководитель команды', 'команда жетекшісі'), V('delegate', 'делегировать', 'тапсыру'), V('feedback', 'обратная связь', 'кері байланыс'), V('motivate', 'мотивировать', 'ынталандыру'), V('deadline', 'дедлайн', 'мерзім'), V('conflict resolution', 'разрешение конфликтов', 'қақтығысты шешу'), V('trust', 'доверие', 'сенім'), V('communication', 'общение', 'қарым-қатынас'), V('responsibility', 'ответственность', 'жауапкершілік'), V('support', 'поддержка', 'қолдау')],
    'questions' => [
        V('Have you ever managed a small team?', 'Вы когда-нибудь управляли небольшой командой?', 'Шағын команданы басқардыңыз ба?'),
        V('What makes someone a good team leader?', 'Что делает человека хорошим руководителем команды?', 'Адамды жақсы команда жетекшісі ететін не?'),
        V('Do you find it easy to delegate tasks to others?', 'Вам легко делегировать задачи другим?', 'Тапсырмаларды басқаларға тапсыру сізге оңай ма?'),
        V('How do you motivate a team that is losing energy?', 'Как вы мотивируете команду, теряющую энергию?', 'Қуатын жоғалтып жатқан команданы қалай ынталандырасыз?'),
        V('Do you give feedback directly, or do you soften it?', 'Вы даёте обратную связь прямо, или смягчаете её?', 'Кері байланысты тікелей бересіз бе, әлде жұмсартасыз ба?'),
        V('Have you ever had to resolve a conflict between team members?', 'Вам когда-нибудь приходилось разрешать конфликт между членами команды?', 'Команда мүшелері арасындағы қақтығысты шешуге тура келді ме?'),
        V('Do you trust your team to work without close supervision?', 'Вы доверяете своей команде работать без пристального надзора?', 'Командаңызға мұқият қадағалаусыз жұмыс істеуге сенесіз бе?'),
        V('Is meeting deadlines always a top priority for you?', 'Соблюдение сроков всегда является для вас главным приоритетом?', 'Мерзімдерді сақтау сіз үшін әрдайым басты басымдық па?'),
        V('Do you think good communication solves most team problems?', 'Как вы думаете, хорошее общение решает большинство командных проблем?', 'Жақсы қарым-қатынас көптеген команда мәселелерін шешеді деп ойлайсыз ба?'),
        V('Would you rather lead a team or be part of one?', 'Вы бы предпочли возглавлять команду или быть её частью?', 'Команданы басқарғанды қалайсыз ба, әлде оның бөлігі болғанды ма?'),
        V('Have you ever felt responsible for a team\'s mistake?', 'Вы когда-нибудь чувствовали ответственность за ошибку команды?', 'Команданың қатесі үшін жауапты сезіндіңіз бе?'),
        V('Do you support team members who are struggling?', 'Вы поддерживаете членов команды, которые испытывают трудности?', 'Қиналған команда мүшелерін қолдайсыз ба?'),
        V('What is the hardest part of managing people?', 'Какая самая трудная часть управления людьми?', 'Адамдарды басқарудың ең қиын бөлігі не?'),
        V('Do you celebrate small wins with your team?', 'Вы отмечаете небольшие успехи со своей командой?', 'Командаңызбен шағын жетістіктерді тойлайсыз ба?'),
        V('What leadership skill would you like to improve?', 'Какой навык руководства вы хотели бы улучшить?', 'Қандай көшбасшылық дағдыны жақсартқыңыз келеді?'),
    ],
];

$lessons[] = ['level' => 'elementary', 'topic' => 'Choosing a Streaming Service', 'background_key' => 'night-city',
    'warmup' => V("Let's talk about streaming services. How do you decide which one to subscribe to?", 'Давайте поговорим о стриминговых сервисах. Как вы решаете, на какой подписаться?', 'Стриминг қызметтері туралы сөйлесейік. Қайсысына жазылуды қалай шешесіз?'),
    'vocab' => [V('subscription', 'подписка', 'жазылым'), V('streaming service', 'стриминговый сервис', 'стриминг қызметі'), V('monthly fee', 'ежемесячная плата', 'айлық төлем'), V('original content', 'оригинальный контент', 'түпнұсқалық контент'), V('cancel', 'отменить', 'бас тарту'), V('binge-watch', 'смотреть запоем', 'үзіліссіз көру'), V('recommendation', 'рекомендация', 'ұсыныс'), V('free trial', 'бесплатный пробный период', 'тегін сынақ мерзімі'), V('library', 'библиотека (контента)', 'кітапхана (контент)'), V('ad-free', 'без рекламы', 'жарнамасыз')],
    'questions' => [
        V('How many streaming services do you subscribe to?', 'На сколько стриминговых сервисов вы подписаны?', 'Неше стриминг қызметіне жазылғансыз?'),
        V('How do you decide which service to subscribe to?', 'Как вы решаете, на какой сервис подписаться?', 'Қай қызметке жазылуды қалай шешесіз?'),
        V('Have you ever canceled a subscription because you didn\'t use it?', 'Вы когда-нибудь отменяли подписку, потому что не пользовались ею?', 'Пайдаланбағандықтан жазылымды бас тарттыңыз ба?'),
        V('Do you binge-watch shows, or watch one episode at a time?', 'Вы смотрите сериалы запоем, или по одному эпизоду?', 'Сериалдарды үзіліссіз көресіз бе, әлде бір-бір эпизодтан көресіз бе?'),
        V('Do you trust the recommendations these services give you?', 'Вы доверяете рекомендациям, которые дают эти сервисы?', 'Бұл қызметтердің ұсыныстарына сенесіз бе?'),
        V('Do you prefer original content or licensed shows and movies?', 'Вы предпочитаете оригинальный контент или лицензированные шоу и фильмы?', 'Түпнұсқалық контентті ұнатасыз ба, әлде лицензияланған шоу мен фильмдерді ме?'),
        V('Would you pay more for an ad-free experience?', 'Вы бы заплатили больше за просмотр без рекламы?', 'Жарнамасыз көру үшін көбірек төлер ме едіңіз?'),
        V('Do you use free trials often?', 'Вы часто пользуетесь бесплатными пробными периодами?', 'Тегін сынақ мерзімдерін жиі пайдаланасыз ба?'),
        V('Do you share a streaming account with family or friends?', 'Вы делите аккаунт стриминга с семьёй или друзьями?', 'Стриминг есептік жазбасын отбасымен немесе достармен бөлісесіз бе?'),
        V('Is monthly cost the biggest factor in your choice?', 'Ежемесячная стоимость — самый большой фактор в вашем выборе?', 'Айлық құн таңдауыңыздағы ең үлкен фактор ма?'),
        V('Do you switch between services depending on what you want to watch?', 'Вы переключаетесь между сервисами в зависимости от того, что хотите посмотреть?', 'Не көргіңіз келетініне байланысты қызметтер арасында ауысасыз ба?'),
        V('Have you ever forgotten you were paying for a subscription?', 'Вы когда-нибудь забывали, что платите за подписку?', 'Жазылым үшін төлеп жатқаныңызды ұмытып қалдыңыз ба?'),
        V('Do you think there are too many streaming services now?', 'Как вы думаете, сейчас слишком много стриминговых сервисов?', 'Қазір стриминг қызметтері тым көп деп ойлайсыз ба?'),
        V('What show or movie made you subscribe to a service?', 'Какой сериал или фильм заставил вас подписаться на сервис?', 'Қандай сериал немесе фильм сізді қызметке жазылуға мәжбүр етті?'),
        V('Would you rather have one big service or many small ones?', 'Вы бы предпочли один большой сервис или много маленьких?', 'Бір үлкен қызметті қалайсыз ба, әлде көптеген кішіні ме?'),
    ],
];

// ========================= PRE-INTERMEDIATE (batch 7) — 15 questions per topic =========================

$lessons[] = ['level' => 'pre-intermediate', 'topic' => 'The Psychology of Motivation', 'background_key' => 'minimal-dark',
    'warmup' => V("Let's talk about motivation. What truly motivates people to keep going toward a goal?", 'Давайте поговорим о мотивации. Что действительно мотивирует людей двигаться к цели?', 'Мотивация туралы сөйлесейік. Адамдарды мақсатқа қарай жылжуға шынымен не итермелейді?'),
    'vocab' => [V('intrinsic motivation', 'внутренняя мотивация', 'ішкі мотивация'), V('extrinsic motivation', 'внешняя мотивация', 'сыртқы мотивация'), V('reward', 'награда', 'сыйақы'), V('discipline', 'дисциплина', 'тәртіп'), V('purpose', 'цель (смысл)', 'мақсат'), V('procrastination', 'прокрастинация', 'кейінге қалдыру'), V('drive', 'стремление', 'ұмтылыс'), V('burnout', 'выгорание', 'күйреу'), V('accountability', 'подотчётность', 'жауапкершілік'), V('consistency', 'последовательность', 'тұрақтылық')],
    'questions' => [
        V('What truly motivates you to keep working toward a goal?', 'Что действительно мотивирует вас продолжать работать над целью?', 'Мақсатқа қарай жұмыс істеуді жалғастыруға сізді шынымен не итермелейді?'),
        V('Do you rely more on internal or external motivation?', 'Вы больше полагаетесь на внутреннюю или внешнюю мотивацию?', 'Ішкі мотивацияға көбірек сенесіз бе, әлде сыртқыға ма?'),
        V('Do rewards actually help you stay motivated long-term?', 'Награды действительно помогают вам оставаться мотивированным в долгосрочной перспективе?', 'Сыйақылар ұзақ мерзімде мотивацияны сақтауға шынымен көмектесе ме?'),
        V('Do you think discipline matters more than motivation?', 'Как вы думаете, дисциплина важнее мотивации?', 'Тәртіп мотивациядан маңыздырақ деп ойлайсыз ба?'),
        V('Why do you think people procrastinate even when they are motivated?', 'Как вы думаете, почему люди откладывают дела, даже будучи мотивированными?', 'Сіздің ойыңызша, неге адамдар мотивацияланса да, істерін кейінге қалдырады?'),
        V('Does having a clear purpose increase your motivation?', 'Наличие чёткой цели увеличивает вашу мотивацию?', 'Анық мақсаттың болуы мотивацияңызды арттыра ма?'),
        V('Have you ever lost motivation for something you once loved?', 'Вы когда-нибудь теряли мотивацию к тому, что раньше любили?', 'Бір кездері ұнатқан нәрсеге деген мотивациядан айырылдыңыз ба?'),
        V('Does accountability to others help you stay motivated?', 'Подотчётность перед другими помогает вам оставаться мотивированным?', 'Басқалар алдындағы жауапкершілік мотивацияны сақтауға көмектесе ме?'),
        V('Do you think motivation naturally fades over time?', 'Как вы думаете, мотивация естественным образом угасает со временем?', 'Мотивация уақыт өте табиғи түрде бәсеңдейді деп ойлайсыз ба?'),
        V('What is more sustainable: motivation or habit?', 'Что более устойчиво: мотивация или привычка?', 'Не тұрақтырақ: мотивация ма, әлде әдет пе?'),
        V('Have you ever experienced burnout from pushing too hard?', 'Вы когда-нибудь испытывали выгорание от чрезмерного напряжения?', 'Тым қатты күш салудан күйреуді бастан кештіңіз бе?'),
        V('Do you use rewards to motivate yourself for small tasks?', 'Вы используете награды, чтобы мотивировать себя на маленькие задачи?', 'Кішкентай тапсырмалар үшін өзіңізді мотивациялау үшін сыйақыларды пайдаланасыз ба?'),
        V('Do you think comparing yourself to others helps or hurts motivation?', 'Как вы думаете, сравнение себя с другими помогает или вредит мотивации?', 'Өзіңізді басқалармен салыстыру мотивацияға көмектесе ме, әлде зиян тигізе ме деп ойлайсыз ба?'),
        V('What is the biggest motivation killer for you personally?', 'Что для вас лично является главным убийцей мотивации?', 'Жеке сіз үшін мотивацияны ең көп өлтіретін нәрсе не?'),
        V('What strategy helps you regain motivation after losing it?', 'Какая стратегия помогает вам восстановить мотивацию после её потери?', 'Мотивацияны жоғалтқаннан кейін оны қалпына келтіруге қандай стратегия көмектеседі?'),
    ],
];

$lessons[] = ['level' => 'pre-intermediate', 'topic' => 'The Ethics of Influencer Marketing', 'background_key' => 'night-city',
    'warmup' => V("Let's talk about influencer marketing. Should influencers always disclose when they are paid to promote something?", 'Давайте поговорим о маркетинге через инфлюенсеров. Должны ли инфлюенсеры всегда раскрывать, когда им платят за продвижение чего-то?', 'Инфлюенсерлер арқылы маркетинг туралы сөйлесейік. Инфлюенсерлер бір нәрсені жарнамалау үшін ақы алғанда әрдайым ашық айтуы керек пе?'),
    'vocab' => [V('sponsored content', 'спонсируемый контент', 'демеушілік контент'), V('disclosure', 'раскрытие информации', 'ақпаратты ашу'), V('authenticity', 'подлинность', 'түпнұсқалық'), V('trust', 'доверие', 'сенім'), V('follower', 'подписчик', 'жазылушы'), V('brand partnership', 'партнёрство с брендом', 'брендпен серіктестік'), V('deceptive', 'обманчивый', 'алдамшы'), V('regulation', 'регулирование', 'реттеу'), V('impressionable', 'легко поддающийся влиянию', 'ықпалға оңай берілетін'), V('endorsement', 'поддержка (реклама)', 'қолдау (жарнама)')],
    'questions' => [
        V('Do you think influencers should always disclose paid promotions?', 'Как вы думаете, инфлюенсеры всегда должны раскрывать оплаченные продвижения?', 'Инфлюенсерлер әрдайым ақылы жарнамаларды ашуы керек деп ойлайсыз ба?'),
        V('Have you ever bought something because an influencer recommended it?', 'Вы когда-нибудь покупали что-то, потому что инфлюенсер это рекомендовал?', 'Инфлюенсер ұсынғаны үшін бір нәрсе сатып алдыңыз ба?'),
        V('Do you trust product recommendations from influencers you follow?', 'Вы доверяете рекомендациям товаров от инфлюенсеров, за которыми следите?', 'Бақылайтын инфлюенсерлеріңіздің өнім ұсыныстарына сенесіз бе?'),
        V('Do you think young followers are more easily influenced by ads?', 'Как вы думаете, молодые подписчики легче поддаются влиянию рекламы?', 'Жас жазылушылар жарнамаға оңайырақ ықпалдана ма деп ойлайсыз ба?'),
        V('Should there be stricter laws regulating influencer marketing?', 'Должны ли быть более строгие законы, регулирующие маркетинг через инфлюенсеров?', 'Инфлюенсерлер маркетингін реттейтін қатаңырақ заңдар болуы керек пе?'),
        V('Do you think an influencer promoting too many products loses credibility?', 'Как вы думаете, инфлюенсер, продвигающий слишком много товаров, теряет доверие?', 'Тым көп өнімді жарнамалайтын инфлюенсер сенімділігін жоғалтады деп ойлайсыз ба?'),
        V('Have you ever felt deceived by a sponsored post?', 'Вы когда-нибудь чувствовали себя обманутым спонсируемым постом?', 'Демеушілік жазбадан алданған сезіндіңіз бе?'),
        V('Do you unfollow influencers who promote too many ads?', 'Вы отписываетесь от инфлюенсеров, которые продвигают слишком много рекламы?', 'Тым көп жарнаманы жарнамалайтын инфлюенсерлерден жазылымыңызды алар ма едіңіз?'),
        V('Do you think brand partnerships change how genuine an influencer seems?', 'Как вы думаете, партнёрства с брендами меняют то, насколько искренним кажется инфлюенсер?', 'Брендпен серіктестік инфлюенсердің қаншалықты шынайы көрінетінін өзгертеді деп ойлайсыз ба?'),
        V('Would you rather trust a small creator or a large influencer for recommendations?', 'Вы бы предпочли доверять маленькому создателю или крупному инфлюенсеру для рекомендаций?', 'Ұсыныстар үшін кішкентай жасаушыға сенер ме едіңіз, әлде ірі инфлюенсерге ме?'),
        V('Do you think children should be protected from influencer advertising?', 'Как вы думаете, детей следует защищать от рекламы через инфлюенсеров?', 'Балаларды инфлюенсерлер жарнамасынан қорғау керек деп ойлайсыз ба?'),
        V('Do you think influencers have a responsibility to their followers?', 'Как вы думаете, инфлюенсеры несут ответственность перед подписчиками?', 'Инфлюенсерлердің жазылушылары алдында жауапкершілігі бар деп ойлайсыз ба?'),
        V('Have you ever noticed a hidden ad that wasn\'t clearly labeled?', 'Вы когда-нибудь замечали скрытую рекламу, которая не была чётко обозначена?', 'Анық белгіленбеген жасырын жарнаманы байқадыңыз ба?'),
        V('Do you think it is fair for influencers to earn money this way?', 'Как вы думаете, справедливо ли инфлюенсерам зарабатывать таким способом?', 'Инфлюенсерлердің осылай ақша табуы әділ ме деп ойлайсыз ба?'),
        V('What would make you trust an influencer\'s recommendation more?', 'Что заставило бы вас больше доверять рекомендации инфлюенсера?', 'Инфлюенсердің ұсынысына көбірек сенуге сізге не көмектесер еді?'),
    ],
];

$lessons[] = ['level' => 'pre-intermediate', 'topic' => 'Living Simply and Minimal Consumption', 'background_key' => 'minimal-dark',
    'warmup' => V("Let's talk about simple living. Would you be willing to own fewer things to live more simply?", 'Давайте поговорим о простой жизни. Вы бы согласились иметь меньше вещей, чтобы жить проще?', 'Қарапайым өмір туралы сөйлесейік. Қарапайымырақ өмір сүру үшін аз затқа ие болуға келісер ме едіңіз?'),
    'vocab' => [V('simple living', 'простая жизнь', 'қарапайым өмір'), V('consumption', 'потребление', 'тұтыну'), V('essentials', 'необходимое', 'қажеттілер'), V('materialism', 'материализм', 'материализм'), V('freedom', 'свобода', 'бостандық'), V('excess', 'избыток', 'артықшылық'), V('intentional', 'осознанный', 'саналы'), V('declutter', 'избавляться от лишнего', 'артықтан құтылу'), V('contentment', 'удовлетворённость', 'қанағат'), V('sustainability', 'устойчивость', 'тұрақтылық')],
    'questions' => [
        V('Would you be willing to own fewer things to live more simply?', 'Вы бы согласились иметь меньше вещей, чтобы жить проще?', 'Қарапайымырақ өмір сүру үшін аз затқа ие болуға келісер ме едіңіз?'),
        V('Do you think excess consumption makes people happier or less happy?', 'Как вы думаете, чрезмерное потребление делает людей счастливее или менее счастливыми?', 'Шамадан тыс тұтыну адамдарды бақыттырақ ете ме, әлде бақытсызырақ па деп ойлайсыз ба?'),
        V('Have you ever decluttered your home to feel lighter?', 'Вы когда-нибудь избавлялись от лишнего дома, чтобы почувствовать себя легче?', 'Жеңілдеу сезіну үшін үйіңізден артық заттарды алып тастадыңыз ба?'),
        V('Do you think simple living gives people more freedom?', 'Как вы думаете, простая жизнь даёт людям больше свободы?', 'Қарапайым өмір адамдарға көбірек бостандық береді деп ойлайсыз ба?'),
        V('What do you consider truly essential in your life?', 'Что вы считаете по-настоящему необходимым в вашей жизни?', 'Өміріңізде шынымен қажет деп нені санайсыз?'),
        V('Do you buy things intentionally, or often on impulse?', 'Вы покупаете вещи осознанно, или часто спонтанно?', 'Заттарды саналы сатып аласыз ба, әлде жиі жедел ме?'),
        V('Do you think materialism is increasing in society today?', 'Как вы думаете, материализм в обществе сегодня растёт?', 'Бүгінгі қоғамда материализм өсіп жатыр деп ойлайсыз ба?'),
        V('Would you feel content with a much smaller living space?', 'Вы бы чувствовали удовлетворение в гораздо меньшем жилом пространстве?', 'Әлдеқайда кіші тұрғын кеңістікте қанағаттанар ма едіңіз?'),
        V('Do you think simple living is more sustainable for the planet?', 'Как вы думаете, простая жизнь более устойчива для планеты?', 'Қарапайым өмір планета үшін тұрақтырақ деп ойлайсыз ба?'),
        V('Have you ever felt overwhelmed by how many possessions you own?', 'Вы когда-нибудь чувствовали себя перегруженным количеством своих вещей?', 'Иеленген заттарыңыздың көптігінен шамадан тыс жүктелген сезіндіңіз бе?'),
        V('Would you rather spend money on experiences or possessions?', 'Вы бы предпочли тратить деньги на впечатления или вещи?', 'Ақшаны әсерлерге жұмсағанды қалайсыз ба, әлде заттарға ма?'),
        V('Do you think simple living is realistic in a modern city?', 'Как вы думаете, простая жизнь реальна в современном городе?', 'Қарапайым өмір заманауи қалада шынайы деп ойлайсыз ба?'),
        V('Is it hard for you to resist buying things you don\'t need?', 'Вам трудно устоять перед покупкой того, что вам не нужно?', 'Керек емес заттарды сатып алудан бас тарту сізге қиын ба?'),
        V('Do you think owning less could reduce daily stress?', 'Как вы думаете, владение меньшим количеством вещей может снизить ежедневный стресс?', 'Аз затқа ие болу күнделікті күйзелісті азайта алады деп ойлайсыз ба?'),
        V('What is one thing you could give up to live more simply?', 'От чего одного вы могли бы отказаться, чтобы жить проще?', 'Қарапайымырақ өмір сүру үшін бас тарта алатын бір нәрсе не?'),
    ],
];

$lessons[] = ['level' => 'pre-intermediate', 'topic' => 'The Rise of Home Fitness', 'background_key' => 'energetic',
    'warmup' => V("Let's talk about working out at home. Do you think home workouts are as effective as going to a gym?", 'Давайте поговорим о тренировках дома. Как вы думаете, домашние тренировки так же эффективны, как поход в спортзал?', 'Үйде жаттығу туралы сөйлесейік. Үйде жаттығу спортзалға баруға қарағанда тиімді деп ойлайсыз ба?'),
    'vocab' => [V('home workout', 'домашняя тренировка', 'үй жаттығуы'), V('equipment', 'оборудование', 'жабдық'), V('fitness app', 'фитнес-приложение', 'фитнес қолданбасы'), V('discipline', 'дисциплина', 'тәртіп'), V('motivation', 'мотивация', 'мотивация'), V('space', 'пространство', 'кеңістік'), V('routine', 'распорядок', 'тәртіп'), V('consistency', 'последовательность', 'тұрақтылық'), V('online class', 'онлайн-занятие', 'онлайн сабақ'), V('progress', 'прогресс', 'прогресс')],
    'questions' => [
        V('Do you think home workouts are as effective as gym workouts?', 'Как вы думаете, домашние тренировки так же эффективны, как тренировки в спортзале?', 'Үй жаттығулары спортзал жаттығуларымен бірдей тиімді деп ойлайсыз ба?'),
        V('Do you use fitness apps or online classes to exercise?', 'Вы используете фитнес-приложения или онлайн-занятия для тренировок?', 'Жаттығу үшін фитнес қолданбаларын немесе онлайн сабақтарды пайдаланасыз ба?'),
        V('Is it harder to stay motivated when working out at home?', 'Труднее ли оставаться мотивированным, тренируясь дома?', 'Үйде жаттығу кезінде мотивацияны сақтау қиынырақ па?'),
        V('Do you have enough space at home to exercise comfortably?', 'У вас достаточно места дома, чтобы удобно тренироваться?', 'Үйде ыңғайлы жаттығу үшін жеткілікті орныңыз бар ма?'),
        V('Have you ever bought home fitness equipment you didn\'t use much?', 'Вы когда-нибудь покупали домашнее фитнес-оборудование, которым мало пользовались?', 'Аз пайдаланған үй фитнес жабдығын сатып алдыңыз ба?'),
        V('Do you think discipline matters more at home than at a gym?', 'Как вы думаете, дисциплина важнее дома, чем в спортзале?', 'Тәртіп үйде спортзалдан гөрі маңыздырақ па деп ойлайсыз ба?'),
        V('Would you rather work out alone at home or with others at a gym?', 'Вы бы предпочли тренироваться одни дома или с другими в спортзале?', 'Үйде жалғыз жаттығуды қалайсыз ба, әлде спортзалда басқалармен бе?'),
        V('Do you think online fitness classes will replace gyms?', 'Как вы думаете, онлайн-фитнес-занятия заменят спортзалы?', 'Онлайн фитнес сабақтары спортзалдарды алмастырады деп ойлайсыз ба?'),
        V('Have you built a consistent home workout routine?', 'Вы выработали постоянный распорядок домашних тренировок?', 'Тұрақты үй жаттығу тәртібін қалыптастырдыңыз ба?'),
        V('Do you track your fitness progress with an app?', 'Вы отслеживаете свой фитнес-прогресс с помощью приложения?', 'Фитнес прогресіңізді қолданбамен қадағалайсыз ба?'),
        V('Is cost a big reason people choose home workouts over gyms?', 'Стоимость — большая причина, по которой люди выбирают домашние тренировки вместо спортзалов?', 'Құн адамдардың спортзал орнына үй жаттығуларын таңдауының үлкен себебі ме?'),
        V('Do distractions at home make it harder to exercise?', 'Отвлекающие факторы дома усложняют тренировки?', 'Үйдегі алаңдатушы нәрселер жаттығуды қиындата ма?'),
        V('Would a home gym setup be a good investment for you?', 'Домашний спортзал был бы для вас хорошей инвестицией?', 'Үй спортзалы сіз үшін жақсы инвестиция бола ма?'),
        V('Do you think people take home workouts as seriously as gym sessions?', 'Как вы думаете, люди относятся к домашним тренировкам так же серьёзно, как к занятиям в спортзале?', 'Адамдар үй жаттығуларына спортзал сабақтарындай байыпты қарайды деп ойлайсыз ба?'),
        V('What would make you more consistent with home workouts?', 'Что сделало бы вас более последовательным в домашних тренировках?', 'Үй жаттығуларында тұрақтырақ болуға сізге не көмектесер еді?'),
    ],
];

$lessons[] = ['level' => 'pre-intermediate', 'topic' => 'The Debate Over School Uniforms', 'background_key' => 'professional',
    'warmup' => V("Let's talk about school uniforms. Do you think schools should require students to wear uniforms?", 'Давайте поговорим о школьной форме. Как вы думаете, школы должны требовать от учеников носить форму?', 'Мектеп формасы туралы сөйлесейік. Мектептер оқушыларды форма киюге міндеттеуі керек деп ойлайсыз ба?'),
    'vocab' => [V('uniform', 'форма', 'форма'), V('discipline', 'дисциплина', 'тәртіп'), V('self-expression', 'самовыражение', 'өзін-өзі көрсету'), V('equality', 'равенство', 'теңдік'), V('bullying', 'буллинг', 'қорлау'), V('dress code', 'дресс-код', 'киім коды'), V('conformity', 'конформизм', 'бір қалыпқа түсу'), V('identity', 'идентичность', 'бірегейлік'), V('affordability', 'доступность (по цене)', 'қолжетімділік'), V('appearance', 'внешний вид', 'сыртқы көрініс')],
    'questions' => [
        V('Do you think schools should require uniforms?', 'Как вы думаете, школы должны требовать форму?', 'Мектептер форманы талап етуі керек деп ойлайсыз ба?'),
        V('Did you wear a uniform at school? Did you like it?', 'Вы носили форму в школе? Она вам нравилась?', 'Мектепте форма кидіңіз бе? Ұнады ма?'),
        V('Do you think uniforms reduce bullying about clothing?', 'Как вы думаете, форма снижает буллинг из-за одежды?', 'Форма киім себебінен қорлауды азайтады деп ойлайсыз ба?'),
        V('Do uniforms limit students\' self-expression too much?', 'Форма слишком сильно ограничивает самовыражение учеников?', 'Форма оқушылардың өзін-өзі көрсетуін тым көп шектей ме?'),
        V('Do you think uniforms create a sense of equality among students?', 'Как вы думаете, форма создаёт чувство равенства среди учеников?', 'Форма оқушылар арасында теңдік сезімін тудырады деп ойлайсыз ба?'),
        V('Are uniforms more affordable than regular school clothes?', 'Форма дешевле обычной школьной одежды?', 'Форма кәдімгі мектеп киіміне қарағанда қолжетімдірек пе?'),
        V('Do you think uniforms help students focus more on studying?', 'Как вы думаете, форма помогает ученикам больше сосредоточиться на учёбе?', 'Форма оқушыларға оқуға көбірек шоғырлануға көмектеседі деп ойлайсыз ба?'),
        V('Would you want your own children to wear a uniform at school?', 'Вы бы хотели, чтобы ваши дети носили форму в школе?', 'Балаларыңыздың мектепте форма киюін қалайсыз ба?'),
        V('Do you think uniforms prepare students for professional dress codes later?', 'Как вы думаете, форма готовит учеников к профессиональным дресс-кодам в будущем?', 'Форма оқушыларды кейінгі кәсіби киім кодтарына дайындайды деп ойлайсыз ба?'),
        V('Do you think students lose part of their identity by wearing a uniform?', 'Как вы думаете, ученики теряют часть своей идентичности, нося форму?', 'Оқушылар форма киюмен бірегейліктерінің бір бөлігін жоғалтады деп ойлайсыз ба?'),
        V('Should students have a say in designing their school uniform?', 'Должны ли ученики иметь право голоса при разработке школьной формы?', 'Оқушылардың мектеп формасын жасауда пікірі болуы керек пе?'),
        V('Do you think uniforms make getting ready for school easier?', 'Как вы думаете, форма упрощает сборы в школу?', 'Форма мектепке дайындалуды жеңілдетеді деп ойлайсыз ба?'),
        V('Do you think strict dress codes without full uniforms are a good compromise?', 'Как вы думаете, строгие дресс-коды без полной формы — хороший компромисс?', 'Толық формасыз қатаң киім кодтары жақсы ымыра деп ойлайсыз ба?'),
        V('Have you seen bullying related to expensive clothing brands at school?', 'Вы видели буллинг, связанный с дорогими брендами одежды в школе?', 'Мектепте қымбат киім брендтеріне байланысты қорлауды көрдіңіз бе?'),
        V('What is your final opinion: should uniforms be required or optional?', 'Каково ваше окончательное мнение: форма должна быть обязательной или по желанию?', 'Соңғы пікіріңіз қандай: форма міндетті болуы керек пе, әлде қалауы бойынша ма?'),
    ],
];

$lessons[] = ['level' => 'pre-intermediate', 'topic' => 'The Rise of Audiobooks', 'background_key' => 'calm',
    'warmup' => V("Let's talk about audiobooks. Do you think listening to a book counts as reading it?", 'Давайте поговорим об аудиокнигах. Как вы думаете, прослушивание книги считается её прочтением?', 'Аудиокітаптар туралы сөйлесейік. Кітапты тыңдау оны оқу деп саналады деп ойлайсыз ба?'),
    'vocab' => [V('audiobook', 'аудиокнига', 'аудиокітап'), V('narrator', 'рассказчик', 'баяндаушы'), V('multitasking', 'многозадачность', 'көп тапсырма'), V('retention', 'запоминание', 'есте сақтау'), V('commute', 'дорога на работу', 'жұмысқа қатынау'), V('subscription', 'подписка', 'жазылым'), V('immersive', 'захватывающий (погружающий)', 'сіңіретін'), V('pace', 'темп', 'қарқын'), V('genre', 'жанр', 'жанр'), V('convenience', 'удобство', 'ыңғайлылық')],
    'questions' => [
        V('Do you think listening to an audiobook counts as reading it?', 'Как вы думаете, прослушивание аудиокниги считается её прочтением?', 'Аудиокітапты тыңдау оны оқу деп саналады деп ойлайсыз ба?'),
        V('Do you listen to audiobooks during your commute?', 'Вы слушаете аудиокниги во время дороги на работу?', 'Жұмысқа бару жолында аудиокітап тыңдайсыз ба?'),
        V('Do you remember stories as well from audiobooks as from reading?', 'Вы запоминаете истории из аудиокниг так же хорошо, как из чтения?', 'Аудиокітаптардан оқиғаларды оқудан жақсы есте сақтайсыз ба?'),
        V('Does the narrator\'s voice affect how much you enjoy an audiobook?', 'Голос рассказчика влияет на то, насколько вам нравится аудиокнига?', 'Баяндаушының дауысы аудиокітапты қаншалықты ұнатуыңызға әсер ете ме?'),
        V('Do you multitask while listening to audiobooks?', 'Вы занимаетесь несколькими делами одновременно, слушая аудиокниги?', 'Аудиокітап тыңдағанда бірнеше іспен айналысасыз ба?'),
        V('Do you prefer physical books, e-books, or audiobooks?', 'Вы предпочитаете бумажные книги, электронные книги или аудиокниги?', 'Қағаз кітаптарды ұнатасыз ба, электронды кітаптарды ма, әлде аудиокітаптарды ма?'),
        V('Do you adjust the playback speed when listening to audiobooks?', 'Вы регулируете скорость воспроизведения при прослушивании аудиокниг?', 'Аудиокітап тыңдағанда ойнату жылдамдығын реттейсіз бе?'),
        V('Do you think audiobooks make reading more accessible to busy people?', 'Как вы думаете, аудиокниги делают чтение более доступным для занятых людей?', 'Аудиокітаптар оқуды бос емес адамдар үшін қолжетімдірек ете ме деп ойлайсыз ба?'),
        V('Have you ever fallen asleep while listening to an audiobook?', 'Вы когда-нибудь засыпали, слушая аудиокнигу?', 'Аудиокітап тыңдап жатып ұйықтап кеттіңіз бе?'),
        V('Do you pay for an audiobook subscription service?', 'Вы платите за подписку на сервис аудиокниг?', 'Аудиокітап жазылым қызметіне төлейсіз бе?'),
        V('What genre do you enjoy most as an audiobook?', 'Какой жанр вам больше всего нравится в формате аудиокниги?', 'Аудиокітап ретінде қай жанрды ең көп ұнатасыз?'),
        V('Do you think audiobooks are as immersive as reading a physical book?', 'Как вы думаете, аудиокниги так же захватывающи, как чтение бумажной книги?', 'Аудиокітаптар қағаз кітап оқудай сіңіретін деп ойлайсыз ба?'),
        V('Has an audiobook narrator ever made a book better or worse for you?', 'Рассказчик аудиокниги когда-нибудь делал книгу лучше или хуже для вас?', 'Аудиокітап баяндаушысы сіз үшін кітапты жақсырақ немесе жаманырақ еткен кезі болды ма?'),
        V('Would you choose an audiobook over a movie adaptation of the same story?', 'Вы бы выбрали аудиокнигу вместо экранизации той же истории?', 'Сол оқиғаның экранизациясының орнына аудиокітапты таңдар ма едіңіз?'),
        V('Do you think audiobooks will become more popular than physical books?', 'Как вы думаете, аудиокниги станут популярнее бумажных книг?', 'Аудиокітаптар қағаз кітаптардан танымалырақ болады деп ойлайсыз ба?'),
    ],
];

// ========================= INTERMEDIATE (batch 7) — 15 questions per topic =========================

$lessons[] = ['level' => 'intermediate', 'topic' => 'The Ethics of Wildlife Tourism', 'background_key' => 'nature',
    'warmup' => V("Let's talk about wildlife tourism. Does paying to see or interact with wild animals help or harm conservation?", 'Давайте поговорим об экотуризме с дикими животными. Оплата за просмотр диких животных или взаимодействие с ними помогает или вредит охране природы?', 'Жабайы табиғат туризмі туралы сөйлесейік. Жабайы жануарларды көру немесе олармен әрекеттесу үшін төлеу табиғатты қорғауға көмектесе ме, әлде зиян тигізе ме?'),
    'vocab' => [V('wildlife tourism', 'экотуризм с дикими животными', 'жабайы табиғат туризмі'), V('ethical travel', 'этичное путешествие', 'этикалық саяхат'), V('captive animal', 'животное в неволе', 'тұтқындағы жануар'), V('conservation funding', 'финансирование охраны природы', 'табиғатты қорғауды қаржыландыру'), V('exploitation', 'эксплуатация', 'пайдалану'), V('habitat disruption', 'нарушение среды обитания', 'мекендеу ортасының бұзылуы'), V('sanctuary', 'заповедник', 'қорық'), V('responsible tourism', 'ответственный туризм', 'жауапты туризм'), V('animal welfare', 'благополучие животных', 'жануарлардың әл-ауқаты'), V('eco-certification', 'эко-сертификация', 'эко-сертификаттау')],
    'questions' => [
        V('Have you ever participated in wildlife tourism, like swimming with dolphins or riding elephants?', 'Вы когда-нибудь участвовали в экотуризме с животными, например, плавали с дельфинами или катались на слонах?', 'Дельфиндермен жүзу немесе пілге міну сияқты жабайы табиғат туризміне қатыстыңыз ба?'),
        V('Do you think wildlife tourism funds help conservation efforts?', 'Как вы думаете, средства от экотуризма помогают усилиям по охране природы?', 'Жабайы табиғат туризмінен түскен қаражат табиғатты қорғау күш-жігеріне көмектеседі деп ойлайсыз ба?'),
        V('Do you research whether an animal attraction is ethical before visiting?', 'Вы изучаете, этично ли развлечение с животными, перед посещением?', 'Жануарлармен байланысты аттракционның этикалық екенін бармас бұрын зерттейсіз бе?'),
        V('Should tourists be allowed to touch or ride wild animals?', 'Должны ли туристам разрешать трогать или кататься на диких животных?', 'Туристерге жабайы жануарларды сипауға немесе оларға мінуге рұқсат берілуі керек пе?'),
        V('Do you think some sanctuaries are just disguised tourist traps?', 'Как вы думаете, некоторые заповедники — это просто замаскированные туристические ловушки?', 'Кейбір қорықтар жай ғана жасырылған туристік тұзақтар деп ойлайсыз ба?'),
        V('Would you pay more to visit a certified ethical wildlife experience?', 'Вы бы заплатили больше за посещение сертифицированного этичного опыта с дикой природой?', 'Сертификатталған этикалық жабайы табиғат тәжірибесіне баруға көбірек төлер ме едіңіз?'),
        V('Do you think seeing animals in captivity teaches people to care about them?', 'Как вы думаете, наблюдение за животными в неволе учит людей заботиться о них?', 'Жануарларды тұтқында көру адамдарды оларға қамқорлық жасауға үйретеді деп ойлайсыз ба?'),
        V('Should countries limit the number of tourists visiting sensitive habitats?', 'Должны ли страны ограничивать количество туристов, посещающих чувствительные места обитания?', 'Елдер осал мекендеу орталарына баратын туристердің санын шектеуі керек пе?'),
        V('Do you think local communities benefit fairly from wildlife tourism?', 'Как вы думаете, местные сообщества справедливо получают выгоду от экотуризма с животными?', 'Жергілікті қауымдастықтар жабайы табиғат туризмінен әділ пайда табады деп ойлайсыз ба?'),
        V('Have you ever avoided an attraction because you suspected animal mistreatment?', 'Вы когда-нибудь избегали аттракциона, подозревая жестокое обращение с животными?', 'Жануарларға жаман қарым-қатынас күдіктенгендіктен аттракционнан аулақ болдыңыз ба?'),
        V('Do you think photos with wild animals encourage harmful tourism trends?', 'Как вы думаете, фотографии с дикими животными поощряют вредные тенденции туризма?', 'Жабайы жануарлармен түсірілген суреттер зиянды туризм үрдістерін ынталандырады деп ойлайсыз ба?'),
        V('Should social media platforms discourage posts that promote unethical animal tourism?', 'Должны ли социальные платформы препятствовать постам, продвигающим неэтичный туризм с животными?', 'Әлеуметтік платформалар этикалық емес жануарлар туризмін насихаттайтын жазбаларды тежеуі керек пе?'),
        V('Do you think it is possible to observe wildlife without disrupting it?', 'Как вы думаете, возможно ли наблюдать за дикой природой, не нарушая её?', 'Жабайы табиғатты бұзбай бақылау мүмкін бе деп ойлайсыз ба?'),
        V('Would you rather see animals in the wild or in a well-run sanctuary?', 'Вы бы предпочли видеть животных в дикой природе или в хорошо управляемом заповеднике?', 'Жануарларды жабайы табиғатта көргенді қалайсыз ба, әлде жақсы басқарылатын қорықта ма?'),
        V('What guideline would you give tourists interested in wildlife experiences?', 'Какой совет вы бы дали туристам, заинтересованным в опыте с дикой природой?', 'Жабайы табиғат тәжірибесіне қызығушылық танытатын туристерге қандай нұсқаулық берер едіңіз?'),
    ],
];

$lessons[] = ['level' => 'intermediate', 'topic' => 'The Politics of Food Security', 'background_key' => 'nature',
    'warmup' => V("Let's talk about food security. Why do some countries struggle to feed their populations while others waste huge amounts of food?", 'Давайте поговорим о продовольственной безопасности. Почему некоторые страны с трудом кормят население, а другие выбрасывают огромное количество еды?', 'Азық-түлік қауіпсіздігі туралы сөйлесейік. Неге кейбір елдер халқын тамақтандыруда қиналады, ал басқалары үлкен көлемдегі тамақты ысырап етеді?'),
    'vocab' => [V('food security', 'продовольственная безопасность', 'азық-түлік қауіпсіздігі'), V('food waste', 'пищевые отходы', 'тамақ қалдығы'), V('famine', 'голод', 'аштық'), V('distribution', 'распределение', 'бөлу'), V('subsidy', 'субсидия', 'субсидия'), V('self-sufficiency', 'самообеспеченность', 'өзін-өзі қамтамасыз ету'), V('trade policy', 'торговая политика', 'сауда саясаты'), V('crop yield', 'урожайность', 'өнімділік'), V('scarcity', 'дефицит', 'тапшылық'), V('humanitarian aid', 'гуманитарная помощь', 'гуманитарлық көмек')],
    'questions' => [
        V('Why do you think some countries struggle with food security while others waste food?', 'Как вы думаете, почему некоторые страны борются с продовольственной безопасностью, а другие выбрасывают еду?', 'Сіздің ойыңызша, неге кейбір елдер азық-түлік қауіпсіздігімен күреседі, ал басқалары тамақты ысырап етеді?'),
        V('Do you think food distribution is more of a production problem or a politics problem?', 'Как вы думаете, распределение продовольствия — это больше проблема производства или политики?', 'Тамақты бөлу өндіріс мәселесі ме, әлде саясат мәселесі ме деп ойлайсыз ба?'),
        V('Should wealthy countries be obligated to send food aid to countries in famine?', 'Должны ли богатые страны быть обязаны отправлять продовольственную помощь странам, страдающим от голода?', 'Бай елдер аштыққа ұшыраған елдерге азық-түлік көмегін жіберуге міндетті болуы керек пе?'),
        V('Do you think trade policies unfairly affect food access in poorer nations?', 'Как вы думаете, торговая политика несправедливо влияет на доступ к еде в более бедных странах?', 'Сауда саясаты кедейірек елдердегі тамаққа қолжетімділікке әділетсіз әсер етеді деп ойлайсыз ба?'),
        V('Should countries prioritize self-sufficiency in food production?', 'Должны ли страны отдавать приоритет самообеспеченности в производстве продовольствия?', 'Елдер азық-түлік өндірісінде өзін-өзі қамтамасыз етуге басымдық беруі керек пе?'),
        V('Do you think about food waste in your own household?', 'Вы думаете о пищевых отходах в своём собственном доме?', 'Өз үйіңіздегі тамақ қалдығы туралы ойланасыз ба?'),
        V('Do you think climate change will make food security worse worldwide?', 'Как вы думаете, изменение климата ухудшит продовольственную безопасность по всему миру?', 'Климаттың өзгеруі әлемде азық-түлік қауіпсіздігін нашарлатады деп ойлайсыз ба?'),
        V('Should governments subsidize farmers to keep food prices low?', 'Должны ли правительства субсидировать фермеров, чтобы держать цены на еду низкими?', 'Үкіметтер тамақ бағасын төмен ұстау үшін фермерлерді субсидиялауы керек пе?'),
        V('Do you think humanitarian food aid solves long-term problems, or just short-term ones?', 'Как вы думаете, гуманитарная продовольственная помощь решает долгосрочные проблемы, или только краткосрочные?', 'Гуманитарлық азық-түлік көмегі ұзақ мерзімді мәселелерді шешеді ме, әлде тек қысқа мерзімдіні ме деп ойлайсыз ба?'),
        V('Do you think reducing global food waste could end world hunger?', 'Как вы думаете, сокращение мировых пищевых отходов могло бы положить конец мировому голоду?', 'Әлемдік тамақ қалдығын азайту әлемдік аштықты тоқтата алады деп ойлайсыз ба?'),
        V('Should there be a global system to redistribute surplus food?', 'Должна ли существовать глобальная система для перераспределения излишков продовольствия?', 'Артық тамақты қайта бөлу үшін жаһандық жүйе болуы керек пе?'),
        V('Do you think local food production is more resilient than importing food?', 'Как вы думаете, местное производство продовольствия более устойчиво, чем импорт продуктов?', 'Жергілікті азық-түлік өндірісі тамақ импорттаудан гөрі төзімдірек пе деп ойлайсыз ба?'),
        V('Do you think politics or weather is the bigger threat to food security today?', 'Как вы думаете, что сегодня представляет большую угрозу продовольственной безопасности — политика или погода?', 'Бүгінде саясат па, әлде ауа райы ма азық-түлік қауіпсіздігіне үлкен қауіп деп ойлайсыз ба?'),
        V('Would you support policies that reduce meat production to increase crop yields for people?', 'Вы бы поддержали политику сокращения производства мяса для увеличения урожайности сельхозкультур для людей?', 'Адамдар үшін өнімділікті арттыру мақсатында ет өндірісін азайту саясатын қолдар ма едіңіз?'),
        V('What do you think is the most effective solution to global food insecurity?', 'Что, по-вашему, является наиболее эффективным решением проблемы глобальной продовольственной небезопасности?', 'Сіздің ойыңызша, жаһандық азық-түлік қауіпсіздігі мәселесінің ең тиімді шешімі не?'),
    ],
];

$lessons[] = ['level' => 'intermediate', 'topic' => 'The Ethics of Genetic Testing', 'background_key' => 'minimal-dark',
    'warmup' => V("Let's talk about genetic testing. Would you want to know your genetic risk for diseases you might develop in the future?", 'Давайте поговорим о генетическом тестировании. Хотели бы вы знать свой генетический риск заболеваний, которые могут развиться в будущем?', 'Генетикалық тестілеу туралы сөйлесейік. Болашақта дамуы мүмкін ауруларға генетикалық тәуекеліңізді білгіңіз келе ме?'),
    'vocab' => [V('genetic testing', 'генетическое тестирование', 'генетикалық тестілеу'), V('predisposition', 'предрасположенность', 'бейімділік'), V('privacy', 'конфиденциальность', 'құпиялылық'), V('discrimination', 'дискриминация', 'кемсіту'), V('insurance company', 'страховая компания', 'сақтандыру компаниясы'), V('DNA', 'ДНК', 'ДНҚ'), V('informed consent', 'информированное согласие', 'хабардар келісім'), V('genetic counseling', 'генетическое консультирование', 'генетикалық кеңес беру'), V('anxiety', 'тревога', 'мазасыздық'), V('data security', 'безопасность данных', 'деректер қауіпсіздігі')],
    'questions' => [
        V('Would you want to know your genetic risk for future diseases?', 'Хотели бы вы знать свой генетический риск будущих заболеваний?', 'Болашақ ауруларға генетикалық тәуекеліңізді білгіңіз келе ме?'),
        V('Do you think insurance companies should have access to genetic test results?', 'Как вы думаете, страховые компании должны иметь доступ к результатам генетических тестов?', 'Сақтандыру компанияларының генетикалық тест нәтижелеріне қолжетімділігі болуы керек пе?'),
        V('Have you or anyone you know taken a consumer DNA test?', 'Вы или кто-то из ваших знакомых проходили потребительский ДНК-тест?', 'Сіз немесе таныстарыңыз тұтынушылық ДНҚ тестінен өттіңіз бе?'),
        V('Do you worry about genetic discrimination in employment or insurance?', 'Вы беспокоитесь о генетической дискриминации при трудоустройстве или страховании?', 'Жұмысқа орналасуда немесе сақтандыруда генетикалық кемсітушілік туралы алаңдайсыз ба?'),
        V('Do you think knowing about a genetic risk could cause unnecessary anxiety?', 'Как вы думаете, знание о генетическом риске может вызвать ненужную тревогу?', 'Генетикалық тәуекел туралы білу қажетсіз мазасыздық тудыруы мүмкін деп ойлайсыз ба?'),
        V('Should genetic counseling be required before receiving test results?', 'Должно ли генетическое консультирование быть обязательным перед получением результатов теста?', 'Тест нәтижелерін алмас бұрын генетикалық кеңес беру міндетті болуы керек пе?'),
        V('Do you trust companies to keep your genetic data secure?', 'Вы доверяете компаниям в защите ваших генетических данных?', 'Компаниялардың генетикалық деректеріңізді қауіпсіз сақтайтынына сенесіз бе?'),
        V('Would you want to know if you carry a gene for a disease with no cure?', 'Вы бы хотели знать, есть ли у вас ген заболевания, от которого нет лечения?', 'Емі жоқ ауру геніне ие екеніңізді білгіңіз келе ме?'),
        V('Do you think parents should be allowed to test embryos for genetic conditions?', 'Как вы думаете, родителям следует разрешать тестировать эмбрионы на генетические состояния?', 'Ата-аналарға эмбриондарды генетикалық жағдайларға тестілеуге рұқсат берілуі керек пе?'),
        V('Should genetic test results be shared with family members who might be affected?', 'Должны ли результаты генетических тестов передаваться членам семьи, которых это может касаться?', 'Генетикалық тест нәтижелері әсер етуі мүмкін отбасы мүшелерімен бөлісілуі керек пе?'),
        V('Do you think genetic testing could lead to a new form of social inequality?', 'Как вы думаете, генетическое тестирование может привести к новой форме социального неравенства?', 'Генетикалық тестілеу жаңа әлеуметтік теңсіздік түріне әкелуі мүмкін деп ойлайсыз ба?'),
        V('Would you make different lifestyle choices based on a genetic risk result?', 'Вы бы сделали другой выбор образа жизни на основе результата генетического риска?', 'Генетикалық тәуекел нәтижесіне негізделіп өмір салтын басқаша таңдар ма едіңіз?'),
        V('Do you think this technology is advancing faster than laws can regulate it?', 'Как вы думаете, эта технология развивается быстрее, чем законы могут её регулировать?', 'Бұл технология заңдар реттей алатыннан жылдамырақ дамиды деп ойлайсыз ба?'),
        V('Do you think genetic privacy should be a fundamental right?', 'Как вы думаете, генетическая конфиденциальность должна быть основным правом?', 'Генетикалық құпиялылық негізгі құқық болуы керек деп ойлайсыз ба?'),
        V('What safeguards would make you more comfortable taking a genetic test?', 'Какие меры защиты сделали бы вас более спокойным при прохождении генетического теста?', 'Генетикалық тест тапсыруда өзіңізді ыңғайлырақ сезінуге қандай қорғаныс шаралары көмектесер еді?'),
    ],
];

$insert = $pdo->prepare('INSERT INTO lessons (teacher_id, level, topic, vocab, warmup, questions, background_key) VALUES (:teacher_id, :level, :topic, :vocab, :warmup, :questions, :background_key)');
$count = 0;
foreach ($lessons as $lesson) {
    $insert->execute([
        ':teacher_id' => $teacherId, ':level' => $lesson['level'], ':topic' => $lesson['topic'],
        ':vocab' => json_encode($lesson['vocab'], JSON_UNESCAPED_UNICODE),
        ':warmup' => json_encode($lesson['warmup'], JSON_UNESCAPED_UNICODE),
        ':questions' => json_encode($lesson['questions'], JSON_UNESCAPED_UNICODE),
        ':background_key' => $lesson['background_key'],
    ]);
    $count++;
}
echo "Inserted $count lessons for teacher '$username' (id $teacherId).\n";
