<?php
declare(strict_types=1);
$configPath = '/home/u856637812/config/speaking_club_config.php';
$cfg = require $configPath;
$pdo = new PDO("mysql:host={$cfg['db_host']};dbname={$cfg['db_name']};charset=utf8mb4", $cfg['db_user'], $cfg['db_pass'], [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);
$username = $argv[1] ?? null;
if (!$username) { fwrite(STDERR, "Usage: php seed_lessons_batch6.php <teacher_username>\n"); exit(1); }
$stmt = $pdo->prepare('SELECT id FROM teachers WHERE username = ?');
$stmt->execute([$username]);
$teacher = $stmt->fetch(PDO::FETCH_ASSOC);
if (!$teacher) { fwrite(STDERR, "Teacher not found: $username\n"); exit(1); }
$teacherId = (int)$teacher['id'];
function V(string $en, string $ru, string $kz): array { return ['en' => $en, 'ru' => $ru, 'kz' => $kz]; }
$lessons = [];

// ========================= BEGINNER (batch 6) — 15 questions per topic =========================

$lessons[] = ['level' => 'beginner', 'topic' => 'Talking on the Phone', 'background_key' => 'calm',
    'warmup' => V("Let's talk about phone calls. Do you prefer calling people or texting them?", 'Давайте поговорим о звонках. Вы предпочитаете звонить людям или писать им?', 'Телефон қоңыраулары туралы сөйлесейік. Адамдарға қоңырау шалғанды ұнатасыз ба, әлде жазғанды ма?'),
    'vocab' => [V('call', 'звонок', 'қоңырау'), V('hang up', 'вешать трубку', 'тұтқаны қою'), V('ring', 'звонить', 'шылдырлау'), V('busy line', 'занятая линия', 'бос емес желі'), V('voicemail', 'голосовая почта', 'дауыстық пошта'), V('dial', 'набирать номер', 'нөмір теру'), V('answer', 'отвечать', 'жауап беру'), V('missed call', 'пропущенный звонок', 'жіберіп алған қоңырау'), V('speaker', 'громкая связь', 'динамик'), V('text', 'смс', 'смс')],
    'questions' => [
        V('Do you prefer calling or texting?', 'Вы предпочитаете звонить или писать?', 'Қоңырау шалғанды ұнатасыз ба, әлде жазғанды ма?'),
        V('How often do you miss calls?', 'Как часто вы пропускаете звонки?', 'Қаншалықты жиі қоңырауды жіберіп аласыз?'),
        V('Do you leave voicemail messages?', 'Вы оставляете голосовые сообщения?', 'Дауыстық хабарлама қалдырасыз ба?'),
        V('Do you answer calls from unknown numbers?', 'Вы отвечаете на звонки с незнакомых номеров?', 'Белгісіз нөмірлерден түскен қоңырауларға жауап бересіз бе?'),
        V('Do you use speaker phone often?', 'Вы часто пользуетесь громкой связью?', 'Динамикті жиі пайдаланасыз ба?'),
        V('Who do you call the most?', 'Кому вы звоните чаще всего?', 'Ең жиі кімге қоңырау шаласыз?'),
        V('Do you get nervous before an important phone call?', 'Вы нервничаете перед важным звонком?', 'Маңызды қоңырау алдында толқисыз ба?'),
        V('How long is your average phone call?', 'Сколько в среднем длится ваш звонок?', 'Орташа қоңырауыңыз қанша уақытқа созылады?'),
        V('Do you call your family often?', 'Вы часто звоните семье?', 'Отбасыңызға жиі қоңырау шаласыз ба?'),
        V('Have you ever had a bad phone connection during a call?', 'У вас когда-нибудь была плохая связь во время звонка?', 'Қоңырау кезінде байланыс нашар болды ма?'),
        V('Do you prefer video calls or voice calls?', 'Вы предпочитаете видеозвонки или голосовые?', 'Бейнеқоңырауды ұнатасыз ба, әлде дауыстық қоңырауды ма?'),
        V('What do you do while talking on the phone?', 'Что вы делаете во время телефонного разговора?', 'Телефонмен сөйлескенде не істейсіз?'),
        V('Do you keep phone calls short, or talk for a long time?', 'Вы делаете звонки короткими, или говорите долго?', 'Қоңырауларыңызды қысқа ұстайсыз ба, әлде ұзақ сөйлейсіз бе?'),
        V('Is it easier for you to explain things by phone or in person?', 'Вам легче объяснять что-то по телефону или лично?', 'Түсіндіру сізге телефонмен оңай ма, әлде жеке ме?'),
        V('Do you silence your phone during meetings or class?', 'Вы отключаете звук телефона во время встреч или занятий?', 'Жиналыс немесе сабақ кезінде телефонды дыбыссыз қоясыз ба?'),
    ],
];

$lessons[] = ['level' => 'beginner', 'topic' => 'At the Barber or Hairdresser', 'background_key' => 'playful',
    'warmup' => V("Let's talk about haircuts. How often do you go to the barber or hairdresser?", 'Давайте поговорим о стрижках. Как часто вы ходите в парикмахерскую?', 'Шаш қию туралы сөйлесейік. Шаштаразға қаншалықты жиі барасыз?'),
    'vocab' => [V('haircut', 'стрижка', 'шаш қию'), V('trim', 'подравнивание', 'жеңіл қию'), V('style', 'стиль', 'стиль'), V('mirror', 'зеркало', 'айна'), V('scissors', 'ножницы', 'қайшы'), V('comb', 'расчёска', 'тарақ'), V('appointment', 'запись', 'жазылу'), V('color', 'краска (для волос)', 'бояу'), V('short', 'короткий', 'қысқа'), V('long', 'длинный', 'ұзын')],
    'questions' => [
        V('How often do you get a haircut?', 'Как часто вы стрижётесь?', 'Шашыңызды қаншалықты жиі қиясыз?'),
        V('Do you prefer short or long hair?', 'Вы предпочитаете короткие или длинные волосы?', 'Қысқа шашты ұнатасыз ба, әлде ұзынды ма?'),
        V('Do you make an appointment before going?', 'Вы записываетесь перед посещением?', 'Барудан бұрын жазыласыз ба?'),
        V('Have you ever colored your hair?', 'Вы когда-нибудь красили волосы?', 'Шашыңызды боядыңыз ба?'),
        V('Do you trust your barber to choose a style for you?', 'Вы доверяете своему парикмахеру выбрать стиль для вас?', 'Шаштаразыңызға сіз үшін стиль таңдауға сенесіз бе?'),
        V('Have you ever been unhappy with a haircut?', 'Вы когда-нибудь были недовольны стрижкой?', 'Шаш қиюға риза болмаған кезіңіз болды ма?'),
        V('Do you always go to the same hairdresser?', 'Вы всегда ходите к одному и тому же парикмахеру?', 'Әрдайым бір парикмахерге барасыз ба?'),
        V('Do you like watching yourself in the mirror during a haircut?', 'Вам нравится смотреть на себя в зеркало во время стрижки?', 'Шаш қиылу кезінде айнадан өзіңізге қарағанды ұнатасыз ба?'),
        V('How do you feel right after getting a fresh haircut?', 'Как вы себя чувствуете сразу после свежей стрижки?', 'Жаңа қиылған шаштан кейін өзіңізді қалай сезінесіз?'),
        V('Would you ever try a very different hairstyle?', 'Вы бы попробовали совсем другую причёску?', 'Мүлдем басқа шаш үлгісін сынап көрер ме едіңіз?'),
        V('Do men and women usually go to the same kind of hair salon in your country?', 'Мужчины и женщины обычно ходят в одинаковые парикмахерские в вашей стране?', 'Еліңізде ерлер мен әйелдер әдетте бір типтегі шаштаразға барады ма?'),
        V('Do you tip your hairdresser?', 'Вы даёте чаевые парикмахеру?', 'Парикмахерге шайпұл бересіз бе?'),
        V('How long does a normal haircut take for you?', 'Сколько времени обычно занимает ваша стрижка?', 'Кәдімгі шаш қию сізде қанша уақыт алады?'),
        V('Do you bring a photo to show the style you want?', 'Вы приносите фото, чтобы показать желаемый стиль?', 'Қалаған стиліңізді көрсету үшін фото аласыз ба?'),
        V('Is it stressful for you to try a new hairdresser?', 'Для вас стрессово пробовать нового парикмахера?', 'Жаңа парикмахерді сынап көру сіз үшін күйзелісті ме?'),
    ],
];

$lessons[] = ['level' => 'beginner', 'topic' => 'Simple Cleaning Tasks', 'background_key' => 'calm',
    'warmup' => V("Let's talk about cleaning. What cleaning tasks do you do at home?", 'Давайте поговорим об уборке. Какие уборочные дела вы делаете дома?', 'Тазалау туралы сөйлесейік. Үйде қандай тазалау жұмыстарын істейсіз?'),
    'vocab' => [V('mop', 'мыть шваброй', 'едені жуу'), V('dust', 'вытирать пыль', 'шаң сүрту'), V('vacuum', 'пылесосить', 'шаңсорғышпен тазалау'), V('wipe', 'протирать', 'сүрту'), V('scrub', 'тереть', 'ысқылау'), V('polish', 'полировать', 'жылтырату'), V('spotless', 'безупречно чистый', 'мінсіз таза'), V('mess', 'беспорядок', 'ретсіздік'), V('trash bin', 'мусорное ведро', 'қоқыс шелегі'), V('laundry basket', 'корзина для белья', 'кір себеті')],
    'questions' => [
        V('What cleaning task do you do most often?', 'Какое уборочное дело вы делаете чаще всего?', 'Ең жиі қандай тазалау жұмысын істейсіз?'),
        V('Do you enjoy cleaning, or find it boring?', 'Вам нравится убираться, или это скучно?', 'Тазалауды ұнатасыз ба, әлде жалықтырады ма?'),
        V('Is your home usually spotless or a bit messy?', 'Ваш дом обычно безупречно чист или немного в беспорядке?', 'Үйіңіз әдетте мінсіз таза ма, әлде сәл ретсіз бе?'),
        V('Do you vacuum every week?', 'Вы пылесосите каждую неделю?', 'Апта сайын шаңсорғышпен тазалайсыз ба?'),
        V('Who empties the trash bin in your home?', 'Кто выносит мусор у вас дома?', 'Үйіңізде қоқыс шелегін кім босатады?'),
        V('Do you clean more before guests arrive?', 'Вы убираетесь больше перед приходом гостей?', 'Қонақтар келер алдында көбірек тазалайсыз ба?'),
        V('Do you clean alone, or does your family help?', 'Вы убираетесь одни, или семья помогает?', 'Жалғыз тазалайсыз ба, әлде отбасы көмектесе ме?'),
        V('What cleaning tool could you not live without?', 'Без какого чистящего инструмента вы не могли бы жить?', 'Қандай тазалау құралынсыз өмір сүре алмас едіңіз?'),
        V('Do you clean in the morning or at night?', 'Вы убираетесь утром или ночью?', 'Таңертең тазалайсыз ба, әлде түнде ме?'),
        V('How do you feel after cleaning a messy room?', 'Как вы себя чувствуете после уборки грязной комнаты?', 'Ретсіз бөлмені тазалағаннан кейін өзіңізді қалай сезінесіз?'),
        V('Do you separate laundry by color before washing?', 'Вы сортируете бельё по цвету перед стиркой?', 'Жуу алдында кірді түсіне қарай бөлесіз бе?'),
        V('What part of cleaning do you dislike the most?', 'Какую часть уборки вы не любите больше всего?', 'Тазалаудың қай бөлігін ең көп ұнатпайсыз?'),
        V('Do you use natural or chemical cleaning products?', 'Вы используете натуральные или химические чистящие средства?', 'Табиғи немесе химиялық тазалау құралдарын пайдаланасыз ба?'),
        V('Would you ever hire someone to clean your home?', 'Вы бы наняли кого-то для уборки дома?', 'Үйіңізді тазалауға біреуді жалдар ма едіңіз?'),
        V('Do you have a cleaning schedule, or clean when you notice mess?', 'У вас есть график уборки, или вы убираетесь, когда замечаете беспорядок?', 'Тазалау кестеңіз бар ма, әлде ретсіздікті байқағанда тазалайсыз ба?'),
    ],
];

$lessons[] = ['level' => 'beginner', 'topic' => 'Colors of Nature', 'background_key' => 'nature',
    'warmup' => V("Let's talk about colors in nature. What colors do you see when you look outside?", 'Давайте поговорим о цветах в природе. Какие цвета вы видите, когда смотрите на улицу?', 'Табиғаттағы түстер туралы сөйлесейік. Далаға қарағанда қандай түстерді көресіз?'),
    'vocab' => [V('green grass', 'зелёная трава', 'жасыл шөп'), V('blue sky', 'голубое небо', 'көк аспан'), V('brown soil', 'коричневая почва', 'қоңыр топырақ'), V('yellow sun', 'жёлтое солнце', 'сары күн'), V('white cloud', 'белое облако', 'ақ бұлт'), V('grey rain', 'серый дождь', 'сұр жаңбыр'), V('colorful flowers', 'разноцветные цветы', 'түрлі-түсті гүлдер'), V('dark night', 'тёмная ночь', 'қараңғы түн'), V('bright day', 'яркий день', 'жарқын күн'), V('rainbow', 'радуга', 'кемпірқосақ')],
    'questions' => [
        V('What color do you see the most around you right now?', 'Какой цвет вы видите чаще всего вокруг себя сейчас?', 'Қазір айналаңызда ең көп қандай түсті көресіз?'),
        V('Do you like grey rainy days or bright sunny days more?', 'Вам больше нравятся серые дождливые дни или яркие солнечные?', 'Сұр жаңбырлы күндер ұнай ма, әлде жарқын күнді күндер ме?'),
        V('Have you ever seen a rainbow? Where?', 'Вы когда-нибудь видели радугу? Где?', 'Кемпірқосақты көрдіңіз бе? Қайда?'),
        V('What is your favorite color of flower?', 'Какой ваш любимый цвет цветка?', 'Гүлдің сүйікті түсі қандай?'),
        V('Do you enjoy watching the sky change color at sunset?', 'Вам нравится наблюдать, как небо меняет цвет на закате?', 'Күн батқанда аспанның түсінің өзгеруін бақылағанды ұнатасыз ба?'),
        V('Does the color green make you think of nature?', 'Зелёный цвет напоминает вам о природе?', 'Жасыл түс сізге табиғатты еске түсіре ме?'),
        V('What natural color would you choose to paint your room?', 'Какой природный цвет вы бы выбрали для покраски комнаты?', 'Бөлмеңізді бояу үшін қандай табиғи түсті таңдар едіңіз?'),
        V('Do the colors of the seasons change a lot where you live?', 'Цвета времён года сильно меняются там, где вы живёте?', 'Тұратын жеріңізде мезгілдердің түстері көп өзгере ме?'),
        V('Have you ever taken a photo of a beautiful natural color?', 'Вы когда-нибудь фотографировали красивый природный цвет?', 'Әдемі табиғи түстің суретін түсірдіңіз бе?'),
        V('Do you notice the color of the soil where you live?', 'Вы замечаете цвет почвы там, где вы живёте?', 'Тұратын жеріңіздегі топырақтың түсін байқайсыз ба?'),
        V('Which season has your favorite natural colors?', 'В какое время года ваши любимые природные цвета?', 'Қай мезгілде сіздің сүйікті табиғи түстеріңіз бар?'),
        V('Do bright colors or soft colors calm you more?', 'Яркие цвета или мягкие цвета успокаивают вас больше?', 'Жарқын түстер ме, әлде жұмсақ түстер ме сізді көбірек тыныштандырады?'),
        V('Do you grow colorful flowers at home?', 'Вы выращиваете разноцветные цветы дома?', 'Үйде түрлі-түсті гүлдер өсіресіз бе?'),
        V('What color of sky do you like best — clear blue or cloudy white?', 'Какое небо вам нравится больше — ясное голубое или облачное белое?', 'Қандай аспанды ұнатасыз — ашық көк пе, әлде бұлтты ақ па?'),
        V('Does looking at nature\'s colors help you relax?', 'Наблюдение за цветами природы помогает вам расслабиться?', 'Табиғат түстеріне қарау демалуыңызға көмектесе ме?'),
    ],
];

$lessons[] = ['level' => 'beginner', 'topic' => 'My Daily Meals', 'background_key' => 'playful',
    'warmup' => V("Let's talk about meals. What do you usually eat during the day?", 'Давайте поговорим о приёмах пищи. Что вы обычно едите в течение дня?', 'Тамақтану туралы сөйлесейік. Күн бойы әдетте не жейсіз?'),
    'vocab' => [V('breakfast', 'завтрак', 'таңғы ас'), V('lunch', 'обед', 'түскі ас'), V('dinner', 'ужин', 'кешкі ас'), V('snack', 'перекус', 'жеңіл тамақ'), V('hungry', 'голодный', 'аш'), V('full', 'сытый', 'тоқ'), V('tasty', 'вкусный', 'дәмді'), V('portion', 'порция', 'үлес'), V('cook', 'готовить', 'пісіру'), V('share', 'делиться', 'бөлісу')],
    'questions' => [
        V('What did you eat for breakfast today?', 'Что вы ели на завтрак сегодня?', 'Бүгін таңғы асқа не жедіңіз?'),
        V('Do you eat snacks between meals?', 'Вы перекусываете между приёмами пищи?', 'Тамақ арасында жеңіл тамақ жейсіз бе?'),
        V('Do you cook your own meals?', 'Вы готовите себе еду сами?', 'Тамағыңызды өзіңіз пісіресіз бе?'),
        V('Do you prefer big portions or small ones?', 'Вы предпочитаете большие порции или маленькие?', 'Үлкен үлестерді ұнатасыз ба, әлде кішіні ме?'),
        V('Do you like sharing food with others?', 'Вам нравится делиться едой с другими?', 'Тамақпен басқалармен бөлісуді ұнатасыз ба?'),
        V('What is your favorite meal of the day?', 'Какой ваш любимый приём пищи?', 'Күндегі сүйікті тамағыңыз қайсы?'),
        V('Which meal do you usually eat the fastest?', 'Какой приём пищи вы обычно едите быстрее всего?', 'Қай тамақты әдетте ең тез жейсіз?'),
        V('Do you skip meals when you are busy?', 'Вы пропускаете приёмы пищи, когда заняты?', 'Бос болмаған кезде тамақтануды өткізіп жібересіз бе?'),
        V('What is the tastiest meal you have eaten recently?', 'Какая самая вкусная еда, которую вы ели недавно?', 'Жақында жеген ең дәмді тамағыңыз қандай?'),
        V('Do you eat dinner alone or with family?', 'Вы ужинаете одни или с семьёй?', 'Кешкі асты жалғыз жейсіз бе, әлде отбасымен ме?'),
        V('Do you feel hungry at the same time every day?', 'Вы чувствуете голод в одно и то же время каждый день?', 'Күн сайын бір уақытта аш сезінесіз бе?'),
        V('Do you eat while watching TV or your phone?', 'Вы едите, смотря телевизор или телефон?', 'Теледидар немесе телефон қарап жейсіз бе?'),
        V('What is a meal you eat only on special occasions?', 'Какая еда, которую вы едите только по особым случаям?', 'Тек ерекше жағдайларда жейтін тамағыңыз бар ма?'),
        V('Do you prefer eating out or eating at home?', 'Вы предпочитаете есть вне дома или дома?', 'Сыртта тамақтанғанды ұнатасыз ба, әлде үйде ме?'),
        V('How many meals do you eat in a normal day?', 'Сколько раз вы едите в обычный день?', 'Кәдімгі күнде неше рет тамақтанасыз?'),
    ],
];

$lessons[] = ['level' => 'beginner', 'topic' => 'Emotions at Work or School', 'background_key' => 'minimal-dark',
    'warmup' => V("Let's talk about feelings at work or school. How do you usually feel during the day?", 'Давайте поговорим о чувствах на работе или в школе. Как вы обычно себя чувствуете в течение дня?', 'Жұмыстағы немесе мектептегі сезімдер туралы сөйлесейік. Күн бойы әдетте өзіңізді қалай сезінесіз?'),
    'vocab' => [V('bored', 'скучающий', 'жалыққан'), V('excited', 'взволнованный', 'қуанышты'), V('proud', 'гордый', 'мақтанышты'), V('nervous', 'нервный', 'толқыған'), V('relieved', 'испытывающий облегчение', 'жеңілдеген'), V('frustrated', 'разочарованный', 'ренжіген'), V('motivated', 'мотивированный', 'ынталанған'), V('confused', 'растерянный', 'шатасқан'), V('calm', 'спокойный', 'сабырлы'), V('satisfied', 'удовлетворённый', 'қанағаттанған')],
    'questions' => [
        V('Do you often feel bored at work or school?', 'Вы часто скучаете на работе или в школе?', 'Жұмыста немесе мектепте жиі жалығасыз ба?'),
        V('What makes you feel proud during the day?', 'Что заставляет вас гордиться в течение дня?', 'Күн бойы сізді не мақтаныш сезіндіреді?'),
        V('Do you get nervous before a big task?', 'Вы нервничаете перед важной задачей?', 'Үлкен тапсырма алдында толқисыз ба?'),
        V('What helps you feel calm during a busy day?', 'Что помогает вам чувствовать себя спокойно в напряжённый день?', 'Қарбалас күнде сабырлы сезінуге не көмектеседі?'),
        V('Do you feel satisfied at the end of a productive day?', 'Вы чувствуете удовлетворение в конце продуктивного дня?', 'Өнімді күннің соңында қанағаттанасыз ба?'),
        V('What usually makes you feel motivated?', 'Что обычно вас мотивирует?', 'Сізді әдетте не ынталандырады?'),
        V('Have you ever felt relieved after finishing a hard task?', 'Вы когда-нибудь чувствовали облегчение после трудной задачи?', 'Қиын тапсырманы бітіргеннен кейін жеңілдеу сезіндіңіз бе?'),
        V('Do you get frustrated when things do not go as planned?', 'Вы расстраиваетесь, когда всё идёт не по плану?', 'Жоспар бойынша болмаса ренжисіз бе?'),
        V('Have you ever felt confused during a lesson or meeting?', 'Вы когда-нибудь чувствовали растерянность на уроке или встрече?', 'Сабақта немесе жиналыста шатасқан кезіңіз болды ма?'),
        V('Does talking to someone help when you feel frustrated?', 'Разговор с кем-то помогает, когда вы расстроены?', 'Ренжіген кезде біреумен сөйлесу көмектесе ме?'),
        V('Do you feel more excited at the start or the end of the day?', 'Вы чувствуете больше волнения в начале или в конце дня?', 'Күннің басында қуанышты сезінесіз бе, әлде соңында ма?'),
        V('What is one thing that always makes you feel calm?', 'Что всегда заставляет вас чувствовать себя спокойно?', 'Сізді әрдайым сабырлы сезіндіретін бір нәрсе не?'),
        V('Do you share your feelings with coworkers or classmates?', 'Вы делитесь чувствами с коллегами или одноклассниками?', 'Сезімдеріңізбен әріптестеріңізбен немесе сыныптастарыңызбен бөлісесіз бе?'),
        V('Have you ever hidden how you really felt at work or school?', 'Вы когда-нибудь скрывали, как вы на самом деле себя чувствуете на работе или в школе?', 'Жұмыста немесе мектепте шынымен қалай сезінетініңізді жасырдыңыз ба?'),
        V('What emotion do you feel most often during a normal week?', 'Какую эмоцию вы чувствуете чаще всего в обычную неделю?', 'Кәдімгі аптада қандай эмоцияны ең жиі сезінесіз?'),
    ],
];

$lessons[] = ['level' => 'beginner', 'topic' => 'Talking About Distance', 'background_key' => 'calm',
    'warmup' => V("Let's talk about distance. How far do you travel to get to work or school?", 'Давайте поговорим о расстоянии. Как далеко вам ехать на работу или в школу?', 'Қашықтық туралы сөйлесейік. Жұмысқа немесе мектепке қаншалықты алыс барасыз?'),
    'vocab' => [V('near', 'близко', 'жақын'), V('far', 'далеко', 'алыс'), V('close', 'рядом', 'жақын'), V('kilometer', 'километр', 'километр'), V('mile', 'миля', 'миля'), V('walk there', 'дойти пешком', 'жаяу бару'), V('drive there', 'доехать на машине', 'көлікпен бару'), V('short trip', 'короткая поездка', 'қысқа сапар'), V('long trip', 'долгая поездка', 'ұзақ сапар'), V('halfway', 'на полпути', 'жарты жол')],
    'questions' => [
        V('How far do you live from your workplace or school?', 'Как далеко вы живёте от работы или школы?', 'Жұмыс немесе мектептен қаншалықты алыс тұрасыз?'),
        V('Do you walk or drive to get to nearby places?', 'Вы ходите пешком или ездите на машине до ближайших мест?', 'Жақын жерлерге жаяу барасыз ба, әлде көлікпен бе?'),
        V('What is the longest trip you have ever taken?', 'Какая самая долгая поездка у вас была?', 'Барған ең ұзақ сапарыңыз қандай болды?'),
        V('Do you prefer places that are close or far from the city?', 'Вы предпочитаете места близко или далеко от города?', 'Қалаға жақын жерлерді ұнатасыз ба, әлде алысты ма?'),
        V('How many kilometers do you travel in a normal week?', 'Сколько километров вы проезжаете за обычную неделю?', 'Кәдімгі аптада қанша километр жүресіз?'),
        V('Do short trips or long trips tire you more?', 'Что вас утомляет больше — короткие поездки или долгие?', 'Қысқа сапарлар ма, әлде ұзақ сапарлар ма сізді көбірек шаршатады?'),
        V('Do you know the distance to your favorite place by heart?', 'Вы знаете расстояние до любимого места наизусть?', 'Сүйікті орныңызға дейінгі қашықтықты жатқа білесіз бе?'),
        V('Have you ever stopped halfway through a long trip to rest?', 'Вы когда-нибудь останавливались на полпути в долгой поездке, чтобы отдохнуть?', 'Ұзақ сапарда жарты жолда демалу үшін тоқтадыңыз ба?'),
        V('Would you walk a long distance to save money on transport?', 'Вы бы прошли большое расстояние пешком, чтобы сэкономить на транспорте?', 'Көлікке ақша үнемдеу үшін ұзақ қашықтықты жаяу жүрер ме едіңіз?'),
        V('Is a short distance in your city still difficult because of traffic?', 'Короткое расстояние в вашем городе всё ещё трудное из-за пробок?', 'Қалаңыздағы қысқа қашықтық көлік кептелісі себебінен әлі қиын ба?'),
        V('Do you measure distance in kilometers or miles?', 'Вы измеряете расстояние в километрах или милях?', 'Қашықтықты километрмен өлшейсіз бе, әлде мильмен бе?'),
        V('What is the farthest place you have traveled to?', 'Какое самое дальнее место, куда вы путешествовали?', 'Барған ең алыс жеріңіз қайсы?'),
        V('Do you avoid long trips if possible?', 'Вы избегаете долгих поездок, если возможно?', 'Мүмкін болса, ұзақ сапарлардан аулақ боласыз ба?'),
        V('Would you move somewhere far from your family for a good job?', 'Вы бы переехали далеко от семьи ради хорошей работы?', 'Жақсы жұмыс үшін отбасыңыздан алыс жерге көшер ме едіңіз?'),
        V('How do you pass the time during a long trip?', 'Как вы проводите время во время долгой поездки?', 'Ұзақ сапар кезінде уақытты қалай өткізесіз?'),
    ],
];

$lessons[] = ['level' => 'beginner', 'topic' => 'My Favorite Holiday', 'background_key' => 'warm',
    'warmup' => V("Let's talk about holidays. What is your favorite holiday, and how do you celebrate it?", 'Давайте поговорим о праздниках. Какой ваш любимый праздник и как вы его отмечаете?', 'Мерекелер туралы сөйлесейік. Сүйікті мерекеңіз қайсы және оны қалай тойлайсыз?'),
    'vocab' => [V('celebrate', 'праздновать', 'тойлау'), V('gather', 'собираться', 'жиналу'), V('gift', 'подарок', 'сыйлық'), V('decorate', 'украшать', 'безендіру'), V('holiday meal', 'праздничная еда', 'мерекелік тамақ'), V('family time', 'семейное время', 'отбасылық уақыт'), V('tradition', 'традиция', 'дәстүр'), V('countdown', 'обратный отсчёт', 'кері санау'), V('festive', 'праздничный', 'мерекелік'), V('memory', 'воспоминание', 'естелік')],
    'questions' => [
        V('What is your favorite holiday?', 'Какой ваш любимый праздник?', 'Сүйікті мерекеңіз қайсы?'),
        V('Does your family gather together for holidays?', 'Ваша семья собирается вместе на праздники?', 'Отбасыңыз мерекелерде бірге жиналады ма?'),
        V('Do you like decorating your home for holidays?', 'Вам нравится украшать дом к праздникам?', 'Мерекелерге үйіңізді безендіргенді ұнатасыз ба?'),
        V('What is a special holiday memory you have?', 'Какое особенное праздничное воспоминание у вас есть?', 'Сізде қандай ерекше мерекелік естелік бар?'),
        V('Do you give or receive gifts on your favorite holiday?', 'Вы дарите или получаете подарки на любимый праздник?', 'Сүйікті мерекеде сыйлық сыйлайсыз ба, әлде аласыз ба?'),
        V('What food do you always eat on that holiday?', 'Какую еду вы всегда едите в этот праздник?', 'Бұл мерекеде әрдайым қандай тамақ жейсіз?'),
        V('Do you count down the days before your favorite holiday?', 'Вы считаете дни до любимого праздника?', 'Сүйікті мерекеге дейінгі күндерді санайсыз ба?'),
        V('Has your favorite holiday changed since you were a child?', 'Ваш любимый праздник изменился с детства?', 'Сүйікті мерекеңіз балалық шағыңыздан бері өзгерді ме?'),
        V('Do you travel to see family during holidays?', 'Вы путешествуете, чтобы увидеть семью во время праздников?', 'Мерекелерде отбасыны көру үшін саяхаттайсыз ба?'),
        V('What holiday tradition would you never want to lose?', 'Какую праздничную традицию вы никогда не хотели бы потерять?', 'Қай мерекелік дәстүрді ешқашан жоғалтқыңыз келмейді?'),
        V('Do you prefer quiet holidays or big celebrations?', 'Вы предпочитаете тихие праздники или большие торжества?', 'Тыныш мерекелерді ұнатасыз ба, әлде үлкен тойларды ма?'),
        V('Is there a holiday from another country you find interesting?', 'Есть ли праздник другой страны, который вам интересен?', 'Басқа елдің қызықты көрінетін мерекесі бар ма?'),
        V('Do you take photos during holiday celebrations?', 'Вы фотографируете во время праздничных торжеств?', 'Мерекелік тойлар кезінде сурет түсіресіз бе?'),
        V('What is the best gift you ever received on a holiday?', 'Какой лучший подарок вы получали на праздник?', 'Мерекеде алған ең жақсы сыйлығыңыз қандай болды?'),
        V('Do you feel more relaxed or more busy during holidays?', 'Вы чувствуете себя более расслабленным или более занятым во время праздников?', 'Мерекелерде өзіңізді сабырлырақ сезінесіз бе, әлде бос емесірек пе?'),
    ],
];

$lessons[] = ['level' => 'beginner', 'topic' => 'Simple Weather Reactions', 'background_key' => 'nature',
    'warmup' => V("Let's talk about reacting to weather. What do you do when the weather changes suddenly?", 'Давайте поговорим о реакции на погоду. Что вы делаете, когда погода внезапно меняется?', 'Ауа райына реакция туралы сөйлесейік. Ауа райы кенеттен өзгергенде не істейсіз?'),
    'vocab' => [V('too hot', 'слишком жарко', 'тым ыстық'), V('too cold', 'слишком холодно', 'тым суық'), V('just right', 'в самый раз', 'дәл келеді'), V('wear a coat', 'надеть пальто', 'пальто кию'), V('stay inside', 'оставаться внутри', 'ішінде қалу'), V('go outside', 'выйти на улицу', 'сыртқа шығу'), V('sunny day', 'солнечный день', 'күнді күн'), V('rainy day', 'дождливый день', 'жаңбырлы күн'), V('pack an umbrella', 'взять зонт', 'қолшатыр алу'), V('check forecast', 'проверить прогноз', 'болжамды тексеру')],
    'questions' => [
        V('Do you check the forecast before leaving home?', 'Вы проверяете прогноз перед выходом из дома?', 'Үйден шықпас бұрын болжамды тексересіз бе?'),
        V('What do you do when it is too hot outside?', 'Что вы делаете, когда на улице слишком жарко?', 'Далада тым ыстық болғанда не істейсіз?'),
        V('Do you always pack an umbrella just in case?', 'Вы всегда берёте зонт на всякий случай?', 'Сақтық үшін әрдайым қолшатыр аласыз ба?'),
        V('Do you prefer staying inside on rainy days?', 'Вы предпочитаете оставаться дома в дождливые дни?', 'Жаңбырлы күндері үйде қалғанды ұнатасыз ба?'),
        V('What is the best weather for you, in your opinion?', 'Какая погода для вас лучшая, по-вашему?', 'Сіздің ойыңызша, сіз үшін ең жақсы ауа райы қандай?'),
        V('Do you change your plans because of bad weather?', 'Вы меняете планы из-за плохой погоды?', 'Жаман ауа райы себебінен жоспарларыңызды өзгертесіз бе?'),
        V('Have you ever been caught outside without an umbrella in the rain?', 'Вы когда-нибудь оказывались на улице без зонта под дождём?', 'Жаңбырда қолшатырсыз сыртта қалдыңыз ба?'),
        V('Do you own different coats for different weather?', 'У вас есть разные пальто для разной погоды?', 'Әртүрлі ауа райына арналған әртүрлі пальтоларыңыз бар ма?'),
        V('Does sudden weather change surprise you often?', 'Внезапная смена погоды часто удивляет вас?', 'Кенеттен ауа райының өзгеруі сізді жиі таңғалдыра ма?'),
        V('Do you feel more energetic on sunny days?', 'Вы чувствуете себя энергичнее в солнечные дни?', 'Күнді күндері өзіңізді энергиялырақ сезінесіз бе?'),
        V('What do you wear when the weather is just right?', 'Что вы носите, когда погода в самый раз?', 'Ауа райы дәл келгенде не киесіз?'),
        V('Do you trust weather forecasts to be accurate?', 'Вы доверяете точности прогнозов погоды?', 'Ауа райы болжамдарының дәлдігіне сенесіз бе?'),
        V('Would you cancel outdoor plans because of light rain?', 'Вы бы отменили планы на улице из-за лёгкого дождя?', 'Жеңіл жаңбыр себебінен сыртқы жоспарларды тоқтатар ма едіңіз?'),
        V('Do you enjoy the smell of rain?', 'Вам нравится запах дождя?', 'Жаңбыр иісін ұнатасыз ба?'),
        V('How does bad weather affect your mood?', 'Как плохая погода влияет на ваше настроение?', 'Жаман ауа райы көңіл-күйіңізге қалай әсер етеді?'),
    ],
];

$lessons[] = ['level' => 'beginner', 'topic' => 'At the Pharmacy', 'background_key' => 'calm',
    'warmup' => V("Let's talk about the pharmacy. What do you usually buy at a pharmacy?", 'Давайте поговорим об аптеке. Что вы обычно покупаете в аптеке?', 'Дәріхана туралы сөйлесейік. Дәріханада әдетте не сатып аласыз?'),
    'vocab' => [V('pharmacist', 'фармацевт', 'фармацевт'), V('prescription', 'рецепт', 'рецепт'), V('tablet', 'таблетка', 'таблетка'), V('syrup', 'сироп', 'сироп'), V('painkiller', 'обезболивающее', 'ауырсынуды басатын дәрі'), V('bandage', 'бинт', 'бинт'), V('vitamin', 'витамин', 'дәрумен'), V('dosage', 'дозировка', 'мөлшер'), V('counter', 'прилавок', 'сөре (сатушы алдындағы)'), V('receipt', 'чек', 'чек')],
    'questions' => [
        V('What do you usually buy at a pharmacy?', 'Что вы обычно покупаете в аптеке?', 'Дәріханада әдетте не сатып аласыз?'),
        V('Do you take vitamins regularly?', 'Вы регулярно принимаете витамины?', 'Тұрақты түрде дәрумен ішесіз бе?'),
        V('Do you always ask the pharmacist for advice?', 'Вы всегда спрашиваете совета у фармацевта?', 'Әрдайым фармацевттен кеңес сұрайсыз ба?'),
        V('Have you ever taken the wrong dosage of medicine?', 'Вы когда-нибудь принимали неправильную дозировку лекарства?', 'Дәріні қате мөлшерде іштіңіз бе?'),
        V('Do you keep a first aid kit with bandages at home?', 'У вас дома есть аптечка с бинтами?', 'Үйде бинты бар дәрі-дәрмек қобдишасы бар ма?'),
        V('Is the pharmacy near your home easy to reach?', 'До аптеки рядом с вашим домом легко добраться?', 'Үйіңізге жақын дәріханаға жету оңай ма?'),
        V('Do you prefer tablets or syrup when you are sick?', 'Вы предпочитаете таблетки или сироп, когда болеете?', 'Ауырғанда таблетканы ұнатасыз ба, әлде сиропты ма?'),
        V('Have you ever needed a painkiller urgently?', 'Вам когда-нибудь срочно требовалось обезболивающее?', 'Ауырсынуды басатын дәрі шұғыл керек болды ма?'),
        V('Do you keep the receipt after buying medicine?', 'Вы храните чек после покупки лекарства?', 'Дәрі сатып алғаннан кейін чекті сақтайсыз ба?'),
        V('Do you need a prescription for most medicines in your country?', 'Вам нужен рецепт для большинства лекарств в вашей стране?', 'Еліңізде көптеген дәрілер үшін рецепт керек пе?'),
        V('Is the pharmacy usually crowded when you go?', 'Аптека обычно многолюдна, когда вы туда идёте?', 'Барғанда дәріхана әдетте адам көп бола ма?'),
        V('Do you buy vitamins for the whole family?', 'Вы покупаете витамины для всей семьи?', 'Бүкіл отбасы үшін дәрумен сатып аласыз ба?'),
        V('Have you ever gone to the pharmacy late at night?', 'Вы когда-нибудь ходили в аптеку поздно ночью?', 'Кеш түнде дәріханаға бардыңыз ба?'),
        V('Do you trust the pharmacist\'s recommendation over the internet\'s?', 'Вы доверяете рекомендации фармацевта больше, чем интернету?', 'Фармацевттің ұсынысына интернеттен гөрі көбірек сенесіз бе?'),
        V('What is the last thing you bought at a pharmacy?', 'Что последнее вы покупали в аптеке?', 'Дәріханадан соңғы сатып алған затыңыз не болды?'),
    ],
];

$lessons[] = ['level' => 'beginner', 'topic' => 'Talking About Sleep', 'background_key' => 'calm',
    'warmup' => V("Let's talk about sleep. What time do you go to bed, and do you sleep well?", 'Давайте поговорим о сне. Во сколько вы ложитесь спать и хорошо ли вы спите?', 'Ұйқы туралы сөйлесейік. Сағат нешеде ұйықтайсыз және жақсы ұйықтайсыз ба?'),
    'vocab' => [V('bedtime', 'время сна', 'ұйықтау уақыты'), V('nap', 'дневной сон', 'күндізгі ұйқы'), V('dream', 'сон (сновидение)', 'түс'), V('alarm', 'будильник', 'оятқыш'), V('snore', 'храпеть', 'қорылдау'), V('tired', 'уставший', 'шаршаған'), V('well-rested', 'отдохнувший', 'жақсы демалған'), V('pillow', 'подушка', 'жастық'), V('blanket', 'одеяло', 'көрпе'), V('wake up', 'просыпаться', 'ояну')],
    'questions' => [
        V('What time do you usually go to bed?', 'Во сколько вы обычно ложитесь спать?', 'Әдетте сағат нешеде ұйықтайсыз?'),
        V('Do you take naps during the day?', 'Вы спите днём?', 'Күндіз ұйықтайсыз ба?'),
        V('Do you remember your dreams often?', 'Вы часто помните свои сны?', 'Түстеріңізді жиі есте сақтайсыз ба?'),
        V('Does someone in your family snore?', 'Кто-то в вашей семье храпит?', 'Отбасыңызда біреу қорылдай ма?'),
        V('Do you wake up feeling well-rested most days?', 'Вы просыпаетесь отдохнувшим большинство дней?', 'Көп күндері жақсы демалған болып оясыз ба?'),
        V('Do you use an alarm to wake up?', 'Вы используете будильник, чтобы проснуться?', 'Ояну үшін оятқышты пайдаланасыз ба?'),
        V('Do you have a favorite pillow or blanket?', 'У вас есть любимая подушка или одеяло?', 'Сүйікті жастығыңыз немесе көрпеңіз бар ма?'),
        V('How many hours do you usually sleep?', 'Сколько часов вы обычно спите?', 'Әдетте қанша сағат ұйықтайсыз?'),
        V('Do you snooze your alarm in the morning?', 'Вы откладываете будильник по утрам?', 'Таңертең оятқышты кейінге қалдырасыз ба?'),
        V('Is it easy for you to fall asleep at night?', 'Вам легко засыпать ночью?', 'Түнде ұйықтап кету сізге оңай ма?'),
        V('Do you sleep better at home or when traveling?', 'Вы лучше спите дома или в путешествиях?', 'Үйде жақсырақ ұйықтайсыз ба, әлде саяхатта ма?'),
        V('Do you use your phone right before sleeping?', 'Вы пользуетесь телефоном прямо перед сном?', 'Ұйықтар алдында телефонды пайдаланасыз ба?'),
        V('Have you ever had a strange or funny dream?', 'У вас когда-нибудь был странный или смешной сон?', 'Сізде ерекше немесе күлкілі түс болды ма?'),
        V('Do you sleep with the lights on or off?', 'Вы спите со светом включённым или выключенным?', 'Жарық қосулы ұйықтайсыз ба, әлде өшірулі ме?'),
        V('What helps you fall asleep faster?', 'Что помогает вам быстрее засыпать?', 'Тезірек ұйықтап кетуге не көмектеседі?'),
    ],
];

$lessons[] = ['level' => 'beginner', 'topic' => 'My Weekly Schedule', 'background_key' => 'calm',
    'warmup' => V("Let's talk about your week. What does your week usually look like?", 'Давайте поговорим о вашей неделе. Как обычно проходит ваша неделя?', 'Апта туралы сөйлесейік. Апта сайын не істейсіз?'),
    'vocab' => [V('weekday', 'будний день', 'жұмыс күні'), V('weekend', 'выходные', 'демалыс күндері'), V('appointment', 'встреча', 'кездесу'), V('class', 'занятие', 'сабақ'), V('work shift', 'рабочая смена', 'жұмыс ауысымы'), V('free evening', 'свободный вечер', 'бос кеш'), V('busy morning', 'занятое утро', 'бос емес таң'), V('routine', 'распорядок', 'тәртіп'), V('calendar', 'календарь', 'күнтізбе'), V('plan', 'план', 'жоспар')],
    'questions' => [
        V('Is your week usually busy or relaxed?', 'Ваша неделя обычно напряжённая или спокойная?', 'Аптаңыз әдетте қарбалас па, әлде сабырлы ма?'),
        V('Do you use a calendar to plan your week?', 'Вы используете календарь, чтобы планировать неделю?', 'Аптаны жоспарлау үшін күнтізбені пайдаланасыз ба?'),
        V('Which day of the week is busiest for you?', 'Какой день недели самый занятой для вас?', 'Аптаның қай күні сіз үшін ең бос емес?'),
        V('Do you have any free evenings this week?', 'У вас есть свободные вечера на этой неделе?', 'Осы аптада бос кештеріңіз бар ма?'),
        V('Does your schedule change often, or stay the same?', 'Ваше расписание часто меняется, или остаётся неизменным?', 'Кестеңіз жиі өзгере ме, әлде бірдей қала ма?'),
        V('What appointment do you have coming up this week?', 'Какая у вас предстоящая встреча на этой неделе?', 'Осы аптада қандай кездесуіңіз бар?'),
        V('Do you look forward to weekends all week?', 'Вы ждёте выходных всю неделю?', 'Апта бойы демалыс күндерін күтесіз бе?'),
        V('Is Monday harder for you than other weekdays?', 'Понедельник труднее для вас, чем другие будние дни?', 'Дүйсенбі сіз үшін басқа жұмыс күндерінен қиынырақ па?'),
        V('Do you write your weekly plan on paper or on your phone?', 'Вы записываете недельный план на бумаге или в телефоне?', 'Апталық жоспарыңызды қағазға жазасыз ба, әлде телефонға ма?'),
        V('How many hours of the week do you spend working?', 'Сколько часов в неделю вы тратите на работу?', 'Аптасына жұмысқа қанша сағат бөлесіз?'),
        V('Do you keep your weekends completely free of work?', 'Вы полностью освобождаете выходные от работы?', 'Демалыс күндерін жұмыстан толығымен бос ұстайсыз ба?'),
        V('What is the most important appointment on your calendar this month?', 'Какая самая важная встреча в вашем календаре в этом месяце?', 'Осы айда күнтізбеңіздегі ең маңызды кездесу қандай?'),
        V('Does a busy morning affect the rest of your day?', 'Занятое утро влияет на остальную часть дня?', 'Бос емес таң күніңіздің қалған бөлігіне әсер ете ме?'),
        V('Do you prefer a fixed weekly routine or a flexible one?', 'Вы предпочитаете фиксированный недельный распорядок или гибкий?', 'Тұрақты апталық тәртіпті ұнатасыз ба, әлде икемдіні ме?'),
        V('What would you change about your current weekly schedule?', 'Что бы вы изменили в своём текущем недельном расписании?', 'Қазіргі апталық кестеңізде нені өзгертер едіңіз?'),
    ],
];

$lessons[] = ['level' => 'beginner', 'topic' => 'Simple Requests', 'background_key' => 'calm',
    'warmup' => V("Let's talk about making requests. How do you politely ask for something?", 'Давайте поговорим о просьбах. Как вы вежливо просите о чём-то?', 'Өтініштер туралы сөйлесейік. Бір нәрсені сыпайы түрде қалай сұрайсыз?'),
    'vocab' => [V('can I have', 'можно мне', 'маған бере аласыз ба'), V('could you help', 'не могли бы вы помочь', 'көмектесе аласыз ба'), V('please pass', 'передайте, пожалуйста', 'өтінемін беріңіз'), V('may I', 'можно ли мне', 'маған бола ма'), V('would you mind', 'вы не против', 'қарсы емессіз бе'), V('excuse me', 'извините', 'кешіріңіз'), V('I need', 'мне нужно', 'маған керек'), V('I want', 'я хочу', 'мен қалаймын'), V('thank you', 'спасибо', 'рахмет'), V('no problem', 'без проблем', 'мәселе жоқ')],
    'questions' => [
        V('Do you find it easy to ask for help?', 'Вам легко просить о помощи?', 'Көмек сұрау сізге оңай ма?'),
        V('What polite phrase do you use most often?', 'Какую вежливую фразу вы используете чаще всего?', 'Ең жиі қандай сыпайы сөз тіркесін қолданасыз?'),
        V('Do you say "thank you" to strangers who help you?', 'Вы говорите "спасибо" незнакомцам, которые вам помогают?', 'Сізге көмектескен бейтаныс адамдарға "рахмет" айтасыз ба?'),
        V('Is it hard for you to say no to a request?', 'Вам трудно отказывать в просьбе?', 'Өтінішке жоқ деп айту сізге қиын ма?'),
        V('How do you ask a stranger for directions?', 'Как вы спрашиваете дорогу у незнакомца?', 'Бейтаныс адамнан жолды қалай сұрайсыз?'),
        V('Do you prefer direct requests or polite hints?', 'Вы предпочитаете прямые просьбы или вежливые намёки?', 'Тікелей өтінішті ұнатасыз ба, әлде сыпайы ишараны ма?'),
        V('Do you say "excuse me" before interrupting someone?', 'Вы говорите "извините" перед тем, как перебить кого-то?', 'Біреуді бөлмес бұрын "кешіріңіз" дейсіз бе?'),
        V('Have you ever felt awkward making a request?', 'Вы когда-нибудь чувствовали себя неловко, обращаясь с просьбой?', 'Өтінішпен келгенде ыңғайсыз сезіндіңіз бе?'),
        V('Do you ask "would you mind" when making a bigger request?', 'Вы говорите "вы не против" при более крупной просьбе?', 'Үлкенірек өтініш жасағанда "қарсы емессіз бе" дейсіз бе?'),
        V('Do you usually get what you ask for?', 'Вы обычно получаете то, что просите?', 'Әдетте сұрағаныңызды аласыз ба?'),
        V('How do you respond when someone says "no problem"?', 'Как вы отвечаете, когда кто-то говорит "без проблем"?', 'Біреу "мәселе жоқ" дегенде қалай жауап бересіз?'),
        V('Do you make requests differently with friends versus strangers?', 'Вы по-другому обращаетесь с просьбами к друзьям и незнакомцам?', 'Достарыңызға және бейтаныс адамдарға өтінішті басқаша жасайсыз ба?'),
        V('What was the last favor you asked someone for?', 'О какой услуге вы недавно просили кого-то?', 'Соңғы рет кімнен қандай жақсылық сұрадыңыз?'),
        V('Do you feel comfortable saying "I need" instead of "I want"?', 'Вам комфортно говорить "мне нужно" вместо "я хочу"?', '"Мен қалаймын" дегеннің орнына "маған керек" дегенге ыңғайлысыз ба?'),
        V('Is politeness in requests more important in some cultures than others?', 'Вежливость в просьбах важнее в одних культурах, чем в других?', 'Кейбір мәдениеттерде өтініштегі сыпайылық басқаларынан маңыздырақ па?'),
    ],
];

$lessons[] = ['level' => 'beginner', 'topic' => 'Talking About Speed', 'background_key' => 'energetic',
    'warmup' => V("Let's talk about speed. Are you usually fast or slow when doing things?", 'Давайте поговорим о скорости. Вы обычно быстрый или медленный в делах?', 'Жылдамдық туралы сөйлесейік. Істерде әдетте жылдамсыз ба, әлде баяусыз ба?'),
    'vocab' => [V('fast', 'быстрый', 'жылдам'), V('slow', 'медленный', 'баяу'), V('quick', 'быстрый (шустрый)', 'тез'), V('hurry', 'спешить', 'асығу'), V('rush', 'спешка', 'асығыс'), V('delay', 'задержка', 'кідіріс'), V('on time', 'вовремя', 'уақытында'), V('late', 'поздно', 'кеш'), V('early', 'рано', 'ерте'), V('wait', 'ждать', 'күту')],
    'questions' => [
        V('Are you usually early, on time, or late?', 'Вы обычно приходите рано, вовремя или поздно?', 'Әдетте ерте, уақытында немесе кеш келесіз бе?'),
        V('Do you hurry in the morning?', 'Вы спешите по утрам?', 'Таңертең асығасыз ба?'),
        V('Do you get frustrated when you have to wait?', 'Вы расстраиваетесь, когда приходится ждать?', 'Күтуге тура келгенде ренжисіз бе?'),
        V('Do you eat quickly or slowly?', 'Вы едите быстро или медленно?', 'Тез жейсіз бе, әлде баяу ма?'),
        V('Have you ever been delayed by traffic?', 'Вы когда-нибудь опаздывали из-за пробок?', 'Көлік кептелісінен кешіктіңіз бе?'),
        V('Do you prefer working fast or taking your time?', 'Вы предпочитаете работать быстро или не спешить?', 'Жылдам жұмыс істегенді ұнатасыз ба, әлде асықпағанды ма?'),
        V('Does being late make you anxious?', 'Опоздание вызывает у вас тревогу?', 'Кешігу сізді мазасыздандыра ма?'),
        V('Do you walk fast or slowly in general?', 'Вы вообще ходите быстро или медленно?', 'Жалпы жылдам жүресіз бе, әлде баяу ма?'),
        V('How do you feel when someone makes you wait a long time?', 'Что вы чувствуете, когда кто-то заставляет вас долго ждать?', 'Біреу сізді ұзақ күттіргенде не сезінесіз?'),
        V('Do you plan extra time in case of delays?', 'Вы планируете дополнительное время на случай задержек?', 'Кідірістер жағдайында қосымша уақыт жоспарлайсыз ба?'),
        V('Is it easy for you to relax when you are in a rush?', 'Вам легко расслабиться, когда вы спешите?', 'Асыққанда демалу сізге оңай ма?'),
        V('Do quick decisions or slow decisions work better for you?', 'Быстрые решения или медленные подходят вам лучше?', 'Тез шешімдер ме, әлде баяу шешімдер ме сізге жақсырақ жұмыс істейді?'),
        V('Do you get annoyed by slow walkers on the street?', 'Вас раздражают медленно идущие люди на улице?', 'Көшедегі баяу жүретін адамдар сізді тітіркендіре ме?'),
        V('Have you ever rushed and made a mistake because of it?', 'Вы когда-нибудь спешили и из-за этого допустили ошибку?', 'Асығып, сол себепті қате жіберген кезіңіз болды ма?'),
        V('Would you rather live in a fast-paced city or a slow-paced town?', 'Вы бы предпочли жить в быстром городе или в спокойном городке?', 'Қарқынды қалада тұрғанды қалайсыз ба, әлде баяу қалашықта ма?'),
    ],
];

$lessons[] = ['level' => 'beginner', 'topic' => 'My Favorite Drink', 'background_key' => 'playful',
    'warmup' => V("Let's talk about drinks. What is your favorite drink, hot or cold?", 'Давайте поговорим о напитках. Какой ваш любимый напиток, горячий или холодный?', 'Сусындар туралы сөйлесейік. Сүйікті сусыныңыз қандай, ыстық па, әлде суық па?'),
    'vocab' => [V('juice', 'сок', 'шырын'), V('soda', 'газировка', 'газдалған су'), V('milk', 'молоко', 'сүт'), V('smoothie', 'смузи', 'смузи'), V('cold drink', 'холодный напиток', 'суық сусын'), V('hot drink', 'горячий напиток', 'ыстық сусын'), V('refreshing', 'освежающий', 'сергітетін'), V('sweet', 'сладкий', 'тәтті'), V('bitter', 'горький', 'ащы'), V('straw', 'трубочка', 'түтікше')],
    'questions' => [
        V('What is your favorite drink?', 'Какой ваш любимый напиток?', 'Сүйікті сусыныңыз қандай?'),
        V('Do you prefer hot drinks or cold drinks?', 'Вы предпочитаете горячие напитки или холодные?', 'Ыстық сусынды ұнатасыз ба, әлде суықты ма?'),
        V('Do you like sweet drinks or bitter ones like coffee?', 'Вам нравятся сладкие напитки или горькие, как кофе?', 'Тәтті сусындарды ұнатасыз ба, әлде кофе сияқты ащыны ма?'),
        V('Do you drink milk every day?', 'Вы пьёте молоко каждый день?', 'Күн сайын сүт ішесіз бе?'),
        V('Have you ever made your own smoothie?', 'Вы когда-нибудь делали свой собственный смузи?', 'Өзіңіздің смузиіңізді жасадыңыз ба?'),
        V('Do you use a straw when drinking?', 'Вы используете трубочку, когда пьёте?', 'Ішкенде түтікшені пайдаланасыз ба?'),
        V('Do you drink soda often, or try to avoid it?', 'Вы часто пьёте газировку, или стараетесь её избегать?', 'Газдалған суды жиі ішесіз бе, әлде одан аулақ болуға тырысасыз ба?'),
        V('What drink helps you wake up in the morning?', 'Какой напиток помогает вам проснуться утром?', 'Таңертең оянуға қандай сусын көмектеседі?'),
        V('Do you order the same drink every time you go out?', 'Вы заказываете один и тот же напиток каждый раз, когда выходите?', 'Сыртқа шыққан сайын бір сусынды тапсырыс бересіз бе?'),
        V('Have you ever tried a drink you really disliked?', 'Вы когда-нибудь пробовали напиток, который вам совсем не понравился?', 'Мүлдем ұнатпаған сусынды сынап көрдіңіз бе?'),
        V('Do you drink more water or other drinks during the day?', 'Вы пьёте больше воды или других напитков в течение дня?', 'Күн бойы суды көбірек ішесіз бе, әлде басқа сусындарды ма?'),
        V('What is a refreshing drink you enjoy in summer?', 'Какой освежающий напиток вам нравится летом?', 'Жазда ұнататын сергітетін сусыныңыз қандай?'),
        V('Do you add sugar to your drinks?', 'Вы добавляете сахар в напитки?', 'Сусындарыңызға қант қосасыз ба?'),
        V('What drink reminds you of your childhood?', 'Какой напиток напоминает вам о детстве?', 'Қай сусын сізге балалық шағыңызды еске түсіреді?'),
        V('Would you rather give up coffee or give up soda?', 'Вы бы предпочли отказаться от кофе или от газировки?', 'Кофеден бас тартар ма едіңіз, әлде газдалған судан ба?'),
    ],
];

$lessons[] = ['level' => 'beginner', 'topic' => 'Directions Inside a Building', 'background_key' => 'professional',
    'warmup' => V("Let's talk about finding your way inside a building. Do you find it easy to find a room in a big building?", 'Давайте поговорим о том, как найти дорогу внутри здания. Вам легко найти комнату в большом здании?', 'Ғимарат ішінде жол табу туралы сөйлесейік. Үлкен ғимаратта бөлмені табу сізге оңай ма?'),
    'vocab' => [V('upstairs', 'наверх', 'жоғарғы қабатқа'), V('downstairs', 'вниз', 'төменгі қабатқа'), V('elevator', 'лифт', 'лифт'), V('stairs', 'лестница', 'баспалдақ'), V('hallway', 'коридор', 'дәліз'), V('floor', 'этаж', 'қабат'), V('room number', 'номер комнаты', 'бөлме нөмірі'), V('exit', 'выход', 'шығу'), V('entrance', 'вход', 'кіру'), V('lobby', 'вестибюль', 'вестибюль')],
    'questions' => [
        V('Do you prefer taking the stairs or the elevator?', 'Вы предпочитаете лестницу или лифт?', 'Баспалдақты ұнатасыз ба, әлде лифтіні ме?'),
        V('Have you ever gotten lost inside a big building?', 'Вы когда-нибудь терялись внутри большого здания?', 'Үлкен ғимарат ішінде адасып қалдыңыз ба?'),
        V('Do you remember room numbers easily?', 'Вы легко запоминаете номера комнат?', 'Бөлме нөмірлерін оңай есте сақтайсыз ба?'),
        V('Is it easy to find the exit in buildings you visit?', 'Легко ли найти выход в зданиях, которые вы посещаете?', 'Баратын ғимараттарда шығуды табу оңай ма?'),
        V('What floor do you live or work on?', 'На каком этаже вы живёте или работаете?', 'Қай қабатта тұрасыз немесе жұмыс істейсіз?'),
        V('Do you like waiting in a lobby, or does it bother you?', 'Вам нравится ждать в вестибюле, или это вас раздражает?', 'Вестибюльде күтуді ұнатасыз ба, әлде мазалай ма?'),
        V('Do you take the stairs for exercise sometimes?', 'Вы иногда поднимаетесь по лестнице ради упражнения?', 'Кейде жаттығу үшін баспалдақпен жүресіз бе?'),
        V('Have you ever been stuck in an elevator?', 'Вы когда-нибудь застревали в лифте?', 'Лифтіде қалып қойдыңыз ба?'),
        V('Do long hallways make you feel uncomfortable?', 'Длинные коридоры заставляют вас чувствовать себя неуютно?', 'Ұзын дәліздер сізді ыңғайсыз сезіндіре ме?'),
        V('Do you ask for directions at a building\'s entrance?', 'Вы спрашиваете дорогу у входа в здание?', 'Ғимараттың кірер жерінде жол сұрайсыз ба?'),
        V('Is the lobby in your workplace or school a nice place to wait?', 'Вестибюль на вашей работе или в школе — приятное место для ожидания?', 'Жұмысыңыздағы немесе мектебіңіздегі вестибюль күтуге жағымды орын ба?'),
        V('Do buildings in your city usually have clear signs?', 'В зданиях вашего города обычно есть чёткие указатели?', 'Қалаңыздағы ғимараттарда әдетте анық белгілер бар ма?'),
        V('Would you rather work on a high floor or a low floor?', 'Вы бы предпочли работать на высоком этаже или на низком?', 'Жоғары қабатта жұмыс істегенді қалайсыз ба, әлде төменгіде ме?'),
        V('Do you use the stairs during a fire drill or emergency?', 'Вы используете лестницу во время пожарной тревоги или экстренной ситуации?', 'Өрт дабылы немесе төтенше жағдай кезінде баспалдақты пайдаланасыз ба?'),
        V('Do elevators make you feel nervous?', 'Лифты вызывают у вас тревогу?', 'Лифттер сізді толқыта ма?'),
    ],
];

$lessons[] = ['level' => 'beginner', 'topic' => 'Clothes and Shoe Sizes', 'background_key' => 'playful',
    'warmup' => V("Let's talk about sizes. Do you know your clothing and shoe size?", 'Давайте поговорим о размерах. Вы знаете свой размер одежды и обуви?', 'Өлшемдер туралы сөйлесейік. Киім мен аяқ киім өлшеміңізді білесіз бе?'),
    'vocab' => [V('small size', 'маленький размер', 'кіші өлшем'), V('medium', 'средний', 'орташа'), V('large', 'большой', 'үлкен'), V('fits well', 'хорошо сидит', 'жақсы келеді'), V('too big', 'слишком большой', 'тым үлкен'), V('too tight', 'слишком тесный', 'тым тар'), V('try again', 'попробовать снова', 'қайта байқау'), V('exchange', 'обменять', 'айырбастау'), V('size chart', 'таблица размеров', 'өлшем кестесі'), V('comfortable fit', 'удобная посадка', 'ыңғайлы отыру')],
    'questions' => [
        V('Do you know your clothing size?', 'Вы знаете свой размер одежды?', 'Киім өлшеміңізді білесіз бе?'),
        V('Have you ever bought shoes that were too tight?', 'Вы когда-нибудь покупали слишком тесную обувь?', 'Тым тар аяқ киім сатып алдыңыз ба?'),
        V('Do you check the size chart before buying clothes online?', 'Вы проверяете таблицу размеров перед покупкой одежды онлайн?', 'Онлайн киім сатып алмас бұрын өлшем кестесін тексересіз бе?'),
        V('Have you ever had to exchange clothes because they didn\'t fit?', 'Вам приходилось менять одежду, потому что она не подошла?', 'Сәйкес келмегендіктен киімді айырбастауға тура келді ме?'),
        V('Do you prefer a loose fit or a tight fit?', 'Вы предпочитаете свободную посадку или облегающую?', 'Бос отыруды ұнатасыз ба, әлде тарды ма?'),
        V('Is it easy for you to find clothes that fit well?', 'Вам легко находить одежду, которая хорошо сидит?', 'Жақсы келетін киімді табу сізге оңай ма?'),
        V('Do you always try clothes on before buying them?', 'Вы всегда примеряете одежду перед покупкой?', 'Сатып алмас бұрын киімді әрдайым өлшеп көресіз бе?'),
        V('Has your clothing size changed over the years?', 'Ваш размер одежды менялся с годами?', 'Киім өлшеміңіз жылдар бойы өзгерді ме?'),
        V('Do you feel confident buying clothes without trying them on?', 'Вам комфортно покупать одежду, не примеряя её?', 'Өлшеп көрмей киім сатып алу сізге сенімді ме?'),
        V('Is medium size usually the right fit for you?', 'Средний размер обычно вам подходит?', 'Орташа өлшем әдетте сізге дәл келе ме?'),
        V('Do shoe sizes vary a lot between different brands for you?', 'Размеры обуви сильно различаются между брендами для вас?', 'Аяқ киім өлшемдері әртүрлі брендтер арасында сіз үшін көп өзгере ме?'),
        V('Have you ever returned clothes because the size was wrong?', 'Вы когда-нибудь возвращали одежду из-за неправильного размера?', 'Өлшем қате болғандықтан киімді қайтардыңыз ба?'),
        V('Do you buy a bigger size on purpose sometimes?', 'Вы иногда специально покупаете размер побольше?', 'Кейде әдейі үлкенірек өлшем сатып аласыз ба?'),
        V('Do you feel comfortable asking a shop assistant for a different size?', 'Вам комфортно просить продавца принести другой размер?', 'Сатушыдан басқа өлшем сұрау сізге ыңғайлы ма?'),
        V('What is more important to you: size accuracy or style?', 'Что для вас важнее: точность размера или стиль?', 'Сіз үшін не маңыздырақ: өлшем дәлдігі ме, әлде стиль ме?'),
    ],
];

$lessons[] = ['level' => 'beginner', 'topic' => 'My Favorite Game', 'background_key' => 'playful',
    'warmup' => V("Let's talk about games. What is your favorite game to play?", 'Давайте поговорим об играх. В какую игру вам нравится играть больше всего?', 'Ойындар туралы сөйлесейік. Ойнауды ең көп ұнататын ойыныңыз қайсы?'),
    'vocab' => [V('board game', 'настольная игра', 'үстел ойыны'), V('card game', 'карточная игра', 'карта ойыны'), V('video game', 'видеоигра', 'бейне ойын'), V('puzzle', 'головоломка', 'басқатырғыш'), V('winner', 'победитель', 'жеңімпаз'), V('loser', 'проигравший', 'ұтылған'), V('rules', 'правила', 'ережелер'), V('turn', 'ход (в игре)', 'кезек'), V('dice', 'кости (игральные)', 'сүйек (ойын)'), V('score', 'счёт', 'есеп')],
    'questions' => [
        V('What is your favorite game?', 'Какая ваша любимая игра?', 'Сүйікті ойыныңыз қайсы?'),
        V('Do you prefer board games or video games?', 'Вы предпочитаете настольные игры или видеоигры?', 'Үстел ойындарын ұнатасыз ба, әлде бейне ойындарды ма?'),
        V('Do you like being the winner, or do you not mind losing?', 'Вам нравится быть победителем, или вы не против проигрыша?', 'Жеңімпаз болғанды ұнатасыз ба, әлде ұтылуға қарсы емессіз бе?'),
        V('Do you always follow the rules when playing games?', 'Вы всегда следуете правилам, когда играете?', 'Ойнағанда әрдайым ережелерді сақтайсыз ба?'),
        V('Do you enjoy solving puzzles?', 'Вам нравится решать головоломки?', 'Басқатырғыштарды шешуді ұнатасыз ба?'),
        V('Who do you usually play games with?', 'С кем вы обычно играете?', 'Әдетте кіммен ойнайсыз?'),
        V('Do you get competitive when playing games?', 'Вы становитесь азартным, когда играете?', 'Ойнағанда бәсекелестікке беріле кетесіз бе?'),
        V('What was the last game you played?', 'В какую игру вы играли последний раз?', 'Соңғы рет қандай ойын ойнадыңыз?'),
        V('Do you own any card games or board games at home?', 'У вас дома есть карточные или настольные игры?', 'Үйде карта немесе үстел ойындарыңыз бар ма?'),
        V('Have you ever taught someone the rules of your favorite game?', 'Вы когда-нибудь учили кого-то правилам своей любимой игры?', 'Сүйікті ойыныңыздың ережелерін біреуге үйреттіңіз бе?'),
        V('Do you enjoy games of luck, like dice games, or games of skill?', 'Вам нравятся игры на удачу, как игры в кости, или игры на мастерство?', 'Сүйек ойындары сияқты сәттілік ойындарын ұнатасыз ба, әлде шеберлік ойындарын ба?'),
        V('Is it hard for you to accept losing a game?', 'Вам трудно смириться с проигрышем в игре?', 'Ойында ұтылуды қабылдау сізге қиын ба?'),
        V('Do you play games to relax or to compete?', 'Вы играете, чтобы расслабиться или чтобы соревноваться?', 'Демалу үшін ойнайсыз ба, әлде бәсекелесу үшін бе?'),
        V('What game from your childhood do you still enjoy?', 'В какую игру из детства вы всё ещё играете с удовольствием?', 'Балалық шақтан қандай ойынды әлі ұнатасыз?'),
        V('Would you like to learn a new game this year?', 'Хотели бы вы выучить новую игру в этом году?', 'Осы жылы жаңа ойынды үйренгіңіз келе ме?'),
    ],
];

$lessons[] = ['level' => 'beginner', 'topic' => 'Talking About Habits', 'background_key' => 'minimal-dark',
    'warmup' => V("Let's talk about habits. What things do you do every day without thinking?", 'Давайте поговорим о привычках. Что вы делаете каждый день, не задумываясь?', 'Әдеттер туралы сөйлесейік. Күн сайын ойланбай не істейсіз?'),
    'vocab' => [V('every day', 'каждый день', 'күн сайын'), V('sometimes', 'иногда', 'кейде'), V('never', 'никогда', 'ешқашан'), V('always', 'всегда', 'әрдайым'), V('usually', 'обычно', 'әдетте'), V('rarely', 'редко', 'сирек'), V('often', 'часто', 'жиі'), V('routine', 'рутина', 'тәртіп'), V('habit', 'привычка', 'әдет'), V('change', 'менять', 'өзгерту')],
    'questions' => [
        V('What do you do every day without thinking about it?', 'Что вы делаете каждый день, не задумываясь?', 'Күн сайын ойланбай не істейсіз?'),
        V('Do you usually wake up at the same time?', 'Вы обычно просыпаетесь в одно и то же время?', 'Әдетте бір уақытта оясыз ба?'),
        V('What habit would you like to change?', 'Какую привычку вы хотели бы изменить?', 'Қандай әдетті өзгерткіңіз келеді?'),
        V('Do you rarely or often eat fast food?', 'Вы редко или часто едите фастфуд?', 'Фастфудты сирек жейсіз бе, әлде жиі ме?'),
        V('Is there a habit you always do before bed?', 'Есть ли привычка, которую вы всегда делаете перед сном?', 'Ұйықтар алдында әрдайым жасайтын әдетіңіз бар ма?'),
        V('Have you ever successfully changed a bad habit?', 'Вы когда-нибудь успешно меняли плохую привычку?', 'Жаман әдетті сәтті өзгерттіңіз бе?'),
        V('What is a good habit you never break?', 'Какая хорошая привычка, которую вы никогда не нарушаете?', 'Ешқашан бұзбайтын жақсы әдетіңіз қандай?'),
        V('Do you sometimes forget your own daily routine?', 'Вы иногда забываете свой собственный распорядок дня?', 'Кейде өзіңіздің күн тәртібіңізді ұмытасыз ба?'),
        V('Do you have a habit that other people find strange?', 'У вас есть привычка, которую другие находят странной?', 'Басқа адамдар оғаш деп санайтын әдетіңіз бар ма?'),
        V('How long does it usually take you to build a new habit?', 'Сколько времени обычно уходит у вас на выработку новой привычки?', 'Жаңа әдетті қалыптастыруға әдетте қанша уақыт кетеді?'),
        V('Do you check your phone as soon as you wake up?', 'Вы проверяете телефон сразу после пробуждения?', 'Оянғаннан кейін бірден телефонды тексересіз бе?'),
        V('What habit does your family always tease you about?', 'Над какой привычкой всегда подшучивает ваша семья?', 'Отбасыңыз қандай әдетіңіз үшін әрдайым қалжыңдайды?'),
        V('Do you always eat at the same time every day?', 'Вы всегда едите в одно и то же время каждый день?', 'Күн сайын бір уақытта тамақтанасыз ба?'),
        V('Is it hard for you to break an old habit?', 'Вам трудно избавиться от старой привычки?', 'Ескі әдеттен арылу сізге қиын ба?'),
        V('What new habit would improve your life the most?', 'Какая новая привычка больше всего улучшила бы вашу жизнь?', 'Қандай жаңа әдет өміріңізді ең көп жақсартар еді?'),
    ],
];

$lessons[] = ['level' => 'beginner', 'topic' => "My Family's Weekend", 'background_key' => 'warm',
    'warmup' => V("Let's talk about weekends with family. What does your family usually do on weekends?", 'Давайте поговорим о выходных с семьёй. Что ваша семья обычно делает по выходным?', 'Отбасымен демалыс күндері туралы сөйлесейік. Отбасыңыз демалыс күндері әдетте не істейді?'),
    'vocab' => [V('Saturday', 'суббота', 'сенбі'), V('Sunday', 'воскресенье', 'жексенбі'), V('relax', 'расслабляться', 'демалу'), V('chores', 'домашние дела', 'үй жұмыстары'), V('visit family', 'навещать семью', 'отбасыны аралау'), V('watch TV', 'смотреть телевизор', 'теледидар көру'), V('go out', 'выходить куда-то', 'сыртқа шығу'), V('sleep in', 'спать подольше', 'ұзақ ұйықтау'), V('cook together', 'готовить вместе', 'бірге тамақ пісіру'), V('enjoy time', 'наслаждаться временем', 'уақытты рахаттану')],
    'questions' => [
        V('What does your family usually do on weekends?', 'Что ваша семья обычно делает по выходным?', 'Отбасыңыз демалыс күндері әдетте не істейді?'),
        V('Do you visit relatives on weekends?', 'Вы навещаете родственников по выходным?', 'Демалыс күндері туыстарыңызды аралайсыз ба?'),
        V('Do you cook together as a family?', 'Вы готовите вместе всей семьёй?', 'Отбасыңызбен бірге тамақ пісіресіз бе?'),
        V('Does your family do chores together on weekends?', 'Ваша семья делает домашние дела вместе по выходным?', 'Отбасыңыз демалыс күндері үй жұмысын бірге істей ме?'),
        V('Do you sleep in on Saturday or Sunday?', 'Вы спите подольше в субботу или воскресенье?', 'Сенбіде немесе жексенбіде ұзақ ұйықтайсыз ба?'),
        V('What is your favorite thing to do with family on weekends?', 'Что вам больше всего нравится делать с семьёй на выходных?', 'Демалыс күндері отбасыңызбен істегенді ең көп ұнататын нәрсеңіз не?'),
        V('Is Saturday or Sunday more relaxing for your family?', 'Суббота или воскресенье более расслабляющий день для вашей семьи?', 'Отбасыңыз үшін сенбі мен жексенбінің қайсысы демалдырақ?'),
        V('Do you watch TV together as a family on weekends?', 'Вы смотрите телевизор вместе всей семьёй на выходных?', 'Демалыс күндері отбасыңызбен бірге теледидар көресіз бе?'),
        V('Does your family plan weekend activities in advance?', 'Ваша семья планирует занятия на выходные заранее?', 'Отбасыңыз демалыс күндерінің іс-шараларын алдын ала жоспарлайды ма?'),
        V('Do you feel like weekends go by too fast?', 'Вам кажется, что выходные проходят слишком быстро?', 'Демалыс күндері тым тез өтеді деп сезінесіз бе?'),
        V('Does your whole family go out together sometimes?', 'Ваша семья иногда выходит куда-то вместе всем составом?', 'Отбасыңыз кейде бәрі бірге сыртқа шыға ма?'),
        V('Do children in your family have chores on weekends?', 'У детей в вашей семье есть дела по дому на выходных?', 'Отбасыңыздағы балалардың демалыс күндерінде үй жұмысы бар ма?'),
        V('What is the busiest part of your family\'s weekend?', 'Какая часть выходных у вашей семьи самая напряжённая?', 'Отбасыңыздың демалыс күндерінің ең қарбалас бөлігі қандай?'),
        V('Do you prefer active weekends or quiet weekends with family?', 'Вы предпочитаете активные выходные или тихие с семьёй?', 'Белсенді демалыс күндерін ұнатасыз ба, әлде отбасымен тыныш демалысты ма?'),
        V('What weekend tradition does your family have?', 'Какая традиция выходного дня есть у вашей семьи?', 'Отбасыңызда қандай демалыс күні дәстүрі бар?'),
    ],
];

require __DIR__ . '/seed_lessons_batch6_part2.php';
