<?php
declare(strict_types=1);
// Included from seed_lessons_batch6.php — shares its scope ($lessons, function V()).

// ========================= ELEMENTARY (batch 6) — 15 questions per topic =========================

$lessons[] = ['level' => 'elementary', 'topic' => 'Working From Home', 'background_key' => 'professional',
    'warmup' => V("Let's talk about working from home. What are the best and worst parts of it?", 'Давайте поговорим о работе из дома. Какие в этом лучшие и худшие стороны?', 'Үйден жұмыс істеу туралы сөйлесейік. Оның ең жақсы және ең жаман жақтары қандай?'),
    'vocab' => [V('home office', 'домашний офис', 'үй кеңсесі'), V('video call', 'видеозвонок', 'бейнеқоңырау'), V('distraction', 'отвлечение', 'алаңдату'), V('productivity', 'продуктивность', 'өнімділік'), V('deadline', 'дедлайн', 'мерзім'), V('quiet space', 'тихое место', 'тыныш орын'), V('work clothes', 'рабочая одежда', 'жұмыс киімі'), V('commute', 'дорога на работу', 'жұмысқа қатынау'), V('flexible hours', 'гибкий график', 'икемді сағаттар'), V('coworker', 'коллега', 'әріптес')],
    'questions' => [
        V('Do you work from home, or would you like to?', 'Вы работаете из дома, или хотели бы?', 'Үйден жұмыс істейсіз бе, әлде қалар ма едіңіз?'),
        V('What distracts you most when working from home?', 'Что больше всего отвлекает вас при работе из дома?', 'Үйден жұмыс істегенде сізді ең көп не алаңдатады?'),
        V('Do you miss commuting, or are you glad to avoid it?', 'Вы скучаете по дороге на работу, или рады её избегать?', 'Жұмысқа қатынауды сағынасыз ба, әлде одан құтылғаныңызға қуанасыз ба?'),
        V('Do you wear work clothes even when at home?', 'Вы носите рабочую одежду, даже находясь дома?', 'Үйде болсаңыз да жұмыс киімін киесіз бе?'),
        V('Is it easy for you to stay productive at home?', 'Вам легко оставаться продуктивным дома?', 'Үйде өнімді болу сізге оңай ма?'),
        V('Do you have a quiet space to work in?', 'У вас есть тихое место для работы?', 'Жұмыс істеуге тыныш орныңыз бар ма?'),
        V('Do you miss seeing coworkers in person?', 'Вы скучаете по личному общению с коллегами?', 'Әріптестеріңізбен жеке кездесуді сағынасыз ба?'),
        V('Do flexible hours help or hurt your productivity?', 'Гибкий график помогает или мешает вашей продуктивности?', 'Икемді сағаттар өнімділігіңізге көмектесе ме, әлде зиян тигізе ме?'),
        V('How do you separate work time from personal time at home?', 'Как вы разделяете рабочее и личное время дома?', 'Үйде жұмыс уақыты мен жеке уақытты қалай бөлесіз?'),
        V('Do video calls tire you more than in-person meetings?', 'Видеозвонки утомляют вас больше, чем личные встречи?', 'Бейнеқоңыраулар сізді жеке кездесулерден гөрі көбірек шаршата ма?'),
        V('Would you rather work fully remote or fully in an office?', 'Вы бы предпочли работать полностью удалённо или полностью в офисе?', 'Толықтай қашықтан жұмыс істегенді қалайсыз ба, әлде толықтай кеңседе ме?'),
        V('Do you take breaks during your workday at home?', 'Вы делаете перерывы в течение рабочего дня дома?', 'Үйде жұмыс күні ішінде үзіліс жасайсыз ба?'),
        V('Does working from home make it harder to meet deadlines?', 'Работа из дома усложняет соблюдение сроков?', 'Үйден жұмыс істеу мерзімдерді сақтауды қиындата ма?'),
        V('Do family members interrupt you when you work at home?', 'Члены семьи вас отвлекают, когда вы работаете дома?', 'Үйде жұмыс істегенде отбасы мүшелері сізді бөле ме?'),
        V('What would make working from home better for you?', 'Что улучшило бы для вас работу из дома?', 'Сіз үшін үйден жұмыс істеуді не жақсартар еді?'),
    ],
];

$lessons[] = ['level' => 'elementary', 'topic' => 'Learning to Cook a New Cuisine', 'background_key' => 'playful',
    'warmup' => V("Let's talk about cooking new cuisines. Have you ever tried cooking food from another country?", 'Давайте поговорим о готовке новой кухни. Вы когда-нибудь пробовали готовить еду из другой страны?', 'Жаңа ас мәзірін пісіру туралы сөйлесейік. Басқа елдің тағамын пісіріп көрдіңіз бе?'),
    'vocab' => [V('cuisine', 'кухня (кулинарная)', 'ас мәзірі'), V('spice', 'специя', 'дәмдеуіш'), V('recipe', 'рецепт', 'рецепт'), V('authentic', 'аутентичный', 'түпнұсқалық'), V('ingredient', 'ингредиент', 'құрам бөлігі'), V('technique', 'техника', 'әдіс'), V('flavor', 'вкус (аромат)', 'дәм'), V('substitute', 'замена', 'алмастыру'), V('experiment', 'эксперимент', 'тәжірибе'), V('mistake', 'ошибка', 'қате')],
    'questions' => [
        V('Have you ever cooked food from another country?', 'Вы когда-нибудь готовили еду из другой страны?', 'Басқа елдің тағамын пісірдіңіз бе?'),
        V('What cuisine would you like to learn to cook?', 'Какую кухню вы хотели бы научиться готовить?', 'Қандай ас мәзірін пісіруді үйренгіңіз келеді?'),
        V('Do you find it hard to get authentic ingredients where you live?', 'Вам трудно найти аутентичные ингредиенты там, где вы живёте?', 'Тұратын жеріңізде түпнұсқалық құрам бөліктерін табу қиын ба?'),
        V('Have you ever substituted an ingredient you couldn\'t find?', 'Вы когда-нибудь заменяли ингредиент, который не смогли найти?', 'Таба алмаған құрам бөлігін алмастырдыңыз ба?'),
        V('Do you follow recipes exactly, or experiment freely?', 'Вы точно следуете рецептам, или свободно экспериментируете?', 'Рецепттерді дәл орындайсыз ба, әлде еркін тәжірибе жасайсыз ба?'),
        V('What spices do you enjoy using the most?', 'Какие специи вам нравится использовать больше всего?', 'Қандай дәмдеуіштерді ең көп қолданғанды ұнатасыз?'),
        V('Have you ever made a big cooking mistake?', 'Вы когда-нибудь допускали большую ошибку в готовке?', 'Пісіруде үлкен қате жіберген кезіңіз болды ма?'),
        V('Do you watch cooking videos to learn new techniques?', 'Вы смотрите видео о готовке, чтобы изучить новые техники?', 'Жаңа әдістерді үйрену үшін пісіру бейнелерін көресіз бе?'),
        V('Is spicy food something you enjoy or avoid?', 'Острая еда — это то, что вам нравится или чего вы избегаете?', 'Ащы тағам сізге ұнай ма, әлде аулақ боласыз ба?'),
        V('Would you take a cooking class for a new cuisine?', 'Вы бы записались на кулинарные курсы по новой кухне?', 'Жаңа ас мәзірі бойынша аспаздық курсқа жазылар ма едіңіз?'),
        V('Do you cook a new dish to impress guests?', 'Вы готовите новое блюдо, чтобы впечатлить гостей?', 'Қонақтарды таңғалдыру үшін жаңа тағам пісіресіз бе?'),
        V('What is the most difficult dish you have tried to make?', 'Какое самое сложное блюдо вы пытались приготовить?', 'Жасауға тырысқан ең қиын тағамыңыз қандай болды?'),
        V('Do you prefer to cook alone or with someone else?', 'Вы предпочитаете готовить одни или с кем-то?', 'Жалғыз пісіргенді ұнатасыз ба, әлде біреумен бе?'),
        V('Have you ever recreated a dish you tried at a restaurant?', 'Вы когда-нибудь воссоздавали блюдо, которое пробовали в ресторане?', 'Мейрамханада татып көрген тағамды қайта жасадыңыз ба?'),
        V('What is your favorite flavor combination?', 'Какое ваше любимое сочетание вкусов?', 'Сүйікті дәм үйлесіміңіз қандай?'),
    ],
];

$lessons[] = ['level' => 'elementary', 'topic' => 'Choosing a University Major', 'background_key' => 'professional',
    'warmup' => V("Let's talk about choosing what to study. How do people usually decide on a university major?", 'Давайте поговорим о выборе специальности. Как люди обычно решают, что изучать в университете?', 'Не оқу керектігін таңдау туралы сөйлесейік. Адамдар университет мамандығын әдетте қалай шешеді?'),
    'vocab' => [V('major', 'специальность', 'мамандық'), V('career path', 'карьерный путь', 'мансап жолы'), V('interest', 'интерес', 'қызығушылық'), V('scholarship', 'стипендия', 'степендия'), V('tuition', 'плата за обучение', 'оқу ақысы'), V('internship', 'стажировка', 'тәжірибеден өту'), V('job market', 'рынок труда', 'еңбек нарығы'), V('passion', 'страсть (увлечение)', 'құштарлық'), V('advisor', 'куратор', 'кеңесші'), V('switch', 'сменить', 'ауыстыру')],
    'questions' => [
        V('How did you choose what to study, or what would you choose?', 'Как вы выбрали, что изучать, или что бы вы выбрали?', 'Не оқу керектігін қалай таңдадыңыз немесе не таңдар едіңіз?'),
        V('Should students follow their passion or the job market?', 'Должны ли студенты следовать своей страсти или рынку труда?', 'Студенттер өз құштарлығына жүруі керек пе, әлде еңбек нарығына ма?'),
        V('Have you ever considered switching your field of study?', 'Вы когда-нибудь думали сменить специальность?', 'Мамандығыңызды ауыстыруды ойладыңыз ба?'),
        V('Do you think tuition costs affect what people choose to study?', 'Как вы думаете, стоимость обучения влияет на выбор специальности?', 'Оқу ақысы адамдардың таңдауына әсер етеді деп ойлайсыз ба?'),
        V('Have you ever done an internship? What was it like?', 'Вы когда-нибудь проходили стажировку? Какой она была?', 'Тәжірибеден өттіңіз бе? Ол қалай болды?'),
        V('Do you think a scholarship should determine where someone studies?', 'Как вы думаете, стипендия должна определять, где кто-то учится?', 'Стипендия адамның қайда оқитынын анықтауы керек пе деп ойлайсыз ба?'),
        V('Is it common to change majors in your country?', 'Часто ли меняют специальность в вашей стране?', 'Еліңізде мамандықты ауыстыру жиі кездесе ме?'),
        V('Do you think young people know enough to choose a career at 18?', 'Как вы думаете, молодые люди знают достаточно, чтобы выбрать карьеру в 18 лет?', 'Жастар 18 жаста мансап таңдау үшін жеткілікті біледі деп ойлайсыз ба?'),
        V('Did an advisor or mentor help you choose your path?', 'Куратор или наставник помогли вам выбрать путь?', 'Кеңесші немесе тәлімгер жолыңызды таңдауға көмектесті ме?'),
        V('Would you study something completely different if you could start over?', 'Вы бы изучали что-то совсем другое, если бы могли начать заново?', 'Қайтадан бастасаңыз, мүлдем басқа нәрсе оқыр ма едіңіз?'),
        V('Do you think practical experience matters more than a degree?', 'Как вы думаете, практический опыт важнее диплома?', 'Практикалық тәжірибе дипломнан маңыздырақ деп ойлайсыз ба?'),
        V('What subject were you most passionate about in school?', 'Каким предметом вы больше всего увлекались в школе?', 'Мектепте қай пәнге ең көп құштар болдыңыз?'),
        V('Is job security or personal interest more important when choosing a major?', 'Что важнее при выборе специальности: гарантия работы или личный интерес?', 'Мамандық таңдағанда жұмыс кепілдігі ме, әлде жеке қызығушылық па маңыздырақ?'),
        V('Have you ever regretted a choice about your education?', 'Вы когда-нибудь жалели о выборе, связанном с образованием?', 'Біліміңізге қатысты таңдауыңызға өкіндіңіз бе?'),
        V('What advice would you give someone choosing a major today?', 'Какой совет вы бы дали тому, кто выбирает специальность сегодня?', 'Бүгін мамандық таңдап жатқан адамға қандай кеңес берер едіңіз?'),
    ],
];

$lessons[] = ['level' => 'elementary', 'topic' => 'Dealing with Traffic Jams', 'background_key' => 'night-city',
    'warmup' => V("Let's talk about traffic. How do you deal with getting stuck in traffic?", 'Давайте поговорим о пробках. Как вы справляетесь, когда застреваете в пробке?', 'Көлік кептелісі туралы сөйлесейік. Кептелісте қалғанда қалай төтеп бересіз?'),
    'vocab' => [V('traffic jam', 'пробка', 'көлік кептелісі'), V('rush hour', 'час пик', 'жүгіру сағаты'), V('honk', 'сигналить', 'дабыл беру'), V('lane', 'полоса', 'жолақ'), V('detour', 'объезд', 'айналма жол'), V('roadwork', 'дорожные работы', 'жол жұмысы'), V('patience', 'терпение', 'шыдамдылық'), V('podcast', 'подкаст', 'подкаст'), V('gridlock', 'затор (полный)', 'толық кептеліс'), V('commute time', 'время в пути на работу', 'жұмысқа бару уақыты')],
    'questions' => [
        V('Do you often get stuck in traffic?', 'Вы часто застреваете в пробках?', 'Жиі көлік кептелісінде қаласыз ба?'),
        V('How do you stay patient during a traffic jam?', 'Как вы сохраняете терпение в пробке?', 'Кептеліс кезінде шыдамдылықты қалай сақтайсыз?'),
        V('Do you listen to music or podcasts while stuck in traffic?', 'Вы слушаете музыку или подкасты, застряв в пробке?', 'Кептелісте музыка немесе подкаст тыңдайсыз ба?'),
        V('Does traffic make you feel stressed or angry?', 'Пробки заставляют вас чувствовать стресс или злость?', 'Кептеліс сізді күйзеліске немесе ашуға түсіре ме?'),
        V('Do you try to leave earlier to avoid rush hour?', 'Вы стараетесь выезжать раньше, чтобы избежать часа пик?', 'Жүгіру сағатынан аулақ болу үшін ертерек шығуға тырысасыз ба?'),
        V('Have you ever taken a detour to avoid traffic?', 'Вы когда-нибудь ехали в объезд, чтобы избежать пробки?', 'Кептелістен аулақ болу үшін айналма жолмен жүрдіңіз бе?'),
        V('Is traffic getting worse or better in your city?', 'Пробки в вашем городе становятся хуже или лучше?', 'Қалаңызда кептеліс нашарлап жатыр ма, әлде жақсарып жатыр ма?'),
        V('Do you honk when someone drives too slowly?', 'Вы сигналите, когда кто-то едет слишком медленно?', 'Біреу тым баяу жүргенде дабыл бересіз бе?'),
        V('How long is your average commute?', 'Сколько времени в среднем занимает ваша дорога на работу?', 'Жұмысқа орташа қанша уақыт барасыз?'),
        V('Do roadwork projects often slow down your route?', 'Дорожные работы часто замедляют ваш маршрут?', 'Жол жұмыстары маршрутыңызды жиі баяулата ма?'),
        V('Would you take public transport to avoid traffic?', 'Вы бы воспользовались общественным транспортом, чтобы избежать пробок?', 'Кептелістен аулақ болу үшін қоғамдық көлікті пайдаланар ма едіңіз?'),
        V('Do you change lanes often when stuck in traffic?', 'Вы часто меняете полосы, застряв в пробке?', 'Кептелісте қалғанда жолақты жиі ауыстырасыз ба?'),
        V('What do you think is the main cause of traffic jams in your city?', 'Что, по-вашему, главная причина пробок в вашем городе?', 'Сіздің ойыңызша, қалаңыздағы кептелістердің басты себебі не?'),
        V('Have you ever been extremely late because of traffic?', 'Вы когда-нибудь сильно опаздывали из-за пробок?', 'Кептеліс себебінен қатты кешіктіңіз бе?'),
        V('Would working from home reduce traffic problems in general?', 'Работа из дома в целом снизила бы проблемы с пробками?', 'Үйден жұмыс істеу жалпы кептеліс мәселелерін азайтар ма еді?'),
    ],
];

$lessons[] = ['level' => 'elementary', 'topic' => 'Planning a Birthday Surprise', 'background_key' => 'playful',
    'warmup' => V("Let's talk about surprise parties. Have you ever planned a surprise for someone?", 'Давайте поговорим о сюрприз-вечеринках. Вы когда-нибудь устраивали сюрприз для кого-то?', 'Тосынсый кештер туралы сөйлесейік. Біреуге тосынсый жасадыңыз ба?'),
    'vocab' => [V('surprise', 'сюрприз', 'тосынсый'), V('secret', 'секрет', 'құпия'), V('invite', 'приглашать', 'шақыру'), V('decorations', 'украшения', 'безендіру'), V('hide', 'прятать', 'жасыру'), V('reveal', 'раскрыть', 'ашу'), V('guest list', 'список гостей', 'қонақтар тізімі'), V('celebration', 'празднование', 'мереке тойлау'), V('plan ahead', 'планировать заранее', 'алдын ала жоспарлау'), V('cake', 'торт', 'торт')],
    'questions' => [
        V('Have you ever planned a surprise party for someone?', 'Вы когда-нибудь устраивали сюрприз-вечеринку для кого-то?', 'Біреуге тосынсый кеш ұйымдастырдыңыз ба?'),
        V('Is it hard for you to keep a secret?', 'Вам трудно хранить секрет?', 'Құпияны сақтау сізге қиын ба?'),
        V('Have you ever been surprised for your own birthday?', 'Вас когда-нибудь удивляли на собственный день рождения?', 'Сізді өз туған күніңізде таңғалдырды ма?'),
        V('Do you enjoy planning events, or find it stressful?', 'Вам нравится планировать мероприятия, или это стрессово?', 'Іс-шараларды жоспарлауды ұнатасыз ба, әлде күйзелісті ме?'),
        V('How far in advance do you plan a birthday surprise?', 'За сколько времени вы планируете сюрприз на день рождения?', 'Туған күн тосынсыйын қаншалықты ерте жоспарлайсыз?'),
        V('Do you invite a big group or a small group for surprises?', 'Вы приглашаете большую группу или маленькую на сюрпризы?', 'Тосынсыйға үлкен топты шақырасыз ба, әлде шағын топты ма?'),
        V('Have you ever accidentally revealed a surprise?', 'Вы когда-нибудь случайно раскрывали сюрприз?', 'Кездейсоқ тосынсыйды ашып қойдыңыз ба?'),
        V('What is the best surprise you have ever received?', 'Какой лучший сюрприз вы когда-либо получали?', 'Алған ең жақсы тосынсыйыңыз қандай болды?'),
        V('Do you prefer surprising someone or being surprised?', 'Вам больше нравится удивлять кого-то или удивляться самому?', 'Біреуді таңғалдырғанды ұнатасыз ба, әлде өзіңіз таңғалғанды ма?'),
        V('Do you decorate for surprise parties?', 'Вы украшаете помещение для сюрприз-вечеринок?', 'Тосынсый кештер үшін безендіресіз бе?'),
        V('Would you help a friend plan a big surprise?', 'Вы бы помогли другу спланировать большой сюрприз?', 'Досыңызға үлкен тосынсый жоспарлауға көмектесер ме едіңіз?'),
        V('Do you order a cake, or bake one for surprises?', 'Вы заказываете торт или печёте его для сюрпризов?', 'Тосынсыйлар үшін торт тапсырыс бересіз бе, әлде пісіресіз бе?'),
        V('Have you ever hidden somewhere to surprise someone?', 'Вы когда-нибудь прятались где-то, чтобы удивить кого-то?', 'Біреуді таңғалдыру үшін бір жерге жасырындыңыз ба?'),
        V('Do you think surprise parties are usually a good idea?', 'Как вы думаете, сюрприз-вечеринки обычно хорошая идея?', 'Тосынсый кештер әдетте жақсы идея деп ойлайсыз ба?'),
        V('What would be your dream surprise from a friend?', 'Какой был бы ваш идеальный сюрприз от друга?', 'Достан алатын арман тосынсыйыңыз қандай болар еді?'),
    ],
];

$lessons[] = ['level' => 'elementary', 'topic' => 'Adjusting to a New Job', 'background_key' => 'professional',
    'warmup' => V("Let's talk about starting a new job. What is it like adjusting to a new workplace?", 'Давайте поговорим о начале новой работы. Каково это — привыкать к новому рабочему месту?', 'Жаңа жұмысты бастау туралы сөйлесейік. Жаңа жұмыс орнына бейімделу қандай?'),
    'vocab' => [V('onboarding', 'адаптация (в компании)', 'бейімдеу'), V('training', 'обучение', 'оқыту'), V('coworker', 'коллега', 'әріптес'), V('manager', 'менеджер', 'менеджер'), V('learning curve', 'кривая обучения', 'оқу қисығы'), V('nervous', 'нервный', 'толқыған'), V('office culture', 'корпоративная культура', 'кеңсе мәдениеті'), V('probation period', 'испытательный срок', 'сынақ мерзімі'), V('responsibility', 'ответственность', 'жауапкершілік'), V('confidence', 'уверенность', 'сенімділік')],
    'questions' => [
        V('Have you ever started a new job? How did you feel?', 'Вы когда-нибудь начинали новую работу? Что вы чувствовали?', 'Жаңа жұмысты бастадыңыз ба? Не сезіндіңіз?'),
        V('What is the hardest part of adjusting to a new workplace?', 'Какая самая трудная часть привыкания к новому рабочему месту?', 'Жаңа жұмыс орнына бейімделудің ең қиын бөлігі қандай?'),
        V('Do you make friends quickly with new coworkers?', 'Вы быстро заводите друзей среди новых коллег?', 'Жаңа әріптестермен тез дос боласыз ба?'),
        V('Were you nervous on your first day at a job?', 'Вы нервничали в первый день на работе?', 'Жұмыстың бірінші күнінде толқыдыңыз ба?'),
        V('How long does it usually take you to feel comfortable in a new role?', 'Сколько времени вам обычно нужно, чтобы освоиться на новой должности?', 'Жаңа лауазымда өзіңізді ыңғайлы сезінуге әдетте қанша уақыт кетеді?'),
        V('Do you ask a lot of questions when you are new?', 'Вы задаёте много вопросов, когда вы новичок?', 'Жаңа болғанда көп сұрақ қоясыз ба?'),
        V('Have you ever had a difficult manager when starting a job?', 'У вас когда-нибудь был трудный руководитель при начале работы?', 'Жұмысты бастағанда қиын менеджеріңіз болды ма?'),
        V('Do you think a probation period is fair?', 'Как вы думаете, испытательный срок справедлив?', 'Сынақ мерзімі әділ деп ойлайсыз ба?'),
        V('What helps you feel confident in a new environment?', 'Что помогает вам чувствовать уверенность в новой обстановке?', 'Жаңа ортада сенімді сезінуге не көмектеседі?'),
        V('Do you prefer formal or relaxed office culture?', 'Вы предпочитаете формальную или непринуждённую корпоративную культуру?', 'Ресми кеңсе мәдениетін ұнатасыз ба, әлде еркінді ме?'),
        V('Have you ever felt overwhelmed by new responsibilities?', 'Вы когда-нибудь чувствовали себя перегруженным новыми обязанностями?', 'Жаңа жауапкершіліктерден шаршадыңыз ба?'),
        V('Do you take notes during training at a new job?', 'Вы делаете заметки во время обучения на новой работе?', 'Жаңа жұмыста оқыту кезінде жазбалар жасайсыз ба?'),
        V('What would make onboarding easier for new employees?', 'Что бы облегчило адаптацию для новых сотрудников?', 'Жаңа қызметкерлер үшін бейімдеуді не жеңілдетер еді?'),
        V('Do you compare a new job to your previous one?', 'Вы сравниваете новую работу с предыдущей?', 'Жаңа жұмысты бұрынғысымен салыстырасыз ба?'),
        V('What advice would you give someone starting their first job?', 'Какой совет вы бы дали тому, кто начинает свою первую работу?', 'Алғашқы жұмысын бастап жатқан адамға қандай кеңес берер едіңіз?'),
    ],
];

$lessons[] = ['level' => 'elementary', 'topic' => 'Home Internet and Wifi Issues', 'background_key' => 'night-city',
    'warmup' => V("Let's talk about internet problems. What do you do when your wifi stops working?", 'Давайте поговорим о проблемах с интернетом. Что вы делаете, когда вайфай перестаёт работать?', 'Интернет мәселелері туралы сөйлесейік. Wifi істемей қалғанда не істейсіз?'),
    'vocab' => [V('wifi', 'вайфай', 'wifi'), V('router', 'роутер', 'роутер'), V('connection', 'подключение', 'байланыс'), V('slow internet', 'медленный интернет', 'баяу интернет'), V('provider', 'провайдер', 'провайдер'), V('reset', 'перезагрузка', 'қайта іске қосу'), V('buffering', 'буферизация', 'буферлеу'), V('signal', 'сигнал', 'сигнал'), V('password', 'пароль', 'құпия сөз'), V('technician', 'техник', 'техник')],
    'questions' => [
        V('What do you do when your wifi stops working?', 'Что вы делаете, когда вайфай перестаёт работать?', 'Wifi істемей қалғанда не істейсіз?'),
        V('How often does your internet connection have problems?', 'Как часто у вашего интернет-соединения бывают проблемы?', 'Интернет байланысыңызда қаншалықты жиі мәселе туындайды?'),
        V('Do you know how to reset your router?', 'Вы знаете, как перезагрузить роутер?', 'Роутерді қайта іске қосуды білесіз бе?'),
        V('Does slow internet frustrate you a lot?', 'Медленный интернет вас сильно раздражает?', 'Баяу интернет сізді қатты ренжіте ме?'),
        V('Have you ever called a technician to fix your internet?', 'Вы когда-нибудь вызывали техника, чтобы починить интернет?', 'Интернетті жөндеу үшін техник шақырдыңыз ба?'),
        V('Do you share your wifi password with guests?', 'Вы делитесь паролем от вайфая с гостями?', 'Wifi құпия сөзін қонақтармен бөлісесіз бе?'),
        V('Is your internet provider reliable?', 'Ваш интернет-провайдер надёжен?', 'Интернет провайдеріңіз сенімді ме?'),
        V('Does video buffering annoy you while watching something?', 'Буферизация видео раздражает вас во время просмотра?', 'Бір нәрсе көргенде бейне буферлеуі сізді тітіркендіре ме?'),
        V('Do you get a weak signal in some parts of your home?', 'В некоторых частях дома у вас слабый сигнал?', 'Үйдің кейбір жерлерінде сигналыңыз әлсіз бе?'),
        V('Could you work or study without a stable internet connection?', 'Могли бы вы работать или учиться без стабильного интернета?', 'Тұрақты интернетсіз жұмыс істей немесе оқи алар ма едіңіз?'),
        V('Have you ever changed your internet provider?', 'Вы когда-нибудь меняли интернет-провайдера?', 'Интернет провайдеріңізді ауыстырдыңыз ба?'),
        V('Do you check your internet speed sometimes?', 'Вы иногда проверяете скорость интернета?', 'Кейде интернет жылдамдығын тексересіз бе?'),
        V('How many devices are usually connected to your wifi?', 'Сколько устройств обычно подключено к вашему вайфаю?', 'Wifi-ге әдетте қанша құрылғы қосылған?'),
        V('Do internet problems usually happen at the worst times?', 'Проблемы с интернетом обычно случаются в самый неподходящий момент?', 'Интернет мәселелері әдетте ең қолайсыз кезде туындай ма?'),
        V('Would you pay more for faster and more reliable internet?', 'Вы бы заплатили больше за более быстрый и надёжный интернет?', 'Жылдамырақ және сенімдірек интернет үшін көбірек төлер ме едіңіз?'),
    ],
];

$lessons[] = ['level' => 'elementary', 'topic' => 'Visiting the Dentist', 'background_key' => 'calm',
    'warmup' => V("Let's talk about the dentist. How do you feel about going to the dentist?", 'Давайте поговорим о стоматологе. Что вы чувствуете, когда идёте к стоматологу?', 'Стоматолог туралы сөйлесейік. Стоматологқа барғанда не сезінесіз?'),
    'vocab' => [V('dentist', 'стоматолог', 'стоматолог'), V('checkup', 'осмотр', 'тексеру'), V('cavity', 'кариес', 'кариес'), V('toothache', 'зубная боль', 'тіс ауруы'), V('filling', 'пломба', 'пломба'), V('brush teeth', 'чистить зубы', 'тіс тазалау'), V('floss', 'зубная нить', 'тіс жіп'), V('nervous', 'нервный', 'толқыған'), V('appointment', 'запись', 'жазылу'), V('clean teeth', 'чистые зубы', 'таза тістер')],
    'questions' => [
        V('How do you feel about going to the dentist?', 'Что вы чувствуете, когда идёте к стоматологу?', 'Стоматологқа барғанда не сезінесіз?'),
        V('How often do you go for a dental checkup?', 'Как часто вы проходите стоматологический осмотр?', 'Стоматологиялық тексеруден қаншалықты жиі өтесіз?'),
        V('Do you brush your teeth twice a day?', 'Вы чистите зубы дважды в день?', 'Тісіңізді күніне екі рет тазалайсыз ба?'),
        V('Do you use dental floss regularly?', 'Вы регулярно пользуетесь зубной нитью?', 'Тіс жіпін тұрақты пайдаланасыз ба?'),
        V('Have you ever had a cavity?', 'У вас когда-нибудь был кариес?', 'Сізде кариес болды ма?'),
        V('Do you get nervous before a dental appointment?', 'Вы нервничаете перед приёмом у стоматолога?', 'Стоматологқа жазылу алдында толқисыз ба?'),
        V('Have you ever had a toothache? How did you deal with it?', 'У вас когда-нибудь болел зуб? Как вы справились?', 'Тісіңіз ауырды ма? Онымен қалай күрестіңіз?'),
        V('Do you avoid sugary foods to protect your teeth?', 'Вы избегаете сладкого, чтобы защитить зубы?', 'Тістеріңізді қорғау үшін тәттіден аулақ боласыз ба?'),
        V('Do you feel confident smiling and showing your teeth?', 'Вам комфортно улыбаться и показывать зубы?', 'Күлкіде тісіңізді көрсету сізге сенімді ме?'),
        V('Have you ever had a filling done?', 'Вам когда-нибудь ставили пломбу?', 'Сізге пломба қойылды ма?'),
        V('Do you think regular checkups are important?', 'Как вы думаете, регулярные осмотры важны?', 'Тұрақты тексерулер маңызды деп ойлайсыз ба?'),
        V('Did you like going to the dentist as a child?', 'Вам нравилось ходить к стоматологу в детстве?', 'Балалық шағыңызда стоматологқа баруды ұнатасыз ба?'),
        V('Do you feel relieved after leaving the dentist\'s office?', 'Вы испытываете облегчение после ухода из кабинета стоматолога?', 'Стоматологтың кабинетінен шыққаннан кейін жеңілдейсіз бе?'),
        V('What could make dental visits less stressful for people?', 'Что могло бы сделать визиты к стоматологу менее стрессовыми для людей?', 'Стоматологқа баруды адамдар үшін не аз күйзелісті ете алады?'),
        V('Do you take good care of your teeth overall?', 'Вы в целом хорошо заботитесь о зубах?', 'Жалпы алғанда тістеріңізге жақсы қамқорлық жасайсыз ба?'),
    ],
];

$lessons[] = ['level' => 'elementary', 'topic' => 'Borrowing and Lending Money', 'background_key' => 'professional',
    'warmup' => V("Let's talk about lending money. How do you feel about borrowing or lending money to friends?", 'Давайте поговорим об одалживании денег. Что вы думаете об одалживании денег друзьям?', 'Ақша қарызға беру туралы сөйлесейік. Достарыңызға ақша қарызға беру немесе алу туралы не ойлайсыз?'),
    'vocab' => [V('borrow', 'занимать', 'қарызға алу'), V('lend', 'одалживать', 'қарызға беру'), V('debt', 'долг', 'борыш'), V('repay', 'возвращать', 'қайтару'), V('IOU', 'долговая расписка', 'қарыз қағазы'), V('trust', 'доверие', 'сенім'), V('awkward', 'неловкий', 'ыңғайсыз'), V('emergency', 'чрезвычайная ситуация', 'төтенше жағдай'), V('interest-free', 'беспроцентный', 'пайызсыз'), V('agreement', 'соглашение', 'келісім')],
    'questions' => [
        V('Have you ever borrowed money from a friend or family member?', 'Вы когда-нибудь занимали деньги у друга или родственника?', 'Досыңыздан немесе туысыңыздан ақша қарызға алдыңыз ба?'),
        V('Do you feel comfortable lending money to friends?', 'Вам комфортно одалживать деньги друзьям?', 'Достарыңызға ақша қарызға беру сізге ыңғайлы ма?'),
        V('Have you ever felt awkward asking for money back?', 'Вы когда-нибудь чувствовали неловкость, прося вернуть деньги?', 'Ақшаны қайтаруды сұрағанда ыңғайсыз сезіндіңіз бе?'),
        V('Do you write down agreements when lending money?', 'Вы записываете соглашения при одалживании денег?', 'Ақша қарызға бергенде келісімдерді жазып қоясыз ба?'),
        V('Would you lend money to someone in an emergency?', 'Вы бы одолжили деньги кому-то в чрезвычайной ситуации?', 'Төтенше жағдайда біреуге ақша қарызға берер ма едіңіз?'),
        V('Do you always repay money you borrow quickly?', 'Вы всегда быстро возвращаете занятые деньги?', 'Қарызға алған ақшаны әрдайым тез қайтарасыз ба?'),
        V('Has lending money ever hurt a friendship?', 'Одалживание денег когда-нибудь портило дружбу?', 'Ақша қарызға беру достықты бұзған кезі болды ма?'),
        V('Do you set limits on how much you would lend?', 'Вы устанавливаете лимиты на сумму, которую готовы одолжить?', 'Қарызға беретін соманың шегін белгілейсіз бе?'),
        V('Do you prefer borrowing from a bank or from family?', 'Вы предпочитаете занимать у банка или у семьи?', 'Банктен қарызға алғанды ұнатасыз ба, әлде отбасыдан ма?'),
        V('Is it rude to remind someone about money they owe you?', 'Грубо ли напоминать кому-то о долге?', 'Біреуге борышы туралы еске салу дөрекілік пе?'),
        V('Do you keep track of small amounts you lend to friends?', 'Вы отслеживаете небольшие суммы, которые одалживаете друзьям?', 'Достарыңызға берген шағын соманы қадағалайсыз ба?'),
        V('Would you rather give money as a gift instead of lending it?', 'Вы бы предпочли подарить деньги вместо того, чтобы одолжить их?', 'Ақшаны қарызға берудің орнына сыйлауды қалар ма едіңіз?'),
        V('How do you politely say no to a request for money?', 'Как вы вежливо отказываете в просьбе о деньгах?', 'Ақша сұрауға сыпайы түрде қалай жоқ дейсіз?'),
        V('Do you think lending money interest-free to friends is normal?', 'Как вы думаете, одалживать деньги друзьям без процентов — это нормально?', 'Достарыңызға пайызсыз ақша қарызға беру қалыпты деп ойлайсыз ба?'),
        V('What would you do if a friend never repaid a loan?', 'Что бы вы сделали, если бы друг никогда не вернул долг?', 'Дос борышын ешқашан қайтармаса, не істер едіңіз?'),
    ],
];

$lessons[] = ['level' => 'elementary', 'topic' => 'Packing for a Business Trip', 'background_key' => 'professional',
    'warmup' => V("Let's talk about business trips. What do you always pack for a work trip?", 'Давайте поговорим о деловых поездках. Что вы всегда берёте в рабочую поездку?', 'Іссапарлар туралы сөйлесейік. Іссапарға әрдайым не аласыз?'),
    'vocab' => [V('business trip', 'командировка', 'іссапар'), V('suitcase', 'чемодан', 'чемодан'), V('laptop', 'ноутбук', 'ноутбук'), V('formal wear', 'деловая одежда', 'іскерлік киім'), V('itinerary', 'маршрут', 'бағыт-жоспар'), V('expense report', 'отчёт о расходах', 'шығын есебі'), V('client meeting', 'встреча с клиентом', 'клиентпен кездесу'), V('flight', 'рейс', 'рейс'), V('hotel', 'отель', 'қонақүй'), V('jet lag', 'смена часовых поясов', 'уақыт белдеуінің ауысуы')],
    'questions' => [
        V('Have you ever gone on a business trip?', 'Вы когда-нибудь ездили в командировку?', 'Іссапарға бардыңыз ба?'),
        V('What do you always pack for a work trip?', 'Что вы всегда берёте в рабочую поездку?', 'Жұмыс сапарына әрдайым не аласыз?'),
        V('Do you enjoy business trips, or find them tiring?', 'Вам нравятся командировки, или они вас утомляют?', 'Іссапарларды ұнатасыз ба, әлде шаршатады ма?'),
        V('Do you bring formal clothes for client meetings?', 'Вы берёте деловую одежду для встреч с клиентами?', 'Клиенттермен кездесулерге іскерлік киім аласыз ба?'),
        V('Have you ever experienced jet lag on a trip?', 'Вы когда-нибудь испытывали смену часовых поясов в поездке?', 'Сапарда уақыт белдеуінің ауысуын сезіндіңіз бе?'),
        V('Do you plan your itinerary carefully before a trip?', 'Вы тщательно планируете маршрут перед поездкой?', 'Сапар алдында бағыт-жоспарды мұқият жоспарлайсыз ба?'),
        V('Do you keep receipts for an expense report?', 'Вы храните чеки для отчёта о расходах?', 'Шығын есебі үшін чектерді сақтайсыз ба?'),
        V('Do you prefer staying in a hotel near the airport or the city center?', 'Вы предпочитаете отель рядом с аэропортом или в центре города?', 'Әуежайға жақын қонақүйді ұнатасыз ба, әлде қала орталығындағыны ма?'),
        V('Have you ever forgotten something important before a business trip?', 'Вы когда-нибудь забывали что-то важное перед командировкой?', 'Іссапар алдында маңызды бір нәрсені ұмытып қалдыңыз ба?'),
        V('Do you work during flights?', 'Вы работаете во время перелётов?', 'Ұшу кезінде жұмыс істейсіз бе?'),
        V('Is packing light important to you for business trips?', 'Важно ли для вас брать мало вещей в деловые поездки?', 'Іссапарлар үшін жеңіл жиналу сіз үшін маңызды ма?'),
        V('Do you enjoy exploring a city during a business trip?', 'Вам нравится осматривать город во время командировки?', 'Іссапар кезінде қаланы аралауды ұнатасыз ба?'),
        V('Would you rather travel for work alone or with colleagues?', 'Вы бы предпочли ездить по работе одни или с коллегами?', 'Жұмыс бойынша жалғыз саяхаттауды қалайсыз ба, әлде әріптестермен бе?'),
        V('Do you feel more tired after a business trip than a vacation?', 'Вы чувствуете себя более уставшим после командировки, чем после отпуска?', 'Іссапардан кейін демалыстан гөрі көбірек шаршаған сезінесіз бе?'),
        V('What is the most important item you never forget to pack?', 'Какой самый важный предмет вы никогда не забываете упаковать?', 'Жинауды ешқашан ұмытпайтын ең маңызды затыңыз не?'),
    ],
];

$lessons[] = ['level' => 'elementary', 'topic' => 'Choosing a Smartphone', 'background_key' => 'night-city',
    'warmup' => V("Let's talk about smartphones. How do you decide which phone to buy?", 'Давайте поговорим о смартфонах. Как вы решаете, какой телефон купить?', 'Смартфондар туралы сөйлесейік. Қандай телефон сатып алуды қалай шешесіз?'),
    'vocab' => [V('smartphone', 'смартфон', 'смартфон'), V('camera quality', 'качество камеры', 'камера сапасы'), V('storage', 'память (хранение)', 'жад'), V('battery life', 'время работы батареи', 'батарея жұмыс уақыты'), V('brand', 'бренд', 'бренд'), V('upgrade', 'обновление', 'жаңарту'), V('screen size', 'размер экрана', 'экран өлшемі'), V('price range', 'ценовой диапазон', 'баға диапазоны'), V('warranty', 'гарантия', 'кепілдік'), V('durability', 'долговечность', 'төзімділік')],
    'questions' => [
        V('What brand of smartphone do you use?', 'Каким брендом смартфона вы пользуетесь?', 'Қандай смартфон брендін пайдаланасыз?'),
        V('What matters most to you when choosing a phone?', 'Что для вас важнее всего при выборе телефона?', 'Телефон таңдағанда сіз үшін ең маңыздысы не?'),
        V('Do you upgrade your phone often?', 'Вы часто обновляете телефон?', 'Телефоныңызды жиі жаңартасыз ба?'),
        V('Is camera quality important to you in a phone?', 'Качество камеры важно для вас в телефоне?', 'Телефонда камера сапасы сіз үшін маңызды ма?'),
        V('Do you worry about your phone\'s battery life?', 'Вы беспокоитесь о времени работы батареи телефона?', 'Телефоныңыздың батарея жұмыс уақыты туралы алаңдайсыз ба?'),
        V('Have you ever bought an expensive phone and regretted it?', 'Вы когда-нибудь покупали дорогой телефон и жалели об этом?', 'Қымбат телефон сатып алып, оған өкіндіңіз бе?'),
        V('Do you prefer a big screen or a small, easy-to-hold phone?', 'Вы предпочитаете большой экран или маленький, удобный телефон?', 'Үлкен экранды ұнатасыз ба, әлде ұстауға ыңғайлы кішіні ме?'),
        V('Do you read reviews before buying a new phone?', 'Вы читаете отзывы перед покупкой нового телефона?', 'Жаңа телефон сатып алмас бұрын пікірлерді оқисыз ба?'),
        V('How long do you usually keep the same phone?', 'Как долго вы обычно пользуетесь одним телефоном?', 'Бір телефонды әдетте қанша уақыт пайдаланасыз?'),
        V('Do you buy phone insurance or a warranty?', 'Вы покупаете страховку или гарантию на телефон?', 'Телефонға сақтандыру немесе кепілдік сатып аласыз ба?'),
        V('Have you ever dropped and broken a phone screen?', 'Вы когда-нибудь роняли и разбивали экран телефона?', 'Телефон экранын түсіріп сындырдыңыз ба?'),
        V('Do you think expensive phones are worth the price?', 'Как вы думаете, дорогие телефоны стоят своих денег?', 'Қымбат телефондар өз бағасына тұрарлық деп ойлайсыз ба?'),
        V('Would you buy a used phone to save money?', 'Вы бы купили подержанный телефон, чтобы сэкономить?', 'Ақша үнемдеу үшін қолданылған телефон сатып алар ма едіңіз?'),
        V('Do you back up your phone data regularly?', 'Вы регулярно делаете резервную копию данных телефона?', 'Телефон деректерін тұрақты сақтық көшірмелейсіз бе?'),
        V('What feature would you most like to see in future phones?', 'Какую функцию вы больше всего хотели бы увидеть в будущих телефонах?', 'Болашақ телефондарда қандай мүмкіндікті ең көп көргіңіз келеді?'),
    ],
];

$lessons[] = ['level' => 'elementary', 'topic' => 'Dealing with Noisy Neighbors', 'background_key' => 'minimal-dark',
    'warmup' => V("Let's talk about noisy neighbors. Have you ever had a problem with noise from neighbors?", 'Давайте поговорим о шумных соседях. У вас когда-нибудь были проблемы с шумом от соседей?', 'Шулы көршілер туралы сөйлесейік. Көршілерден шығатын шумен мәселеңіз болды ма?'),
    'vocab' => [V('noise complaint', 'жалоба на шум', 'шу туралы шағым'), V('loud music', 'громкая музыка', 'қатты музыка'), V('thin walls', 'тонкие стены', 'жұқа қабырғалар'), V('quiet hours', 'тихие часы', 'тыныш сағаттар'), V('confront', 'противостоять', 'қарсы шығу'), V('landlord', 'арендодатель', 'үй иесі'), V('earplugs', 'беруши', 'құлаққап'), V('polite note', 'вежливая записка', 'сыпайы жазба'), V('patience', 'терпение', 'шыдамдылық'), V('resolve', 'разрешить (проблему)', 'шешу')],
    'questions' => [
        V('Have you ever had a problem with noisy neighbors?', 'У вас когда-нибудь были проблемы с шумными соседями?', 'Шулы көршілермен мәселеңіз болды ма?'),
        V('Do you have thin walls in your home?', 'У вас дома тонкие стены?', 'Үйіңізде жұқа қабырғалар бар ма?'),
        V('Would you confront a noisy neighbor directly?', 'Вы бы прямо поговорили с шумным соседом?', 'Шулы көршіге тікелей айтар ма едіңіз?'),
        V('Have you ever written a polite note to a neighbor?', 'Вы когда-нибудь писали вежливую записку соседу?', 'Көршіге сыпайы жазба жаздыңыз ба?'),
        V('Do you use earplugs to sleep if it is noisy?', 'Вы пользуетесь берушами, чтобы спать, если шумно?', 'Шулы болса, ұйықтау үшін құлаққапты пайдаланасыз ба?'),
        V('Are there quiet hours where you live?', 'Есть ли тихие часы там, где вы живёте?', 'Тұратын жеріңізде тыныш сағаттар бар ма?'),
        V('Have you ever complained to a landlord about noise?', 'Вы когда-нибудь жаловались арендодателю на шум?', 'Шу туралы үй иесіне шағымдандыңыз ба?'),
        V('Do you think loud music late at night is unreasonable?', 'Как вы думаете, громкая музыка поздно ночью — это неразумно?', 'Кеш түнде қатты музыка ойнату орынсыз деп ойлайсыз ба?'),
        V('Have you ever been the noisy neighbor yourself?', 'Вы сами когда-нибудь были шумным соседом?', 'Сіз өзіңіз шулы көрші болдыңыз ба?'),
        V('Do you try to be patient before complaining about noise?', 'Вы стараетесь быть терпеливым, прежде чем жаловаться на шум?', 'Шу туралы шағымданбас бұрын шыдамды болуға тырысасыз ба?'),
        V('Would you move because of a permanently noisy neighbor?', 'Вы бы переехали из-за постоянно шумного соседа?', 'Тұрақты шулы көрші себебінен көшер ме едіңіз?'),
        V('Do apartment buildings usually have noise rules?', 'В многоквартирных домах обычно есть правила о шуме?', 'Көп пәтерлі үйлерде әдетте шу ережелері бар ма?'),
        V('How do you usually resolve conflicts with neighbors?', 'Как вы обычно разрешаете конфликты с соседями?', 'Көршілермен қақтығыстарды әдетте қалай шешесіз?'),
        V('Do you feel guilty when you are the one making noise?', 'Вы чувствуете вину, когда шум создаёте вы сами?', 'Шуды өзіңіз жасағанда кінәлі сезінесіз бе?'),
        V('Is it easier to talk to neighbors, or send a note?', 'Легче поговорить с соседями, или отправить записку?', 'Көршілермен сөйлесу оңайырақ па, әлде жазба жіберу ме?'),
    ],
];

$lessons[] = ['level' => 'elementary', 'topic' => 'Learning to Budget as a Student', 'background_key' => 'professional',
    'warmup' => V("Let's talk about budgeting as a student. How do students usually manage their money?", 'Давайте поговорим о бюджете студента. Как студенты обычно управляют деньгами?', 'Студент бюджеті туралы сөйлесейік. Студенттер әдетте ақшаны қалай басқарады?'),
    'vocab' => [V('budget', 'бюджет', 'бюджет'), V('allowance', 'карманные деньги', 'қалта ақшасы'), V('part-time job', 'подработка', 'жарты күндік жұмыс'), V('textbook cost', 'стоимость учебников', 'оқулық құны'), V('cheap meal', 'дешёвая еда', 'арзан тамақ'), V('save up', 'копить', 'жинау'), V('overspend', 'перерасходовать', 'артық жұмсау'), V('discount', 'скидка', 'жеңілдік'), V('student loan', 'студенческий кредит', 'студенттік несие'), V('financial plan', 'финансовый план', 'қаржылық жоспар')],
    'questions' => [
        V('Do you or did you have a budget as a student?', 'У вас есть или был бюджет как у студента?', 'Студент ретінде бюджетіңіз бар ма немесе болды ма?'),
        V('Did you have a part-time job while studying?', 'У вас была подработка во время учёбы?', 'Оқу кезінде жарты күндік жұмысыңыз болды ма?'),
        V('How did you afford textbooks and school materials?', 'Как вы могли позволить себе учебники и материалы?', 'Оқулықтар мен материалдарға қалай ақша тапқансыз?'),
        V('Did you often overspend as a student?', 'Вы часто перерасходовали деньги как студент?', 'Студент кезіңізде жиі артық жұмсадыңыз ба?'),
        V('Do you think students should learn budgeting in school?', 'Как вы думаете, студенты должны учиться бюджетированию в школе?', 'Студенттер мектепте бюджет жасауды үйренуі керек деп ойлайсыз ба?'),
        V('Did you look for student discounts?', 'Вы искали студенческие скидки?', 'Студенттік жеңілдіктерді іздедіңіз бе?'),
        V('Did you eat cheap meals to save money?', 'Вы ели дешёвую еду, чтобы сэкономить?', 'Ақша үнемдеу үшін арзан тамақ жедіңіз бе?'),
        V('Do you think student loans are necessary or risky?', 'Как вы думаете, студенческие кредиты необходимы или рискованны?', 'Студенттік несиелер қажет пе, әлде тәуекелді ме деп ойлайсыз ба?'),
        V('Did you save any money during your studies?', 'Вы откладывали деньги во время учёбы?', 'Оқу кезінде ақша жинадыңыз ба?'),
        V('What was your biggest expense as a student?', 'Какой был ваш самый большой расход как студента?', 'Студент кезіндегі ең үлкен шығыныңыз не болды?'),
        V('Did your parents help you financially during school?', 'Родители помогали вам финансово во время учёбы?', 'Ата-анаңыз оқу кезінде қаржылай көмектесті ме?'),
        V('Would a financial plan have helped you as a student?', 'Финансовый план помог бы вам как студенту?', 'Қаржылық жоспар студент ретінде сізге көмектесер ме еді?'),
        V('Did you compare prices before buying things as a student?', 'Вы сравнивали цены перед покупками как студент?', 'Студент ретінде сатып алмас бұрын бағаларды салыстырдыңыз ба?'),
        V('Do you think it is harder to budget now compared to your student years?', 'Как вы думаете, сейчас труднее вести бюджет, чем в студенческие годы?', 'Қазір бюджет жасау студент жылдарыңызбен салыстырғанда қиынырақ деп ойлайсыз ба?'),
        V('What budgeting advice would you give a new student?', 'Какой совет по бюджету вы бы дали новому студенту?', 'Жаңа студентке бюджет туралы қандай кеңес берер едіңіз?'),
    ],
];

$lessons[] = ['level' => 'elementary', 'topic' => 'Planning a Road Trip', 'background_key' => 'energetic',
    'warmup' => V("Let's talk about road trips. Have you ever planned a long trip by car?", 'Давайте поговорим о путешествиях на машине. Вы когда-нибудь планировали долгую поездку на машине?', 'Көлікпен саяхаттар туралы сөйлесейік. Көлікпен ұзақ сапарды жоспарладыңыз ба?'),
    'vocab' => [V('road trip', 'путешествие на машине', 'көлікпен саяхат'), V('route', 'маршрут', 'маршрут'), V('gas station', 'заправка', 'жанармай құю станциясы'), V('playlist', 'плейлист', 'ойнату тізімі'), V('snacks', 'закуски', 'жеңіл тамақтар'), V('rest stop', 'место отдыха', 'демалыс аялдамасы'), V('scenic view', 'живописный вид', 'көркем көрініс'), V('co-driver', 'второй водитель', 'екінші жүргізуші'), V('breakdown', 'поломка', 'бұзылу'), V('budget', 'бюджет', 'бюджет')],
    'questions' => [
        V('Have you ever been on a long road trip?', 'Вы когда-нибудь ездили в долгое путешествие на машине?', 'Көлікпен ұзақ саяхатқа бардыңыз ба?'),
        V('What do you always bring on a road trip?', 'Что вы всегда берёте в путешествие на машине?', 'Көлікпен саяхатқа әрдайым не аласыз?'),
        V('Do you plan your route in advance, or improvise?', 'Вы планируете маршрут заранее, или импровизируете?', 'Маршрутты алдын ала жоспарлайсыз ба, әлде экспромтпен жүресіз бе?'),
        V('Do you make a playlist for road trips?', 'Вы делаете плейлист для путешествий на машине?', 'Көлікпен саяхаттар үшін ойнату тізімін жасайсыз ба?'),
        V('What snacks do you bring on long drives?', 'Какие закуски вы берёте в долгие поездки?', 'Ұзақ сапарларға қандай жеңіл тамақ аласыз?'),
        V('Have you ever had a car breakdown during a road trip?', 'У вас когда-нибудь ломалась машина во время путешествия?', 'Саяхат кезінде көлігіңіз бұзылды ма?'),
        V('Do you prefer driving alone or having a co-driver?', 'Вы предпочитаете ехать одни или с напарником?', 'Жалғыз жүруді ұнатасыз ба, әлде серігіңізбен бе?'),
        V('Do you stop often to see scenic views?', 'Вы часто останавливаетесь, чтобы посмотреть на живописные виды?', 'Көркем көріністерді көру үшін жиі тоқтайсыз ба?'),
        V('How do you decide how much to budget for a road trip?', 'Как вы решаете, сколько заложить в бюджет для поездки?', 'Саяхат үшін бюджетті қаншалықты бөлуді қалай шешесіз?'),
        V('Do you take rest stops often on long drives?', 'Вы часто делаете остановки для отдыха в долгих поездках?', 'Ұзақ сапарларда демалыс аялдамасын жиі жасайсыз ба?'),
        V('What is the most memorable road trip you have taken?', 'Какое самое запоминающееся путешествие на машине у вас было?', 'Барған ең есте қаларлық көлікпен саяхатыңыз қандай болды?'),
        V('Do you check the car before starting a long trip?', 'Вы проверяете машину перед долгой поездкой?', 'Ұзақ сапар алдында көлікті тексересіз бе?'),
        V('Would you rather take a road trip or fly to your destination?', 'Вы бы предпочли поездку на машине или перелёт до места назначения?', 'Көлікпен саяхаттауды қалайсыз ба, әлде мақсатты жерге ұшуды ма?'),
        V('Do you get tired easily during long drives?', 'Вы легко устаёте во время долгих поездок?', 'Ұзақ сапарларда оңай шаршайсыз ба?'),
        V('What destination would you love to reach by road trip?', 'До какого места вы бы хотели добраться на машине?', 'Көлікпен қандай жерге жеткіңіз келеді?'),
    ],
];

$lessons[] = ['level' => 'elementary', 'topic' => 'Adopting a Pet', 'background_key' => 'warm',
    'warmup' => V("Let's talk about adopting pets. Would you adopt a pet from a shelter?", 'Давайте поговорим об усыновлении питомцев. Вы бы взяли питомца из приюта?', 'Үй жануарын асырап алу туралы сөйлесейік. Паналайтын жерден үй жануарын алар ма едіңіз?'),
    'vocab' => [V('shelter', 'приют', 'баспана'), V('adopt', 'усыновлять (питомца)', 'асырап алу'), V('rescue', 'спасённое (животное)', 'құтқарылған'), V('responsibility', 'ответственность', 'жауапкершілік'), V('vet visit', 'визит к ветеринару', 'ветеринарға бару'), V('vaccination', 'вакцинация', 'вакцинация'), V('bond', 'связь (эмоциональная)', 'байланыс'), V('training', 'дрессировка', 'үйрету'), V('lifelong commitment', 'пожизненное обязательство', 'өмір бойы міндеттеме'), V('foster', 'временный приют', 'уақытша қамқорлық')],
    'questions' => [
        V('Would you adopt a pet from a shelter?', 'Вы бы взяли питомца из приюта?', 'Паналайтын жерден үй жануарын алар ма едіңіз?'),
        V('Do you think adopting is better than buying from a breeder?', 'Как вы думаете, усыновление лучше, чем покупка у заводчика?', 'Асырап алу тұқымнан сатып алудан жақсы деп ойлайсыз ба?'),
        V('Have you ever visited an animal shelter?', 'Вы когда-нибудь посещали приют для животных?', 'Жануарлар паналайтын жерге бардыңыз ба?'),
        V('Do you understand the responsibility of having a pet?', 'Вы понимаете ответственность за питомца?', 'Үй жануарын ұстаудың жауапкершілігін түсінесіз бе?'),
        V('Would you foster an animal temporarily?', 'Вы бы взяли животное на временное содержание?', 'Жануарды уақытша қамқорлыққа алар ма едіңіз?'),
        V('Do you think older pets deserve adoption too?', 'Как вы думаете, старшие питомцы тоже заслуживают усыновления?', 'Егде үй жануарлары да асырап алынуға лайық деп ойлайсыз ба?'),
        V('Have you ever bonded quickly with an animal?', 'Вы когда-нибудь быстро находили связь с животным?', 'Жануармен тез байланыс тапқаныңыз болды ма?'),
        V('Do you think training a rescued pet is difficult?', 'Как вы думаете, дрессировать спасённого питомца трудно?', 'Құтқарылған үй жануарын үйрету қиын деп ойлайсыз ба?'),
        V('Are you ready for the lifelong commitment of owning a pet?', 'Вы готовы к пожизненному обязательству владения питомцем?', 'Үй жануарын ұстаудың өмір бойы міндеттемесіне дайынсыз ба?'),
        V('Do you regularly take pets for vet visits?', 'Вы регулярно водите питомцев к ветеринару?', 'Үй жануарларын ветеринарға тұрақты апарасыз ба?'),
        V('What kind of animal would you like to adopt?', 'Какое животное вы хотели бы усыновить?', 'Қандай жануарды асырап алғыңыз келеді?'),
        V('Do you think shelters have too many animals waiting for homes?', 'Как вы думаете, в приютах слишком много животных, ожидающих дом?', 'Паналайтын жерлерде үй күтіп жатқан жануарлар тым көп деп ойлайсыз ба?'),
        V('Have you ever helped find a home for a stray animal?', 'Вы когда-нибудь помогали найти дом для бездомного животного?', 'Иесіз жануарға үй табуға көмектестіңіз бе?'),
        V('Do you think adopting a pet changes a person\'s daily life a lot?', 'Как вы думаете, усыновление питомца сильно меняет повседневную жизнь человека?', 'Үй жануарын асырап алу адамның күнделікті өмірін көп өзгертеді деп ойлайсыз ба?'),
        V('What is the most rewarding part of having a pet, in your opinion?', 'Что самое приятное в содержании питомца, по-вашему?', 'Сіздің ойыңызша, үй жануарын ұстаудың ең қуантатын жағы не?'),
    ],
];

$lessons[] = ['level' => 'elementary', 'topic' => 'Preparing for a Job Change', 'background_key' => 'professional',
    'warmup' => V("Let's talk about changing jobs. What do people usually do to prepare for a career change?", 'Давайте поговорим о смене работы. Что люди обычно делают, чтобы подготовиться к смене карьеры?', 'Жұмыс ауыстыру туралы сөйлесейік. Адамдар мансап ауыстыруға дайындалу үшін әдетте не істейді?'),
    'vocab' => [V('resume', 'резюме', 'түйіндеме'), V('networking', 'нетворкинг', 'байланыс құру'), V('interview', 'собеседование', 'сұхбат'), V('reference', 'рекомендация', 'ұсынымхат'), V('notice period', 'срок уведомления', 'ескерту мерзімі'), V('career change', 'смена карьеры', 'мансап ауысымы'), V('skill gap', 'пробел в навыках', 'дағды алшақтығы'), V('salary negotiation', 'переговоры о зарплате', 'жалақы туралы келіссөз'), V('opportunity', 'возможность', 'мүмкіндік'), V('risk', 'риск', 'тәуекел')],
    'questions' => [
        V('Have you ever changed careers or jobs?', 'Вы когда-нибудь меняли карьеру или работу?', 'Мансап немесе жұмысыңызды ауыстырдыңыз ба?'),
        V('What steps do you take to prepare for a job change?', 'Какие шаги вы предпринимаете, чтобы подготовиться к смене работы?', 'Жұмыс ауыстыруға дайындалу үшін қандай қадамдар жасайсыз?'),
        V('Do you update your resume regularly, even if you are not job hunting?', 'Вы регулярно обновляете резюме, даже если не ищете работу?', 'Жұмыс іздемесеңіз де, түйіндемеңізді тұрақты жаңартасыз ба?'),
        V('Is networking important for finding new opportunities?', 'Важен ли нетворкинг для поиска новых возможностей?', 'Жаңа мүмкіндіктерді табу үшін байланыс құру маңызды ма?'),
        V('Do you feel confident during job interviews?', 'Вы чувствуете себя уверенно на собеседованиях?', 'Сұхбат кезінде өзіңізді сенімді сезінесіз бе?'),
        V('Have you ever negotiated your salary?', 'Вы когда-нибудь вели переговоры о зарплате?', 'Жалақыңыз туралы келіссөз жүргіздіңіз бе?'),
        V('Would you take a risk and change careers completely?', 'Вы бы рискнули и полностью сменили карьеру?', 'Мансабыңызды толығымен ауыстыруға тәуекел етер ме едіңіз?'),
        V('Do you ask former coworkers for references?', 'Вы просите бывших коллег дать рекомендации?', 'Бұрынғы әріптестеріңізден ұсынымхат сұрайсыз ба?'),
        V('Have you ever felt a skill gap when applying for a job?', 'Вы когда-нибудь чувствовали пробел в навыках, подавая заявку на работу?', 'Жұмысқа өтініш бергенде дағды алшақтығын сезіндіңіз бе?'),
        V('How much notice do you think is fair to give an employer?', 'Сколько времени, по-вашему, справедливо предупредить работодателя?', 'Жұмыс берушіні қаншалықты уақыт бұрын ескерту әділ деп ойлайсыз?'),
        V('Do you research a company before an interview?', 'Вы изучаете компанию перед собеседованием?', 'Сұхбат алдында компанияны зерттейсіз бе?'),
        V('Would you leave a stable job for a better opportunity?', 'Вы бы ушли с надёжной работы ради лучшей возможности?', 'Жақсырақ мүмкіндік үшін тұрақты жұмыстан кетер ме едіңіз?'),
        V('Do you think it is common to change careers multiple times today?', 'Как вы думаете, сегодня часто меняют карьеру несколько раз?', 'Бүгінде мансапты бірнеше рет ауыстыру жиі кездесе ме деп ойлайсыз ба?'),
        V('What is the scariest part of changing jobs for you?', 'Что для вас самое пугающее в смене работы?', 'Жұмыс ауыстырудың сіз үшін ең қорқынышты бөлігі не?'),
        V('What advice would you give someone considering a career change?', 'Какой совет вы бы дали тому, кто рассматривает смену карьеры?', 'Мансабын ауыстыруды ойлап жатқан адамға қандай кеңес берер едіңіз?'),
    ],
];

$lessons[] = ['level' => 'elementary', 'topic' => 'Managing Household Bills', 'background_key' => 'professional',
    'warmup' => V("Let's talk about household bills. How do you keep track of all your monthly bills?", 'Давайте поговорим о домашних счетах. Как вы отслеживаете все ежемесячные счета?', 'Үй шоттары туралы сөйлесейік. Барлық айлық шоттарыңызды қалай қадағалайсыз?'),
    'vocab' => [V('electricity bill', 'счёт за электричество', 'электр қуаты шоты'), V('water bill', 'счёт за воду', 'су шоты'), V('internet bill', 'счёт за интернет', 'интернет шоты'), V('due date', 'срок оплаты', 'төлем мерзімі'), V('autopay', 'автоплатёж', 'автоматты төлем'), V('budget', 'бюджет', 'бюджет'), V('overdue', 'просроченный', 'мерзімі өткен'), V('split bills', 'делить счета', 'шоттарды бөлу'), V('savings', 'сбережения', 'жинақ'), V('subscription', 'подписка', 'жазылым')],
    'questions' => [
        V('How do you keep track of your monthly bills?', 'Как вы отслеживаете ежемесячные счета?', 'Айлық шоттарыңызды қалай қадағалайсыз?'),
        V('Do you set up automatic payments for bills?', 'Вы настраиваете автоматические платежи для счетов?', 'Шоттар үшін автоматты төлемдерді орнатасыз ба?'),
        V('Have you ever paid a bill late?', 'Вы когда-нибудь платили по счёту с опозданием?', 'Шотты кеш төледіңіз бе?'),
        V('Do you split bills with roommates or family?', 'Вы делите счета с соседями по квартире или семьёй?', 'Шоттарды бөлме серіктерімен немесе отбасымен бөлесіз бе?'),
        V('What is your biggest monthly bill?', 'Какой ваш самый большой ежемесячный счёт?', 'Ең үлкен айлық шотыңыз қандай?'),
        V('Do you review your subscriptions to cancel ones you don\'t use?', 'Вы проверяете подписки, чтобы отменить те, которыми не пользуетесь?', 'Пайдаланбайтын жазылымдарды тоқтату үшін оларды тексересіз бе?'),
        V('Do you try to reduce your electricity bill?', 'Вы стараетесь снизить счёт за электричество?', 'Электр қуаты шотын азайтуға тырысасыз ба?'),
        V('Have you ever been surprised by a bill that was higher than expected?', 'Вас когда-нибудь удивлял счёт, который был выше ожидаемого?', 'Күткеннен жоғары шот сізді таңғалдырды ма?'),
        V('Do you compare providers to find better prices?', 'Вы сравниваете поставщиков, чтобы найти лучшие цены?', 'Жақсы бағаны табу үшін провайдерлерді салыстырасыз ба?'),
        V('Is managing bills stressful for you?', 'Управление счетами вызывает у вас стресс?', 'Шоттарды басқару сізге күйзелісті ме?'),
        V('Do you keep a savings fund for unexpected bills?', 'У вас есть сберегательный фонд для непредвиденных счетов?', 'Күтпеген шоттар үшін жинақ қорыңыз бар ма?'),
        V('Who in your household usually pays the bills?', 'Кто в вашей семье обычно платит по счетам?', 'Үй ішінде әдетте кім шоттарды төлейді?'),
        V('Do you check your bills carefully for mistakes?', 'Вы внимательно проверяете счета на ошибки?', 'Шоттарыңызды қателерге мұқият тексересіз бе?'),
        V('Would a fixed monthly budget help you manage bills better?', 'Фиксированный месячный бюджет помог бы вам лучше управлять счетами?', 'Тұрақты айлық бюджет шоттарды жақсырақ басқаруға көмектесер ме еді?'),
        V('What tip would you give someone struggling to pay bills on time?', 'Какой совет вы бы дали тому, кто с трудом платит по счетам вовремя?', 'Шоттарды уақытында төлеуге қиналған адамға қандай кеңес берер едіңіз?'),
    ],
];

$lessons[] = ['level' => 'elementary', 'topic' => 'Learning First Aid', 'background_key' => 'minimal-dark',
    'warmup' => V("Let's talk about first aid. Do you know basic first aid skills?", 'Давайте поговорим о первой помощи. Вы знаете основные навыки первой помощи?', 'Алғашқы көмек туралы сөйлесейік. Алғашқы көмектің негізгі дағдыларын білесіз бе?'),
    'vocab' => [V('first aid', 'первая помощь', 'алғашқы көмек'), V('bandage', 'бинт', 'бинт'), V('CPR', 'СЛР (сердечно-лёгочная реанимация)', 'жүрек-өкпе реанимациясы'), V('burn', 'ожог', 'күйік'), V('choking', 'удушье', 'тұншығу'), V('emergency', 'чрезвычайная ситуация', 'төтенше жағдай'), V('injury', 'травма', 'жарақат'), V('training course', 'учебный курс', 'оқу курсы'), V('calm down', 'успокоиться', 'сабырға түсу'), V('call for help', 'звать на помощь', 'көмекке шақыру')],
    'questions' => [
        V('Do you know any basic first aid skills?', 'Вы знаете какие-либо базовые навыки первой помощи?', 'Алғашқы көмектің негізгі дағдыларын білесіз бе?'),
        V('Have you ever taken a first aid training course?', 'Вы когда-нибудь проходили курс первой помощи?', 'Алғашқы көмек оқу курсынан өттіңіз бе?'),
        V('Would you know what to do if someone was choking?', 'Вы бы знали, что делать, если кто-то подавился?', 'Біреу тұншығып қалса, не істеу керектігін білер ме едіңіз?'),
        V('Do you know how to treat a small burn?', 'Вы знаете, как обработать небольшой ожог?', 'Кішкене күйікті қалай емдеу керектігін білесіз бе?'),
        V('Have you ever needed to give first aid to someone?', 'Вам когда-нибудь приходилось оказывать первую помощь кому-то?', 'Біреуге алғашқы көмек көрсетуге тура келді ме?'),
        V('Do you have a first aid kit at home?', 'У вас дома есть аптечка первой помощи?', 'Үйде алғашқы көмек қобдишасы бар ма?'),
        V('Do you know how to stay calm in an emergency?', 'Вы знаете, как оставаться спокойным в чрезвычайной ситуации?', 'Төтенше жағдайда сабырлы болуды білесіз бе?'),
        V('Would you know when to call for professional help?', 'Вы бы знали, когда звать профессиональную помощь?', 'Кәсіби көмекке қашан хабарласу керектігін білер ме едіңіз?'),
        V('Do schools in your country teach first aid?', 'В школах вашей страны учат первой помощи?', 'Еліңіздегі мектептерде алғашқы көмекке үйрете ме?'),
        V('Have you ever witnessed an injury and helped?', 'Вы когда-нибудь были свидетелем травмы и помогали?', 'Жарақаттың куәсі болып, көмектестіңіз бе?'),
        V('Do you think everyone should learn CPR?', 'Как вы думаете, каждый должен изучить СЛР?', 'Әркім жүрек-өкпе реанимациясын үйренуі керек деп ойлайсыз ба?'),
        V('Would you feel confident helping in a medical emergency?', 'Вы бы чувствовали себя уверенно, помогая в медицинской чрезвычайной ситуации?', 'Медициналық төтенше жағдайда көмектесу сізге сенімді бола ма?'),
        V('Do you keep emergency phone numbers saved on your phone?', 'Вы храните номера экстренных служб в телефоне?', 'Телефонда төтенше жағдай нөмірлерін сақтайсыз ба?'),
        V('Would you take a first aid course if it was offered nearby?', 'Вы бы прошли курс первой помощи, если бы он предлагался поблизости?', 'Жақын жерде ұсынылса, алғашқы көмек курсынан өтер ме едіңіз?'),
        V('What first aid skill do you think is most important to know?', 'Какой навык первой помощи, по-вашему, самый важный?', 'Сіздің ойыңызша, алғашқы көмектің қандай дағдысын білу ең маңызды?'),
    ],
];

$lessons[] = ['level' => 'elementary', 'topic' => 'Choosing a Diet Plan', 'background_key' => 'calm',
    'warmup' => V("Let's talk about diets. Have you ever tried following a specific diet plan?", 'Давайте поговорим о диетах. Вы когда-нибудь пробовали следовать определённому плану питания?', 'Диеталар туралы сөйлесейік. Белгілі бір тамақтану жоспарын ұстанып көрдіңіз бе?'),
    'vocab' => [V('diet plan', 'план питания', 'тамақтану жоспары'), V('balanced meal', 'сбалансированное питание', 'теңдестірілген тамақ'), V('portion control', 'контроль порций', 'үлесті бақылау'), V('calorie', 'калория', 'калория'), V('nutrient', 'питательное вещество', 'қоректік зат'), V('cravings', 'сильное желание еды', 'тамаққа құштарлық'), V('cheat day', 'день послаблений', 'жеңілдік күні'), V('meal prep', 'заготовка еды', 'тамақты алдын ала дайындау'), V('sustainable', 'устойчивый (долгосрочный)', 'тұрақты'), V('goal', 'цель', 'мақсат')],
    'questions' => [
        V('Have you ever tried following a specific diet plan?', 'Вы когда-нибудь пробовали следовать определённому плану питания?', 'Белгілі бір тамақтану жоспарын ұстанып көрдіңіз бе?'),
        V('Do you count calories or focus on balanced meals instead?', 'Вы считаете калории или фокусируетесь на сбалансированном питании?', 'Калорияны санайсыз ба, әлде теңдестірілген тамаққа назар аударасыз ба?'),
        V('Do you allow yourself a cheat day sometimes?', 'Вы иногда позволяете себе день послаблений?', 'Кейде өзіңізге жеңілдік күнін рұқсат етесіз бе?'),
        V('Is it hard for you to control food cravings?', 'Вам трудно контролировать тягу к еде?', 'Тамаққа құштарлықты бақылау сізге қиын ба?'),
        V('Do you meal prep in advance?', 'Вы готовите еду заранее на несколько дней?', 'Тамақты алдын ала дайындайсыз ба?'),
        V('Do you think most diets are sustainable long-term?', 'Как вы думаете, большинство диет устойчивы в долгосрочной перспективе?', 'Көптеген диеталар ұзақ мерзімде тұрақты деп ойлайсыз ба?'),
        V('Have you ever quit a diet because it was too hard?', 'Вы когда-нибудь бросали диету, потому что было слишком трудно?', 'Тым қиын болғандықтан диетадан бас тарттыңыз ба?'),
        V('Do you set specific health goals for yourself?', 'Вы ставите себе конкретные цели по здоровью?', 'Өзіңізге нақты денсаулық мақсаттарын қоясыз ба?'),
        V('Do you think portion control matters more than what you eat?', 'Как вы думаете, контроль порций важнее того, что вы едите?', 'Үлесті бақылау не жейтініңізден маңыздырақ деп ойлайсыз ба?'),
        V('Would you follow a diet trend recommended by a friend?', 'Вы бы последовали диетическому тренду, рекомендованному другом?', 'Досыңыз ұсынған диета трендін ұстанар ма едіңіз?'),
        V('Do you read nutrition labels when shopping for food?', 'Вы читаете этикетки с составом при покупке еды?', 'Тамақ сатып алғанда қоректік құрам жапсырмаларын оқисыз ба?'),
        V('Would you consult a nutritionist to plan your diet?', 'Вы бы обратились к диетологу, чтобы спланировать питание?', 'Тамақтануыңызды жоспарлау үшін диетологқа хабарласар ма едіңіз?'),
        V('Do you think willpower alone is enough to follow a diet?', 'Как вы думаете, одной силы воли достаточно, чтобы соблюдать диету?', 'Тек ерік-жігер диетаны ұстануға жеткілікті деп ойлайсыз ба?'),
        V('Do you prefer cooking your own meals to control what you eat?', 'Вы предпочитаете готовить сами, чтобы контролировать питание?', 'Не жейтініңізді бақылау үшін өзіңіз тамақ жасағанды ұнатасыз ба?'),
        V('What is more important to you: how you look or how you feel?', 'Что для вас важнее: как вы выглядите или как себя чувствуете?', 'Сіз үшін не маңыздырақ: сырт көрінісіңіз бе, әлде өзіңізді қалай сезінуіңіз бе?'),
    ],
];

$lessons[] = ['level' => 'elementary', 'topic' => 'Setting Personal Goals', 'background_key' => 'minimal-dark',
    'warmup' => V("Let's talk about goals. Do you set personal goals for yourself, and do you achieve them?", 'Давайте поговорим о целях. Вы ставите себе личные цели и достигаете их?', 'Мақсаттар туралы сөйлесейік. Өзіңізге жеке мақсаттар қоясыз ба және оларға жетесіз бе?'),
    'vocab' => [V('goal', 'цель', 'мақсат'), V('achieve', 'достигать', 'жету'), V('progress', 'прогресс', 'прогресс'), V('deadline', 'срок', 'мерзім'), V('motivation', 'мотивация', 'мотивация'), V('obstacle', 'препятствие', 'кедергі'), V('milestone', 'веха', 'белес'), V('review', 'пересматривать', 'қайта қарау'), V('discipline', 'дисциплина', 'тәртіп'), V('reward', 'награда', 'сыйақы')],
    'questions' => [
        V('Do you set personal goals for yourself?', 'Вы ставите себе личные цели?', 'Өзіңізге жеке мақсаттар қоясыз ба?'),
        V('What is a goal you are currently working on?', 'Над какой целью вы сейчас работаете?', 'Қазір қандай мақсат үстінде жұмыс істеп жатырсыз?'),
        V('Do you write your goals down, or just think about them?', 'Вы записываете свои цели, или просто думаете о них?', 'Мақсаттарыңызды жазасыз ба, әлде жай ойлайсыз ба?'),
        V('Do you usually achieve the goals you set?', 'Вы обычно достигаете поставленных целей?', 'Қойған мақсаттарыңызға әдетте жетесіз бе?'),
        V('What obstacles usually stop you from reaching a goal?', 'Какие препятствия обычно мешают вам достичь цели?', 'Мақсатыңызға жетуге әдетте қандай кедергілер тосқауыл болады?'),
        V('Do you set deadlines for your personal goals?', 'Вы устанавливаете сроки для личных целей?', 'Жеке мақсаттарыңыз үшін мерзім белгілейсіз бе?'),
        V('How do you stay motivated when working toward a goal?', 'Как вы остаётесь мотивированным, работая над целью?', 'Мақсатқа қарай жұмыс істегенде қалай ынталы боласыз?'),
        V('Do you reward yourself after reaching a milestone?', 'Вы вознаграждаете себя после достижения вехи?', 'Белеске жеткеннен кейін өзіңізді марапаттайсыз ба?'),
        V('Do you review your goals regularly?', 'Вы регулярно пересматриваете свои цели?', 'Мақсаттарыңызды тұрақты қайта қарайсыз ба?'),
        V('Have you ever given up on a goal? Why?', 'Вы когда-нибудь отказывались от цели? Почему?', 'Мақсаттан бас тарттыңыз ба? Неге?'),
        V('Do you set big goals or small, easy ones?', 'Вы ставите большие цели или маленькие, лёгкие?', 'Үлкен мақсаттар қоясыз ба, әлде кішкентай, оңайларын ба?'),
        V('Is discipline or motivation more important for reaching goals?', 'Что важнее для достижения целей: дисциплина или мотивация?', 'Мақсатқа жету үшін тәртіп пе, әлде мотивация ма маңыздырақ?'),
        V('Do you share your goals with others, or keep them private?', 'Вы делитесь целями с другими, или держите их в тайне?', 'Мақсаттарыңызбен басқалармен бөлісесіз бе, әлде құпия сақтайсыз ба?'),
        V('What is the biggest goal you have ever achieved?', 'Какая самая большая цель, которую вы когда-либо достигли?', 'Жеткен ең үлкен мақсатыңыз қандай болды?'),
        V('What goal would you like to achieve in the next year?', 'Какую цель вы хотели бы достичь в следующем году?', 'Келесі жылы қандай мақсатқа жеткіңіз келеді?'),
    ],
];

require __DIR__ . '/seed_lessons_batch6_part3.php';
