<?php
declare(strict_types=1);

require_once __DIR__ . '/db.php';

// Curated word -> trilingual definitional clue bank. Hangman words are
// drawn from here (never from the lesson's own vocab list) so every clue
// actually describes the word instead of just showing it in a sentence.
function C(string $en, string $ru, string $kz): array { return ['en' => $en, 'ru' => $ru, 'kz' => $kz]; }

function build_hangman_clues(): array {
    return [
        'mother' => C("This is the woman who gave birth to you or raised you.", "Это женщина, которая родила вас или вырастила.", "Бұл сізді туған немесе тәрбиелеген әйел."),
        'father' => C("This is the man who is your parent.", "Это мужчина, который является вашим родителем.", "Бұл сіздің әкеңіз болып табылатын ер адам."),
        'sister' => C("This is a girl who has the same parents as you.", "Это девочка, у которой такие же родители, как у вас.", "Бұл сізбен бірдей ата-анасы бар қыз."),
        'brother' => C("This is a boy who has the same parents as you.", "Это мальчик, у которого такие же родители, как у вас.", "Бұл сізбен бірдей ата-анасы бар ұл."),
        'grandmother' => C("This is your mother's or father's mother.", "Это мать вашей мамы или папы.", "Бұл сіздің анаңыздың немесе әкеңіздің анасы."),
        'grandfather' => C("This is your mother's or father's father.", "Это отец вашей мамы или папы.", "Бұл сіздің анаңыздың немесе әкеңіздің әкесі."),
        'cousin' => C("This is the child of your aunt or uncle.", "Это ребёнок вашей тёти или дяди.", "Бұл сіздің апайыңыздың немесе ағайыңыздың баласы."),
        'uncle' => C("This is your father's or mother's brother.", "Это брат вашего отца или матери.", "Бұл сіздің әкеңіздің немесе анаңыздың ағасы/інісі."),
        'aunt' => C("This is your father's or mother's sister.", "Это сестра вашего отца или матери.", "Бұл сіздің әкеңіздің немесе анаңыздың апасы/қарындасы."),
        'family' => C("This is the group of people related to you, like parents and children.", "Это группа людей, связанных с вами, например родители и дети.", "Бұл сізбен туыс адамдар тобы, мысалы ата-аналар мен балалар."),
        'baby' => C("This is a very young child who cannot walk or talk yet.", "Это очень маленький ребёнок, который ещё не умеет ходить или говорить.", "Бұл әлі жүре немесе сөйлей алмайтын өте кішкентай бала."),
        'wife' => C("This is a married woman, in relation to her husband.", "Это замужняя женщина по отношению к своему мужу.", "Бұл күйеуіне қатысты тұрмыс құрған әйел."),
        'husband' => C("This is a married man, in relation to his wife.", "Это женатый мужчина по отношению к своей жене.", "Бұл әйеліне қатысты үйленген ер адам."),
        'friend' => C("This is a person you like and enjoy spending time with.", "Это человек, который вам нравится и с которым приятно проводить время.", "Бұл сізге ұнайтын және бірге уақыт өткізгіңіз келетін адам."),
        'neighbor' => C("This is a person who lives next to you or near you.", "Это человек, который живёт рядом с вами.", "Бұл сіздің қасыңызда тұратын адам."),
        'stranger' => C("This is a person you have never met before.", "Это человек, которого вы никогда раньше не встречали.", "Бұл сіз бұрын-соңды кездестірмеген адам."),
        'chicken' => C("This is meat and people eat it a lot.", "Это мясо, которое люди едят очень часто.", "Бұл ет, адамдар оны жиі жейді."),
        'bread' => C("This is baked from flour and eaten every day, often with butter.", "Это выпекается из муки и едят каждый день, часто с маслом.", "Бұл ұннан пісіріледі және күн сайын, көбіне маймен жейді."),
        'rice' => C("These are small white grains, very common in Asian cooking.", "Это маленькие белые зёрна, очень распространённые в азиатской кухне.", "Бұл Азия асханасында өте кең тараған кішкентай ақ дән."),
        'apple' => C("This round fruit, often red or green, is said to keep the doctor away.", "Этот круглый фрукт, часто красный или зелёный, как говорят, отгоняет доктора.", "Бұл жиі қызыл немесе жасыл түсті дөңгелек жеміс, дәрігерден алшақ ұстайды дейді."),
        'banana' => C("This is a long yellow fruit that monkeys love to eat.", "Это длинный жёлтый фрукт, который любят есть обезьяны.", "Бұл маймылдар жегенді жақсы көретін ұзын сары жеміс."),
        'orange' => C("This round citrus fruit shares its name with a color.", "Этот круглый цитрусовый фрукт имеет то же название, что и цвет.", "Бұл дөңгелек цитрус жемісінің атауы түстің атауымен бірдей."),
        'potato' => C("This vegetable grows underground and can be fried or boiled.", "Этот овощ растёт под землёй, его можно жарить или варить.", "Бұл көкөніс жер астында өседі, оны қуыруға немесе қайнатуға болады."),
        'tomato' => C("This red fruit is often used in salads and sauces.", "Этот красный плод часто используют в салатах и соусах.", "Бұл қызыл жеміс салаттар мен тұздықтарда жиі қолданылады."),
        'cheese' => C("This is made from milk and is often melted on pizza.", "Это делают из молока, и его часто плавят на пицце.", "Бұл сүттен жасалады және көбіне пиццаның үстінде ерітіледі."),
        'butter' => C("This soft yellow food is spread on bread.", "Этот мягкий жёлтый продукт намазывают на хлеб.", "Бұл жұмсақ сары тағамды нанға жағады."),
        'sugar' => C("This white substance makes your tea or coffee sweet.", "Это белое вещество делает ваш чай или кофе сладким.", "Бұл ақ зат шәйіңізді немесе кофеңізді тәтті етеді."),
        'salt' => C("This white substance is sprinkled on food to add flavor.", "Это белое вещество посыпают на еду, чтобы придать вкус.", "Бұл ақ зат дәм қосу үшін тағамға себіледі."),
        'milk' => C("This white drink comes from cows and is good for your bones.", "Этот белый напиток получают от коров, и он полезен для костей.", "Бұл ақ сусын сиырдан алынады және сүйекке пайдалы."),
        'coffee' => C("This hot dark drink helps people wake up in the morning.", "Этот горячий тёмный напиток помогает людям проснуться утром.", "Бұл ыстық қара сусын адамдарға таңертең ояну үшін көмектеседі."),
        'juice' => C("This sweet drink is made by pressing fruit.", "Этот сладкий напиток делают, отжимая фрукты.", "Бұл тәтті сусын жемісті сығу арқылы жасалады."),
        'soup' => C("This warm liquid food is often eaten with a spoon.", "Эту тёплую жидкую еду часто едят ложкой.", "Бұл жылы сұйық тағамды көбіне қасықпен жейді."),
        'salad' => C("This dish is made of raw vegetables mixed together.", "Это блюдо готовят из смешанных сырых овощей.", "Бұл тағам шикі көкөністерді араластырып жасалады."),
        'cake' => C("This sweet dessert is often eaten on birthdays.", "Этот сладкий десерт часто едят на дни рождения.", "Бұл тәтті десертті көбіне туған күндерде жейді."),
        'sandwich' => C("This food has fillings placed between two slices of bread.", "В этой еде начинка кладётся между двумя кусками хлеба.", "Бұл тағамда толтырғыш екі кесек нанның арасына салынады."),
        'breakfast' => C("This is the first meal you eat in the morning.", "Это первый приём пищи, который вы едите утром.", "Бұл таңертең жейтін алғашқы тамақ."),
        'vegetable' => C("This healthy food grows in a garden, like carrots or spinach.", "Эта полезная еда растёт в саду, например морковь или шпинат.", "Бұл пайдалы тағам бақшада өседі, мысалы сәбіз немесе саумалдық."),
        'fruit' => C("This sweet food grows on trees or plants, like apples or bananas.", "Эта сладкая еда растёт на деревьях или растениях, например яблоки или бананы.", "Бұл тәтті тағам ағаштарда немесе өсімдіктерде өседі, мысалы алма немесе банан."),
        'dog' => C("This animal is often called a person's best friend and loves to bark.", "Это животное часто называют лучшим другом человека, и оно любит лаять.", "Бұл жануарды жиі адамның ең жақын досы деп атайды және ол үруді жақсы көреді."),
        'cat' => C("This small animal likes to chase mice and says \"meow\".", "Это маленькое животное любит гоняться за мышами и говорит «мяу».", "Бұл кішкентай жануар тышқанды қууды жақсы көреді және «мияу» дейді."),
        'horse' => C("This large animal can be ridden and likes to run fast.", "На этом большом животном можно ездить верхом, и оно любит быстро бегать.", "Бұл үлкен жануарға мініп жүруге болады және ол жылдам жүгіруді жақсы көреді."),
        'cow' => C("This farm animal gives us milk.", "Это домашнее животное даёт нам молоко.", "Бұл үй жануары бізге сүт береді."),
        'sheep' => C("This farm animal has wool and says \"baa\".", "У этого домашнего животного есть шерсть, и оно говорит «бее».", "Бұл үй жануарының жүні бар және ол «маа» дейді."),
        'lion' => C("This big wild cat is known as the king of the jungle.", "Эту большую дикую кошку называют королём джунглей.", "Бұл үлкен жабайы мысық джунгли патшасы деп аталады."),
        'tiger' => C("This large wild cat has orange and black stripes.", "У этой большой дикой кошки оранжевые и чёрные полосы.", "Бұл үлкен жабайы мысықтың қызғылт сары және қара жолақтары бар."),
        'elephant' => C("This is the biggest land animal, and it has a long trunk.", "Это самое большое сухопутное животное, у него длинный хобот.", "Бұл ең үлкен құрлық жануары, оның ұзын хоботы бар."),
        'monkey' => C("This animal loves bananas and can climb trees quickly.", "Это животное любит бананы и умеет быстро лазить по деревьям.", "Бұл жануар бананды жақсы көреді және ағашқа тез өрмелей алады."),
        'rabbit' => C("This small animal has long ears and hops around.", "У этого маленького животного длинные уши, и оно прыгает.", "Бұл кішкентай жануардың құлақтары ұзын және секіріп жүреді."),
        'snake' => C("This long animal has no legs and can be dangerous.", "У этого длинного животного нет ног, и оно может быть опасным.", "Бұл ұзын жануардың аяғы жоқ және қауіпті болуы мүмкін."),
        'bear' => C("This large wild animal likes honey and sleeps through winter.", "Это большое дикое животное любит мёд и спит всю зиму.", "Бұл үлкен жабайы жануар балды жақсы көреді және қыста ұйықтайды."),
        'duck' => C("This bird swims on water and says \"quack\".", "Эта птица плавает по воде и говорит «кря».", "Бұл құс суда жүзеді және «қуақ» дейді."),
        'spider' => C("This small creature has eight legs and spins webs.", "У этого маленького существа восемь ног, и оно плетёт паутину.", "Бұл кішкентай жәндіктің сегіз аяғы бар және ол өрмек тоқиды."),
        'butterfly' => C("This colorful insect starts life as a caterpillar.", "Это яркое насекомое начинает жизнь как гусеница.", "Бұл түрлі-түсті жәндік өмірін көбелек құрты ретінде бастайды."),
        'rain' => C("This is water that falls from the clouds.", "Это вода, которая падает с облаков.", "Бұл бұлттардан жауатын су."),
        'snow' => C("This is soft, white, and cold, and falls in winter.", "Это мягкое, белое и холодное, выпадает зимой.", "Бұл жұмсақ, ақ әрі суық, қыста жауады."),
        'sun' => C("This bright object in the sky gives us light and heat.", "Этот яркий объект в небе даёт нам свет и тепло.", "Аспандағы бұл жарқын дене бізге жарық пен жылу береді."),
        'wind' => C("This is moving air that can blow your hat away.", "Это движущийся воздух, который может сдуть вашу шапку.", "Бұл қозғалыстағы ауа, ол сіздің бөркіңізді ұшырып әкетуі мүмкін."),
        'cloud' => C("This white or gray shape floats in the sky before it rains.", "Эта белая или серая фигура плывёт по небу перед дождём.", "Бұл ақ немесе сұр пішін жаңбыр жаумас бұрын аспанда қалқиды."),
        'storm' => C("This is very bad weather with strong wind and rain.", "Это очень плохая погода с сильным ветром и дождём.", "Бұл күшті жел мен жаңбыры бар өте жаман ауа райы."),
        'weather' => C("This word describes whether it is sunny, rainy, or cold outside.", "Это слово описывает, солнечно, дождливо или холодно на улице.", "Бұл сөз далада күн ашық, жаңбырлы немесе суық екенін сипаттайды."),
        'morning' => C("This is the part of the day right after you wake up.", "Это часть дня сразу после того, как вы просыпаетесь.", "Бұл сіз оянғаннан кейінгі күннің бөлігі."),
        'afternoon' => C("This is the part of the day between lunch and evening.", "Это часть дня между обедом и вечером.", "Бұл түскі астан кейін кештен бұрынғы күн бөлігі."),
        'evening' => C("This is the part of the day before night, after work or school.", "Это часть дня перед ночью, после работы или школы.", "Бұл жұмыстан немесе мектептен кейін, түннен бұрынғы күн бөлігі."),
        'tomorrow' => C("This is the day right after today.", "Это день сразу после сегодняшнего.", "Бұл бүгіннен кейінгі күн."),
        'yesterday' => C("This is the day right before today.", "Это день перед сегодняшним.", "Бұл бүгінге дейінгі күн."),
        'calendar' => C("This tool shows you all the days, weeks, and months of the year.", "Этот инструмент показывает вам все дни, недели и месяцы года.", "Бұл құрал сізге жылдың барлық күндерін, апталары мен айларын көрсетеді."),
        'schedule' => C("This is a plan that shows what you will do and when.", "Это план, который показывает, что и когда вы будете делать.", "Бұл не істейтініңізді және қашан істейтініңізді көрсететін жоспар."),
        'school' => C("This is a place where children go to learn.", "Это место, куда дети ходят учиться.", "Бұл балалар оқуға баратын орын."),
        'hospital' => C("This is a place where sick people go to get better.", "Это место, куда идут больные люди, чтобы поправиться.", "Бұл ауру адамдар жазылу үшін баратын орын."),
        'restaurant' => C("This is a place where you pay to eat a meal.", "Это место, где вы платите за еду.", "Бұл тамақ ішу үшін ақы төлейтін орын."),
        'airport' => C("This is a place where airplanes take off and land.", "Это место, где самолёты взлетают и приземляются.", "Бұл ұшақтар ұшып шығатын және қонатын орын."),
        'market' => C("This is a place where people buy and sell fresh food.", "Это место, где люди покупают и продают свежие продукты.", "Бұл адамдар жаңа өнімдерді сатып алатын және сататын орын."),
        'library' => C("This is a quiet place full of books you can borrow.", "Это тихое место, полное книг, которые можно взять почитать.", "Бұл сіз алып оқи алатын кітаптарға толы тыныш орын."),
        'beach' => C("This is a sandy place next to the sea.", "Это песчаное место рядом с морем.", "Бұл теңіздің жанындағы құмды орын."),
        'mountain' => C("This is a very tall landform, often covered in snow at the top.", "Это очень высокая форма рельефа, вершина которой часто покрыта снегом.", "Бұл өте биік жер бедері, оның шыңы көбіне қармен жабылған."),
        'forest' => C("This is a large area full of trees.", "Это большая территория, полная деревьев.", "Бұл ағаштарға толы үлкен аумақ."),
        'bridge' => C("This structure lets you cross a river or road.", "Это сооружение позволяет вам пересечь реку или дорогу.", "Бұл құрылым сізге өзен немесе жолдан өтуге мүмкіндік береді."),
        'museum' => C("This is a building where old and interesting objects are shown.", "Это здание, где показывают старые и интересные предметы.", "Бұл ескі және қызықты заттар көрсетілетін ғимарат."),
        'hotel' => C("This is a place where you pay to sleep when you travel.", "Это место, где вы платите за ночлег во время путешествия.", "Бұл сіз саяхаттағанда ұйықтау үшін ақы төлейтін орын."),
        'office' => C("This is a place where people go to do business work.", "Это место, куда люди ходят для деловой работы.", "Бұл адамдар іскерлік жұмыс істеу үшін баратын орын."),
        'table' => C("This furniture has four legs and you eat your meals on it.", "У этой мебели четыре ножки, и вы едите на ней.", "Бұл жиһаздың төрт аяғы бар және сіз тамақты соның үстінде ішесіз."),
        'chair' => C("This piece of furniture is made for one person to sit on.", "Этот предмет мебели предназначен для того, чтобы на нём сидел один человек.", "Бұл жиһаз бір адам отыруы үшін жасалған."),
        'window' => C("This lets light into your room and you can see outside through it.", "Это пропускает свет в вашу комнату, и через него видно улицу.", "Бұл бөлмеңізге жарық түсіреді және одан сыртты көруге болады."),
        'door' => C("You open and close this to enter or leave a room.", "Вы открываете и закрываете это, чтобы войти в комнату или выйти из неё.", "Сіз бөлмеге кіру немесе шығу үшін мұны ашасыз және жабасыз."),
        'kitchen' => C("This room in the house is used for cooking food.", "Эта комната в доме используется для приготовления еды.", "Үйдегі бұл бөлме тамақ пісіру үшін пайдаланылады."),
        'bedroom' => C("This is the room in a house where you sleep.", "Это комната в доме, где вы спите.", "Бұл үйдегі сіз ұйықтайтын бөлме."),
        'mirror' => C("You look into this to see your own face.", "Вы смотрите в это, чтобы увидеть своё лицо.", "Сіз өз бетіңізді көру үшін мұған қарайсыз."),
        'refrigerator' => C("This kitchen machine keeps your food cold.", "Эта кухонная техника хранит вашу еду холодной.", "Бұл ас үй құрылғысы тағамыңызды салқын ұстайды."),
        'shirt' => C("You wear this on the top part of your body.", "Вы носите это на верхней части тела.", "Сіз мұны денеңіздің жоғарғы бөлігіне киесіз."),
        'shoes' => C("You wear these on your feet to walk outside.", "Вы носите это на ногах, чтобы гулять на улице.", "Сіз мұны сыртта жүру үшін аяғыңызға киесіз."),
        'jacket' => C("You wear this over your clothes when it is cold outside.", "Вы надеваете это поверх одежды, когда на улице холодно.", "Сыртта суық болғанда мұны киіміңіздің үстінен киесіз."),
        'hat' => C("You wear this on top of your head.", "Вы носите это на голове.", "Сіз мұны басыңыздың үстіне киесіз."),
        'gloves' => C("You wear these to keep your hands warm.", "Вы носите это, чтобы согреть руки.", "Сіз қолыңызды жылы ұстау үшін мұны киесіз."),
        'head' => C("This is the top part of your body, where your brain is.", "Это верхняя часть вашего тела, где находится мозг.", "Бұл денеңіздің ми орналасқан жоғарғы бөлігі."),
        'hand' => C("You use this part of your body to hold things.", "Вы используете эту часть тела, чтобы держать вещи.", "Сіз заттарды ұстау үшін дене мүшесінің осы бөлігін пайдаланасыз."),
        'eye' => C("You use this part of your body to see.", "Вы используете эту часть тела, чтобы видеть.", "Сіз көру үшін дене мүшесінің осы бөлігін пайдаланасыз."),
        'ear' => C("You use this part of your body to hear.", "Вы используете эту часть тела, чтобы слышать.", "Сіз есту үшін дене мүшесінің осы бөлігін пайдаланасыз."),
        'nose' => C("You use this part of your body to smell.", "Вы используете эту часть тела, чтобы чувствовать запах.", "Сіз иіс сезу үшін дене мүшесінің осы бөлігін пайдаланасыз."),
        'mouth' => C("You use this part of your body to eat and speak.", "Вы используете эту часть тела, чтобы есть и говорить.", "Сіз тамақтану және сөйлеу үшін дене мүшесінің осы бөлігін пайдаланасыз."),
        'heart' => C("This organ pumps blood through your body.", "Этот орган перекачивает кровь по вашему телу.", "Бұл мүше қаныңызды денеңіз бойынша айдайды."),
        'happy' => C("This is how you feel when something good happens to you.", "Так вы себя чувствуете, когда с вами происходит что-то хорошее.", "Бұл сізбен жақсы бір нәрсе болғанда сезінетін көңіл-күй."),
        'sad' => C("This is how you feel when you want to cry.", "Так вы себя чувствуете, когда хотите плакать.", "Бұл жылағыңыз келгенде сезінетін көңіл-күй."),
        'angry' => C("This is how you feel when something makes you very upset.", "Так вы себя чувствуете, когда что-то вас сильно расстраивает.", "Бұл бір нәрсе сізді қатты ашуландырғанда сезінетін көңіл-күй."),
        'tired' => C("This is how you feel when you need to sleep.", "Так вы себя чувствуете, когда вам нужно спать.", "Бұл ұйықтау керек болғанда сезінетін көңіл-күй."),
        'hungry' => C("This is how you feel when your stomach needs food.", "Так вы себя чувствуете, когда ваш желудок требует еды.", "Бұл асқазаныңыз тамақ сұрағанда сезінетін көңіл-күй."),
        'thirsty' => C("This is how you feel when your body needs water.", "Так вы себя чувствуете, когда вашему телу нужна вода.", "Бұл денеңізге су керек болғанда сезінетін көңіл-күй."),
        'scared' => C("This is how you feel when something frightens you.", "Так вы себя чувствуете, когда что-то вас пугает.", "Бұл бір нәрсе сізді қорқытқанда сезінетін көңіл-күй."),
        'excited' => C("This is how you feel right before something fun happens.", "Так вы себя чувствуете прямо перед тем, как произойдёт что-то весёлое.", "Бұл қызықты бір нәрсе болар алдында сезінетін көңіл-күй."),
        'nervous' => C("This is how you feel before a big test or interview.", "Так вы себя чувствуете перед важным экзаменом или собеседованием.", "Бұл үлкен емтихан немесе сұхбат алдында сезінетін көңіл-күй."),
        'proud' => C("This is how you feel when you achieve something great.", "Так вы себя чувствуете, когда достигаете чего-то важного.", "Бұл үлкен жетістікке жеткенде сезінетін көңіл-күй."),
        'teacher' => C("This person helps students learn in a classroom.", "Этот человек помогает ученикам учиться в классе.", "Бұл адам сыныпта оқушыларға үйренуге көмектеседі."),
        'doctor' => C("This person helps sick people feel better.", "Этот человек помогает больным людям чувствовать себя лучше.", "Бұл адам ауру адамдарға жақсы сезінуге көмектеседі."),
        'nurse' => C("This person works in a hospital and helps doctors care for patients.", "Этот человек работает в больнице и помогает врачам ухаживать за пациентами.", "Бұл адам ауруханада жұмыс істейді және дәрігерлерге науқастарды күтуге көмектеседі."),
        'engineer' => C("This person designs and builds machines, roads, or buildings.", "Этот человек проектирует и строит машины, дороги или здания.", "Бұл адам машиналарды, жолдарды немесе ғимараттарды жобалайды және салады."),
        'farmer' => C("This person grows crops and raises animals for a living.", "Этот человек выращивает урожай и разводит животных для заработка.", "Бұл адам күнкөріс үшін дақыл өсіреді және мал бағады."),
        'driver' => C("This person controls a car, bus, or truck.", "Этот человек управляет машиной, автобусом или грузовиком.", "Бұл адам машинаны, автобусты немесе жүк көлігін басқарады."),
        'chef' => C("This person cooks food in a restaurant kitchen.", "Этот человек готовит еду на кухне ресторана.", "Бұл адам мейрамхана асханасында тамақ пісіреді."),
        'artist' => C("This person creates paintings or other beautiful works.", "Этот человек создаёт картины или другие красивые произведения.", "Бұл адам сурет немесе басқа әдемі туындылар жасайды."),
        'lawyer' => C("This person helps people with legal problems in court.", "Этот человек помогает людям с юридическими проблемами в суде.", "Бұл адам сотта адамдарға заңды мәселелерде көмектеседі."),
        'pilot' => C("This person flies an airplane.", "Этот человек управляет самолётом.", "Бұл адам ұшақты басқарады."),
        'car' => C("This vehicle has four wheels and you drive it on roads.", "У этого транспортного средства четыре колеса, и вы ездите на нём по дорогам.", "Бұл көліктің төрт дөңгелегі бар және сіз онымен жолмен жүресіз."),
        'bus' => C("This large vehicle carries many passengers around a city.", "Этот большой транспорт перевозит много пассажиров по городу.", "Бұл үлкен көлік қала бойынша көптеген жолаушыларды тасиды."),
        'train' => C("This long vehicle runs on tracks and carries many people.", "Этот длинный транспорт движется по рельсам и перевозит много людей.", "Бұл ұзын көлік рельс бойымен жүреді және көп адамды тасиды."),
        'bicycle' => C("This two-wheeled vehicle is powered by pedaling with your legs.", "Этот двухколёсный транспорт приводится в движение педалями с помощью ваших ног.", "Бұл екі дөңгелекті көлік аяғыңызбен педаль басу арқылы қозғалады."),
        'airplane' => C("This vehicle flies through the sky and carries passengers far away.", "Этот транспорт летает по небу и перевозит пассажиров далеко.", "Бұл көлік аспанмен ұшады және жолаушыларды алысқа апарады."),
        'boat' => C("This vehicle travels on water.", "Этот транспорт передвигается по воде.", "Бұл көлік су бетімен жүреді."),
        'taxi' => C("This is a car you can pay to take you somewhere.", "Это машина, за которую вы платите, чтобы вас куда-то отвезли.", "Бұл сізді бір жерге апару үшін ақы төлейтін көлік."),
        'music' => C("This is sounds arranged to be pleasant, like songs.", "Это звуки, организованные так, чтобы быть приятными, например песни.", "Бұл ән сияқты жағымды болатындай ретке келтірілген дыбыстар."),
        'dance' => C("This means moving your body to the rhythm of music.", "Это значит двигать телом в ритме музыки.", "Бұл денеңізді музыка ырғағына сай қозғау дегенді білдіреді."),
        'football' => C("This popular sport is played with a round ball and two teams.", "В этот популярный вид спорта играют круглым мячом две команды.", "Бұл танымал спорт түрінде екі команда дөңгелек допты ойнайды."),
        'swimming' => C("This activity means moving your body through water.", "Это занятие означает передвижение тела по воде.", "Бұл әрекет денеңізді су арқылы қозғау дегенді білдіреді."),
        'painting' => C("This hobby uses a brush and colors to create pictures.", "В этом хобби используют кисть и краски, чтобы создавать картины.", "Бұл хоббиде сурет салу үшін қылқалам мен бояулар қолданылады."),
        'reading' => C("This hobby means looking at words in a book to understand a story.", "Это хобби означает читать слова в книге, чтобы понять историю.", "Бұл хобби әңгімені түсіну үшін кітаптағы сөздерді оқу дегенді білдіреді."),
        'cooking' => C("This activity means preparing food to eat.", "Это занятие означает готовить еду.", "Бұл әрекет жеу үшін тамақ дайындау дегенді білдіреді."),
        'photography' => C("This hobby means taking pictures with a camera.", "Это хобби означает делать снимки с помощью камеры.", "Бұл хобби камерамен сурет түсіру дегенді білдіреді."),
        'chess' => C("This is a strategy board game played with kings and queens.", "Это настольная стратегическая игра, в которой есть короли и королевы.", "Бұл патшалар мен патшайымдар қатысатын стратегиялық үстел ойыны."),
        'camping' => C("This activity means sleeping outdoors, often in a tent.", "Это занятие означает спать на улице, часто в палатке.", "Бұл әрекет сыртта, көбіне шатырда ұйықтау дегенді білдіреді."),
        'fishing' => C("This activity means trying to catch fish from the water.", "Это занятие означает пытаться поймать рыбу из воды.", "Бұл әрекет судан балық аулауға тырысу дегенді білдіреді."),
        'hiking' => C("This activity means walking long distances in nature, often on hills.", "Это занятие означает ходить на большие расстояния на природе, часто по холмам.", "Бұл әрекет табиғатта, көбіне төбелерде ұзақ қашықтыққа жаяу жүру дегенді білдіреді."),
        'phone' => C("You use this device to call or text people.", "Вы используете это устройство, чтобы звонить или писать людям.", "Сіз адамдарға қоңырау шалу немесе хабарлама жазу үшін бұл құрылғыны пайдаланасыз."),
        'computer' => C("You use this machine to work, browse the internet, or play games.", "Вы используете эту машину для работы, интернета или игр.", "Сіз бұл құрылғыны жұмыс істеу, интернетті шолу немесе ойын ойнау үшін пайдаланасыз."),
        'internet' => C("This is the network that connects computers around the world.", "Это сеть, которая соединяет компьютеры по всему миру.", "Бұл бүкіл әлем бойынша компьютерлерді байланыстыратын желі."),
        'camera' => C("You use this device to take photos.", "Вы используете это устройство, чтобы делать фотографии.", "Сіз фотосурет түсіру үшін бұл құрылғыны пайдаланасыз."),
        'television' => C("You watch shows and movies on this device.", "Вы смотрите шоу и фильмы на этом устройстве.", "Сіз бұл құрылғыдан хабарлар мен фильмдер көресіз."),
        'password' => C("You need this secret code to log into your account.", "Вам нужен этот секретный код, чтобы войти в свой аккаунт.", "Аккаунтыңызға кіру үшін сізге осы құпия код керек."),
        'battery' => C("This device stores power for your phone or other devices.", "Это устройство хранит энергию для вашего телефона или других приборов.", "Бұл құрылғы телефоныңыз немесе басқа құрылғылар үшін қуат сақтайды."),
        'tree' => C("This tall plant has a trunk, branches, and leaves.", "У этого высокого растения есть ствол, ветви и листья.", "Бұл биік өсімдіктің діңі, бұтақтары және жапырақтары бар."),
        'flower' => C("This colorful part of a plant often smells nice.", "Эта яркая часть растения часто приятно пахнет.", "Өсімдіктің бұл түрлі-түсті бөлігі көбіне жағымды иіс шығарады."),
        'river' => C("This is a long body of water that flows to the sea.", "Это длинный водоём, который течёт к морю.", "Бұл теңізге құятын ұзын су айдыны."),
        'ocean' => C("This is a huge body of salt water.", "Это огромный водоём с солёной водой.", "Бұл тұзды судың алып айдыны."),
        'sky' => C("This is what you see above you, blue in the day and dark at night.", "Это то, что вы видите над собой, синее днём и тёмное ночью.", "Бұл сіздің үстіңізде көретін нәрсе, күндіз көк, түнде қараңғы."),
        'star' => C("This bright object appears in the night sky.", "Этот яркий объект появляется в ночном небе.", "Бұл жарқын дене түнгі аспанда пайда болады."),
        'moon' => C("This object orbits the earth and is visible at night.", "Этот объект вращается вокруг Земли и виден ночью.", "Бұл дене Жерді айналады және түнде көрінеді."),
        'sand' => C("These are the tiny grains you find on a beach.", "Это крошечные крупинки, которые вы находите на пляже.", "Бұл жағажайдан табатын ұсақ түйіршіктер."),
        'expensive' => C("This word describes something that costs a lot of money.", "Это слово описывает то, что стоит много денег.", "Бұл сөз көп ақшаға тұратын нәрсені сипаттайды."),
        'cheap' => C("This word describes something that costs very little money.", "Это слово описывает то, что стоит очень мало денег.", "Бұл сөз аз ақшаға тұратын нәрсені сипаттайды."),
        'beautiful' => C("This word describes something that is very pleasant to look at.", "Это слово описывает то, на что очень приятно смотреть.", "Бұл сөз қарауға өте жағымды нәрсені сипаттайды."),
        'delicious' => C("This word describes food that tastes very good.", "Это слово описывает еду, которая очень вкусная.", "Бұл сөз дәмі өте жақсы тағамды сипаттайды."),
        'dangerous' => C("This word describes something that could hurt you.", "Это слово описывает то, что может вам навредить.", "Бұл сөз сізге зиян тигізуі мүмкін нәрсені сипаттайды."),
        'healthy' => C("This word describes something good for your body.", "Это слово описывает то, что полезно для вашего тела.", "Бұл сөз денеңізге пайдалы нәрсені сипаттайды."),
        'crowded' => C("This word describes a place that is full of people.", "Это слово описывает место, полное людей.", "Бұл сөз адамға толы орынды сипаттайды."),
        'quiet' => C("This word describes a place with very little noise.", "Это слово описывает место с очень небольшим шумом.", "Бұл сөз шуы өте аз орынды сипаттайды."),
        'strong' => C("This word describes someone with a lot of physical power.", "Это слово описывает того, у кого много физической силы.", "Бұл сөз дене күші мол адамды сипаттайды."),
        'travel' => C("This means going to different places, often far from home.", "Это значит ездить в разные места, часто далеко от дома.", "Бұл көбіне үйден алыс, әртүрлі жерлерге бару дегенді білдіреді."),
        'study' => C("This means spending time learning something.", "Это значит проводить время, изучая что-то.", "Бұл бір нәрсені үйренуге уақыт жұмсау дегенді білдіреді."),
        'clean' => C("This means making something free of dirt.", "Это значит делать что-то свободным от грязи.", "Бұл бір нәрсені кірден тазарту дегенді білдіреді."),
        'drive' => C("This means controlling a car to move it.", "Это значит управлять машиной, чтобы она двигалась.", "Бұл машинаны қозғалту үшін басқару дегенді білдіреді."),
        'swim' => C("This means moving your body through water.", "Это значит двигать телом в воде.", "Бұл денеңізді су арқылы қозғау дегенді білдіреді."),
        'sing' => C("This means using your voice to make music.", "Это значит использовать свой голос, чтобы создавать музыку.", "Бұл музыка жасау үшін дауысыңызды пайдалану дегенді білдіреді."),
        'listen' => C("This means paying close attention with your ears.", "Это значит внимательно слушать ушами.", "Бұл құлағыңызбен мұқият тыңдау дегенді білдіреді."),
        'smile' => C("This means turning up the corners of your mouth to show happiness.", "Это значит поднимать уголки рта, чтобы показать радость.", "Бұл қуанышты білдіру үшін ауыз бұрышын жоғары көтеру дегенді білдіреді."),
        'laugh' => C("This means making a sound when something is funny.", "Это значит издавать звук, когда что-то смешно.", "Бұл бір нәрсе күлкілі болғанда дыбыс шығару дегенді білдіреді."),
        'help' => C("This means giving support to someone who needs it.", "Это значит оказывать поддержку тому, кто в ней нуждается.", "Бұл көмек қажет ететін адамға қолдау көрсету дегенді білдіреді."),
        'learn' => C("This means gaining new knowledge or a skill.", "Это значит получать новые знания или навык.", "Бұл жаңа білім немесе дағды алу дегенді білдіреді."),
        'teach' => C("This means helping someone else learn something.", "Это значит помогать кому-то другому чему-то научиться.", "Бұл басқа адамға бір нәрсені үйренуге көмектесу дегенді білдіреді."),
        'build' => C("This means putting materials together to make something new.", "Это значит соединять материалы, чтобы создать что-то новое.", "Бұл жаңа нәрсе жасау үшін материалдарды біріктіру дегенді білдіреді."),
    ];
}

// Moderate word bank for Pre-Intermediate/Intermediate: everyday and school/
// classroom vocabulary a real student at that level actually knows (student,
// homework, knowledge, borrow, exam...), not abstract idiom-level words. A
// small step up from the beginner bank, not a leap into advanced vocabulary.
function build_hangman_clues_moderate(): array {
    return [
        'student' => C("This is a person who is studying at a school, college, or university.", "Это человек, который учится в школе, колледже или университете.", "Бұл мектепте, колледжде немесе университетте оқитын адам."),
        'classmate' => C("This is a person who is in the same class as you at school.", "Это человек, который учится в одном классе с вами.", "Бұл сізбен бір сыныпта оқитын адам."),
        'classroom' => C("This is the room where students sit and learn with their teacher.", "Это комната, где ученики сидят и учатся со своим учителем.", "Бұл оқушылар мұғаліммен бірге отырып білім алатын бөлме."),
        'homework' => C("This is the school work that students do at home, not in class.", "Это школьное задание, которое ученики делают дома, а не в классе.", "Бұл оқушылардың сыныпта емес, үйде орындайтын мектеп тапсырмасы."),
        'exam' => C("This is a test that checks how much a student has learned.", "Это проверка, которая показывает, сколько ученик выучил.", "Бұл оқушының қаншалықты үйренгенін тексеретін сынақ."),
        'subject' => C("Math, history, and English are all examples of this at school.", "Математика, история и английский язык — это примеры этого в школе.", "Математика, тарих және ағылшын тілі — мектептегі осының мысалдары."),
        'education' => C("Going to school and learning new things for years is called this.", "Ходить в школу и годами учиться новому называют этим словом.", "Мектепке барып, жылдар бойы жаңа нәрселерді үйрену осылай аталады."),
        'knowledge' => C("The facts and information you know after studying and reading are called this.", "Факты и информация, которые вы знаете после учёбы и чтения, называются этим словом.", "Оқу мен білім алудан кейін білетін деректер мен ақпарат осылай аталады."),
        'dictionary' => C("You open this book when you don't know the meaning of a word.", "Вы открываете эту книгу, когда не знаете значения слова.", "Сөздің мағынасын білмегенде осы кітапты ашасыз."),
        'grammar' => C("The rules for putting words together correctly in a sentence are called this.", "Правила правильного соединения слов в предложении называются этим словом.", "Сөздерді сөйлемде дұрыс құрастыру ережелері осылай аталады."),
        'vocabulary' => C("All the words that you know in a language are called this.", "Все слова, которые вы знаете на каком-либо языке, называются этим словом.", "Белгілі бір тілде білетін барлық сөздеріңіз осылай аталады."),
        'explain' => C("A teacher does this when they make a difficult idea easy to understand.", "Учитель делает это, когда делает сложную идею понятной.", "Мұғалім қиын идеяны түсінікті ететінде осыны істейді."),
        'practice' => C("Doing something again and again to get better at it is called this.", "Делать что-то снова и снова, чтобы стать лучше в этом, называется этим словом.", "Бір нәрсені жақсы меңгеру үшін оны қайта-қайта жасау осылай аталады."),
        'improve' => C("When your English gets better than before, this is what happened.", "Когда ваш английский становится лучше, чем раньше, значит, произошло это.", "Ағылшын тіліңіз бұрынғыдан жақсарғанда, дәл осы болды дегенді білдіреді."),
        'remember' => C("You do this when information stays in your mind and you don't forget it.", "Вы делаете это, когда информация остаётся в вашей памяти и вы её не забываете.", "Ақпарат есіңізде қалып, оны ұмытпағанда, сіз осыны істеп жатырсыз."),
        'forget' => C("This is the opposite of remembering - the information just disappears from your mind.", "Это противоположность запоминанию — информация просто исчезает из памяти.", "Бұл есте сақтаудың қарама-қарсысы — ақпарат жадыдан жай ғана жоғалады."),
        'translate' => C("You do this when you change words from one language into another.", "Вы делаете это, когда меняете слова с одного языка на другой.", "Сөздерді бір тілден екінші тілге ауыстырғанда, сіз осыны істейсіз."),
        'pronounce' => C("You do this with your mouth when you say a word out loud correctly.", "Вы делаете это ртом, когда правильно произносите слово вслух.", "Сөзді дұрыс дауыстап айтқанда, сіз аузыңызбен осыны істейсіз."),
        'describe' => C("You do this when you use words to tell someone what a person or place is like.", "Вы делаете это, когда словами рассказываете, каким является человек или место.", "Адамның немесе орынның қандай екенін сөзбен айтқанда, сіз осыны істейсіз."),
        'compare' => C("You do this when you look at two things to see how they are similar or different.", "Вы делаете это, когда смотрите на две вещи, чтобы увидеть их сходства и различия.", "Екі затты олардың ұқсастығы мен айырмашылығын білу үшін қарағанда, сіз осыны істейсіз."),
        'discuss' => C("A group of students does this when they talk together about a topic.", "Группа учеников делает это, когда вместе разговаривает на какую-то тему.", "Оқушылар тобы бір тақырыпты бірге талқылағанда осыны істейді."),
        'agree' => C("You do this when you have the same opinion as someone else.", "Вы делаете это, когда у вас такое же мнение, как у кого-то другого.", "Басқа біреумен бірдей пікірде болғанда, сіз осыны істейсіз."),
        'disagree' => C("This is the opposite of agreeing - you have a different opinion from someone.", "Это противоположность согласию — у вас другое мнение, чем у кого-то.", "Бұл келісудің қарама-қарсысы — сіздің біреумен пікіріңіз әртүрлі."),
        'borrow' => C("You do this when you take something, like a pen, planning to give it back later.", "Вы делаете это, когда берёте что-то, например ручку, планируя вернуть позже.", "Қалам сияқты затты кейін қайтаруды жоспарлап алғанда, сіз осыны істейсіз."),
        'uniform' => C("Many students wear the same special clothes to school - these clothes are called this.", "Многие ученики носят одинаковую специальную одежду в школу — эту одежду называют этим словом.", "Көптеген оқушылар мектепке бірдей арнайы киім киеді — бұл киім осылай аталады."),
        'playground' => C("This is the outdoor area at a school where children play during break.", "Это площадка на улице школы, где дети играют на перемене.", "Бұл мектептің сыртындағы аумақ, балалар үзілісте сонда ойнайды."),
        'holiday' => C("This is a day or period when school and work are closed and people rest.", "Это день или период, когда школа и работа закрыты, и люди отдыхают.", "Бұл мектеп пен жұмыс жабық болатын, адамдар демалатын күн немесе кезең."),
        'project' => C("Students often work in a group for weeks to finish this big school task.", "Ученики часто работают в группе несколько недель, чтобы закончить это большое школьное задание.", "Оқушылар осы үлкен мектеп тапсырмасын аяқтау үшін бірнеше апта топпен жұмыс істейді."),
        'timetable' => C("This shows students which subject they have in each lesson, on each day of the week.", "Это показывает ученикам, какой предмет у них на каждом уроке в каждый день недели.", "Бұл оқушыларға аптаның әр күніндегі әр сабақта қандай пән бар екенін көрсетеді."),
        'headphones' => C("You put these over or in your ears to listen to music without others hearing it.", "Вы надеваете это на уши или в уши, чтобы слушать музыку так, чтобы другие не слышали.", "Музыканы басқалар естімейтіндей тыңдау үшін мұны құлаққа саласыз."),
        'laptop' => C("This is a small computer you can close and carry around with you.", "Это маленький компьютер, который можно закрыть и носить с собой.", "Бұл жабуға және өзіңізбен алып жүруге болатын кішкентай компьютер."),
        'calculator' => C("You use this small device to quickly add, subtract, or multiply numbers.", "Вы используете это маленькое устройство, чтобы быстро складывать, вычитать или умножать числа.", "Сандарды тез қосу, азайту немесе көбейту үшін осы кішкентай құрылғыны пайдаланасыз."),
        'printer' => C("This machine puts the words from your computer screen onto paper.", "Эта машина переносит слова с экрана компьютера на бумагу.", "Бұл құрылғы компьютер экранындағы сөздерді қағазға басып шығарады."),
        'notebook' => C("Students write their class notes in this small book.", "Ученики записывают свои заметки с уроков в эту маленькую книгу.", "Оқушылар сабақ жазбаларын осы кішкентай кітапшаға жазады."),
        'textbook' => C("This is the main book a class uses to study a subject all year.", "Это основная книга, которую класс использует для изучения предмета весь год.", "Бұл сынып пәнді бүкіл жыл бойы оқу үшін пайдаланатын негізгі кітап."),
        'blackboard' => C("The teacher writes with chalk on this dark board at the front of the classroom.", "Учитель пишет мелом на этой тёмной доске перед классом.", "Мұғалім сыныптың алдындағы осы қара тақтаға бормен жазады."),
        'eraser' => C("You use this small object to remove a pencil mark or chalk from a board.", "Вы используете этот маленький предмет, чтобы стереть след от карандаша или мела с доски.", "Қарындаш ізін немесе тақтадан борды өшіру үшін осы кішкентай затты пайдаланасыз."),
        'backpack' => C("Students carry their books and notebooks to school in this bag on their back.", "Ученики носят книги и тетради в школу в этой сумке на спине.", "Оқушылар кітаптары мен дәптерлерін мектепке арқасындағы осы сөмкеде алып барады."),
        'canteen' => C("This is the room at school where students go to eat their lunch.", "Это комната в школе, куда ученики идут обедать.", "Бұл мектептегі оқушылар түскі ас ішуге баратын бөлме."),
        'graduate' => C("You do this when you successfully finish your studies at a school or university.", "Вы делаете это, когда успешно заканчиваете учёбу в школе или университете.", "Мектепте немесе университетте оқуды сәтті аяқтағанда, сіз осыны істейсіз."),
        'journey' => C("A long trip from one place to another, especially by land, is called this.", "Долгая поездка из одного места в другое, особенно по суше, называется этим словом.", "Бір жерден екінші жерге, әсіресе құрлықпен жасалатын ұзақ сапар осылай аталады."),
        'traffic' => C("This word describes all the cars and buses moving along the road at the same time.", "Это слово описывает все машины и автобусы, движущиеся по дороге одновременно.", "Бұл сөз жолмен бір мезгілде қозғалатын барлық көліктер мен автобустарды сипаттайды."),
        'appointment' => C("You make this when you arrange a specific time to meet a doctor or dentist.", "Вы делаете это, когда договариваетесь о конкретном времени встречи с врачом или стоматологом.", "Дәрігермен белгілі бір уақытта кездесуді келіскенде, сіз осыны жасайсыз."),
        'invitation' => C("You send this to a friend to ask them to come to your party.", "Вы отправляете это другу, чтобы пригласить его на свой праздник.", "Досыңызды мерекеңізге шақыру үшін оған осыны жібересіз."),
        'celebration' => C("A birthday party or a wedding is an example of this happy event.", "День рождения или свадьба — это пример такого радостного события.", "Туған күн немесе үйлену тойы — осы қуанышты оқиғаның мысалы."),
        'volunteer' => C("This person helps other people or works for a good cause without being paid.", "Этот человек помогает другим людям или работает на благое дело бесплатно.", "Бұл адам басқа адамдарға көмектеседі немесе ақысыз игі іс үшін жұмыс істейді."),
        'community' => C("The group of people who live in the same area or share the same interests is called this.", "Группа людей, живущих в одном районе или имеющих общие интересы, называется этим словом.", "Бір аймақта тұратын немесе ортақ қызығушылығы бар адамдар тобы осылай аталады."),
        'festival' => C("This is a special day or days when a town celebrates with music, food, and events.", "Это особый день или дни, когда город празднует с музыкой, едой и мероприятиями.", "Бұл қала музыка, тағам және іс-шаралармен тойлайтын арнайы күн немесе күндер."),
        'custom' => C("A traditional way of doing something in a certain country or family is called this.", "Традиционный способ делать что-то в определённой стране или семье называется этим словом.", "Белгілі бір елде немесе отбасында бір нәрсені жасаудың дәстүрлі тәсілі осылай аталады."),
        'recipe' => C("You follow this list of steps and foods when you want to cook a dish.", "Вы следуете этому списку шагов и продуктов, когда хотите приготовить блюдо.", "Тағам дайындағыңыз келгенде осы қадамдар мен өнімдер тізімін ұстанасыз."),
        'ingredient' => C("Flour, sugar, and eggs are all examples of this - something you need to cook a dish.", "Мука, сахар и яйца — это примеры того, что нужно для приготовления блюда.", "Ұн, қант және жұмыртқа — тағам дайындау үшін керек нәрсенің мысалдары."),
        'exercise' => C("Running, swimming, or lifting weights to keep your body healthy is called this.", "Бег, плавание или поднятие тяжестей для поддержания здоровья тела называется этим словом.", "Денсаулықты сақтау үшін жүгіру, жүзу немесе ауыртпалық көтеру осылай аталады."),
        'habit' => C("Something you do so often that you almost do it without thinking is called this.", "То, что вы делаете так часто, что почти не задумываетесь об этом, называется этим словом.", "Сіз соншалықты жиі жасайтын, тіпті ойланбай жасайтын нәрсе осылай аталады."),
        'routine' => C("The usual set of things you do every day, in the same order, is called this.", "Обычный набор дел, которые вы делаете каждый день в одном и том же порядке, называется этим словом.", "Сіз күн сайын бірдей ретпен жасайтын әдеттегі істер жиынтығы осылай аталады."),
        'instrument' => C("A guitar, a piano, and a violin are all examples of this - something used to make music.", "Гитара, пианино и скрипка — это примеры того, на чём играют музыку.", "Гитара, пианино және скрипка — музыка ойнау үшін қолданылатын заттың мысалдары."),
        'exhibition' => C("This is an event where paintings or interesting objects are shown to the public.", "Это мероприятие, где картины или интересные предметы показывают публике.", "Бұл суреттер немесе қызықты заттар көпшілікке көрсетілетін іс-шара."),
        'ticket' => C("You must buy this small piece of paper before you can enter a cinema or ride a train.", "Вы должны купить этот маленький кусочек бумаги, прежде чем войти в кино или сесть на поезд.", "Кинотеатрға кіру немесе пойызға отыру алдында осы кішкентай қағазды сатып алуыңыз керек."),
        'passport' => C("You must show this official document with your photo when you travel to another country.", "Вы должны показать этот официальный документ с вашей фотографией, когда едете в другую страну.", "Басқа елге барғанда фотосуретіңіз бар осы ресми құжатты көрсетуіңіз керек."),
        'suitcase' => C("You pack your clothes into this bag before you go on a trip.", "Вы складываете одежду в эту сумку перед поездкой.", "Сапарға шығар алдында киімдеріңізді осы сөмкеге саласыз."),
        'luggage' => C("This word describes all the bags and suitcases you take with you when you travel.", "Это слово описывает все сумки и чемоданы, которые вы берёте с собой в поездку.", "Бұл сөз сапарға алып жүретін барлық сөмке мен чемоданды сипаттайды."),
        'direction' => C("North, south, east, and west are all examples of this.", "Север, юг, восток и запад — это примеры этого.", "Солтүстік, оңтүстік, шығыс және батыс — осының мысалдары."),
        'compass' => C("This small tool with a needle always points north and helps you find your way.", "Этот маленький инструмент со стрелкой всегда показывает на север и помогает найти дорогу.", "Инесі бар осы кішкентай құрал әрқашан солтүстікті көрсетіп, жол табуға көмектеседі."),
        'accident' => C("A car crash that nobody planned to happen is an example of this.", "Авария на дороге, которую никто не планировал, — это пример этого.", "Ешкім жоспарламаған көлік апаты осының мысалы."),
        'emergency' => C("A fire or a serious accident that needs help right away is called this.", "Пожар или серьёзная авария, требующая немедленной помощи, называется этим словом.", "Дереу көмек қажет ететін өрт немесе ауыр апат осылай аталады."),
        'ambulance' => C("This special vehicle rushes sick or hurt people quickly to the hospital.", "Этот специальный транспорт быстро везёт больных или раненых людей в больницу.", "Бұл арнайы көлік ауру немесе жарақат алған адамдарды ауруханаға жедел жеткізеді."),
        'pharmacy' => C("This is the shop where you go to buy medicine.", "Это магазин, куда вы идёте, чтобы купить лекарства.", "Бұл дәрі-дәрмек сатып алуға баратын дүкен."),
        'medicine' => C("A doctor gives you this to help you feel better when you are sick.", "Врач даёт вам это, чтобы вам стало лучше, когда вы больны.", "Ауырғанда өзіңізді жақсы сезіну үшін дәрігер сізге осыны береді."),
        'symptom' => C("A headache or a fever is a sign that shows you might be sick - this is what such a sign is called.", "Головная боль или температура — это признак того, что вы можете быть больны, и такой признак называется этим словом.", "Бас ауруы немесе температура сіздің ауру екеніңізді көрсететін белгі, мұндай белгі осылай аталады."),
        'treatment' => C("The medicine and care a doctor gives you to make an illness go away is called this.", "Лекарства и уход, которые врач вам назначает, чтобы вылечить болезнь, называются этим словом.", "Дәрігердің ауруды жою үшін берген дәрісі мен күтімі осылай аталады."),
        'rescue' => C("Firefighters do this when they save a person from a dangerous situation, like a fire.", "Пожарные делают это, когда спасают человека из опасной ситуации, например из огня.", "Өрт сөндірушілер адамды өрт сияқты қауіпті жағдайдан құтқарғанда осыны істейді."),
        'pollution' => C("Dirty smoke from factories and cars making the air or water unhealthy is called this.", "Грязный дым от заводов и машин, делающий воздух или воду вредными, называется этим словом.", "Зауыттар мен көліктердің ауаны немесе суды зиянды ететін лас түтіні осылай аталады."),
        'recycle' => C("Putting plastic bottles in a special bin so they can be used again is this.", "Класть пластиковые бутылки в специальный контейнер, чтобы их использовали снова, — это оно.", "Пластик бөтелкелерді қайта пайдалану үшін арнайы себетке салу осылай аталады."),
        'electricity' => C("This kind of power turns on your lights and makes your phone charge.", "Этот вид энергии включает свет и заряжает ваш телефон.", "Бұл қуат түрі жарықты жағады және телефоныңызды зарядтайды."),
        'signal' => C("Your phone needs this invisible connection to make calls or use the internet.", "Вашему телефону нужна эта невидимая связь, чтобы звонить или пользоваться интернетом.", "Телефоныңызға қоңырау шалу немесе интернетті пайдалану үшін осы көрінбейтін байланыс керек."),
        'connection' => C("You need a good one of these to your Wi-Fi if you want videos to load quickly.", "Вам нужна хорошая такая связь с Wi-Fi, чтобы видео быстро загружалось.", "Бейнелердің тез жүктелуі үшін Wi-Fi-ге жақсы осындай байланыс керек."),
        'software' => C("Apps and programs that run on a computer or phone are called this, unlike the physical machine itself.", "Приложения и программы, которые работают на компьютере или телефоне, называются этим словом, в отличие от самого устройства.", "Компьютерде немесе телефонда жұмыс істейтін қосымшалар мен бағдарламалар осылай аталады."),
        'keyboard' => C("You press the letters on this to type words on a computer.", "Вы нажимаете буквы на этом, чтобы печатать слова на компьютере.", "Компьютерде сөздерді теру үшін мұның әріптерін басасыз."),
        'screen' => C("You look at this flat part of your phone or computer to see pictures and words.", "Вы смотрите на эту плоскую часть телефона или компьютера, чтобы видеть картинки и слова.", "Суреттер мен сөздерді көру үшін телефон немесе компьютердің осы жалпақ бөлігіне қарайсыз."),
        'newspaper' => C("People used to read the news of the day printed on large sheets of paper like this.", "Раньше люди читали новости дня, напечатанные на больших листах бумаги, как этот.", "Бұрын адамдар күннің жаңалықтарын осындай үлкен қағаз парақтарынан оқитын."),
        'magazine' => C("This is a thin book with colorful pictures, printed every week or month about a topic like fashion or cars.", "Это тонкая книга с яркими картинками, которую печатают каждую неделю или месяц на такую тему, как мода или машины.", "Бұл сән немесе көлік сияқты тақырыпта апта немесе ай сайын басылатын түрлі-түсті суреттері бар жұқа кітап."),
        'advertisement' => C("A company pays to show this on TV or online to convince you to buy their product.", "Компания платит, чтобы показать это по телевизору или в интернете, чтобы убедить вас купить их товар.", "Компания өз тауарын сатып алуға көндіру үшін теледидардан немесе интернеттен осыны көрсетуге ақы төлейді."),
        'customer' => C("A shop calls you this word when you come in to buy something.", "В магазине вас называют этим словом, когда вы приходите что-то купить.", "Дүкенде бір нәрсе сатып алуға келгенде сізді осылай атайды."),
        'discount' => C("When a shop lowers its price for a short time, this is what they are giving you.", "Когда магазин на короткое время снижает цену, вам дают именно это.", "Дүкен қысқа уақытқа бағаны төмендеткенде, сізге дәл осыны береді."),
        'receipt' => C("The shop gives you this small piece of paper as proof after you pay for something.", "Магазин даёт вам этот маленький листок бумаги как доказательство после того, как вы что-то оплатили.", "Бір нәрсе үшін төлегеннен кейін дүкен сізге дәлел ретінде осы кішкентай қағазды береді."),
        'cashier' => C("This person in a shop takes your money and gives you your receipt.", "Этот человек в магазине принимает ваши деньги и даёт вам чек.", "Дүкендегі бұл адам ақшаңызды алып, чегіңізді береді."),
        'delivery' => C("When a company brings your online order right to your front door, this is what happened.", "Когда компания приносит ваш заказ из интернета прямо к вашей двери, значит, произошло это.", "Компания интернеттен тапсырысыңызды тікелей есігіңізге әкелгенде, дәл осы болды дегенді білдіреді."),
        'package' => C("This is a box or wrapped item that arrives at your door after you order something online.", "Это коробка или упакованный предмет, который приходит к вашей двери после того, как вы что-то заказали в интернете.", "Интернеттен бір нәрсе тапсырыс бергеннен кейін есігіңізге келетін қорап немесе оралған зат осы."),
        'quantity' => C("This word describes how much or how many of something there is - a number, not a quality.", "Это слово описывает, сколько чего-то есть — это число, а не качество.", "Бұл сөз бір заттың қаншалықты көп немесе аз екенін сипаттайды — бұл сан, сапа емес."),
        'quality' => C("This word describes how good or bad something is, not how much of it there is.", "Это слово описывает, насколько хорошим или плохим является что-то, а не то, сколько его.", "Бұл сөз бір заттың қаншалықты жақсы немесе жаман екенін сипаттайды, оның мөлшерін емес."),
    ];
}

// Assigns each lesson a deterministic, non-overlapping slice of 5 words from
// its level's bank, based on the lesson's rank among all lessons that share
// that bank. This is what actually guarantees lessons don't repeat the same
// hangman words (as opposed to the old approach: an independent random draw
// per lesson, which collides constantly once two lessons share a bank of
// only a few hundred words). Repeats only start reappearing once a level
// group has more lessons than bank_size/5 - at that point the sequence wraps
// and starts over from the beginning, rather than colliding unpredictably.
function extract_hangman_words(int $lessonId, string $level, array $vocabWords): array {
    $levelGroup = in_array($level, ['pre-intermediate', 'intermediate'], true)
        ? ['pre-intermediate', 'intermediate']
        : ['beginner', 'elementary'];
    $clues = $levelGroup[0] === 'pre-intermediate'
        ? build_hangman_clues_moderate()
        : build_hangman_clues();

    $bankWords = array_keys($clues);
    mt_srand(crc32(implode(',', $levelGroup)));
    shuffle($bankWords);
    $n = count($bankWords);

    $placeholders = implode(',', array_fill(0, count($levelGroup), '?'));
    $stmt = db()->prepare("SELECT id FROM lessons WHERE level IN ($placeholders) ORDER BY id");
    $stmt->execute($levelGroup);
    $orderedIds = array_column($stmt->fetchAll(), 'id');
    $rank = array_search($lessonId, $orderedIds, true);
    if ($rank === false) $rank = 0;

    $vocabLower = array_flip(array_map('mb_strtolower', $vocabWords));
    $result = [];
    $start = ($rank * 5) % $n;
    for ($i = 0; $i < $n && count($result) < 5; $i++) {
        $word = $bankWords[($start + $i) % $n];
        if (isset($vocabLower[$word])) continue;
        $result[] = ['word' => $word, 'clue' => $clues[$word]];
    }
    return $result;
}
