<?php
declare(strict_types=1);

require_once __DIR__ . '/db.php';

// Trilingual hint. Hints go from vague/riddle-like to more specific -
// nothing here is a plain dictionary definition like the Hangman clues.
function WH(string $en, string $ru, string $kz): array { return ['en' => $en, 'ru' => $ru, 'kz' => $kz]; }
function WW(string $word, array $h1, array $h2, array $h3): array { return ['word' => $word, 'hints' => [$h1, $h2, $h3]]; }

function build_whoami_bank(string $level): array {
    if ($level === 'elementary') {
        return [
            WW('compass',
                WH("I never get lost, no matter where you take me.", "Я никогда не теряюсь, куда бы ты меня ни взял.", "Мені қайда алып барсаң да, мен ешқашан адаспаймын."),
                WH("My little arrow always points to the same direction, no matter what.", "Моя маленькая стрелка всегда указывает в одном и том же направлении, что бы ни случилось.", "Менің кішкентай көрсеткішім не болса да әрқашан бір бағытты көрсетеді."),
                WH("Sailors and hikers trust me before they trust a map.", "Моряки и туристы доверяют мне раньше, чем карте.", "Теңізшілер мен туристер картаға сенгенше маған сенеді.")),
            WW('telescope',
                WH("I make faraway things feel like they're right beside you.", "Я делаю так, что далёкие вещи кажутся совсем рядом с тобой.", "Мен алыстағы заттарды дәл жаныңдағыдай сезіндіремін."),
                WH("Scientists point me at the sky to study stars no eye can see alone.", "Учёные направляют меня в небо, чтобы изучать звёзды, которые не видно простым глазом.", "Ғалымдар жай көзбен көрінбейтін жұлдыздарды зерттеу үшін мені аспанға бағыттайды."),
                WH("The more powerful I am, the deeper into space I can see.", "Чем я мощнее, тем глубже в космос я могу заглянуть.", "Мен неғұрлым қуатты болсам, соғұрлым ғарышты тереңірек көре аламын.")),
            WW('thermometer',
                WH("People check on me when they're not feeling well.", "Люди обращаются ко мне, когда плохо себя чувствуют.", "Адамдар өздерін жаман сезінгенде маған қарайды."),
                WH("I can tell you if it's freezing or boiling, just by looking at me.", "Я могу сказать тебе, холодно или жарко, стоит только на меня взглянуть.", "Маған қарау арқылы суық немесе ыстық екенін біле аласың."),
                WH("A doctor might put me under your tongue or against your forehead.", "Врач может положить меня тебе под язык или приложить ко лбу.", "Дәрігер мені тіліңнің астына немесе маңдайыңа қоюы мүмкін.")),
            WW('lighthouse',
                WH("I stand alone by the water, watching over travelers I'll never meet.", "Я стою одиноко у воды, наблюдая за путешественниками, которых никогда не встречу.", "Мен судың жағасында жалғыз тұрып, ешқашан кездеспейтін саяхатшыларды бақылаймын."),
                WH("My light spins around all night so no one crashes into the rocks.", "Мой свет кружится всю ночь, чтобы никто не разбился о скалы.", "Ешкім жартастарға соқтығыспас үшін менің жарығым түні бойы айналады."),
                WH("Ships far out at sea search for my beam during a storm.", "Корабли далеко в море ищут мой луч во время шторма.", "Теңіздегі алыс кемелер дауыл кезінде менің сәулемді іздейді.")),
            WW('waterfall',
                WH("I'm always falling, but I never seem to hit the ground for good.", "Я всегда падаю, но, кажется, никогда не падаю окончательно.", "Мен әрқашан құлап жатырмын, бірақ ешқашан толықтай құлап бітпейтін сияқтымын."),
                WH("You can hear my roar long before you ever see me.", "Ты услышишь мой рёв задолго до того, как увидишь меня.", "Сен мені көрмей тұрып-ақ, менің гуілімді естисің."),
                WH("Rivers jump off a cliff and become me.", "Реки прыгают со скалы и становятся мной.", "Өзендер жардан секіріп, мен болып шығады.")),
            WW('glacier',
                WH("I move so slowly that you'd never notice me traveling.", "Я двигаюсь так медленно, что ты никогда не заметишь моего движения.", "Мен соншалықты баяу қозғаламын, сен менің жылжуымды ешқашан байқамайсың."),
                WH("I've been frozen for so long, some of my ice is older than any person alive.", "Я заморожен так давно, что часть моего льда старше любого живого человека.", "Мен сонша ұзақ уақыт мұздап жатырмын, мұзымның кейбір бөлігі кез келген тірі адамнан үлкен."),
                WH("Scientists worry that I'm shrinking faster every year because of warming.", "Учёные беспокоятся, что из-за потепления я таю всё быстрее каждый год.", "Ғалымдар жылынудың салдарынан мен жыл сайын жылдамырақ кішірейіп жатырмын деп алаңдайды.")),
            WW('avalanche',
                WH("I start as one small slip, high on a mountain.", "Я начинаюсь с одного маленького сдвига высоко в горах.", "Мен тау басында бір кішкентай жылжудан басталамын."),
                WH("By the time I reach the bottom, nothing can stop me.", "К тому времени, как я достигаю подножия, меня уже не остановить.", "Мен етекке жеткенше, мені ешкім тоқтата алмайды."),
                WH("Skiers watch the slopes nervously, hoping I stay asleep.", "Лыжники нервно смотрят на склоны, надеясь, что я не проснусь.", "Шаңғышылар беткейге алаңдап қарайды, мен ұйықтап жатсам екен деп.")),
            WW('tornado',
                WH("I spin so fast, I can lift a house off the ground.", "Я кручусь так быстро, что могу поднять дом с земли.", "Мен соншалықты жылдам айналамын, үйді жерден көтере аламын."),
                WH("Farmers in flat, wide country fear my visits most.", "Фермеры на равнинах боятся моих визитов больше всего.", "Тегіс жазық жердегі диқандар менің келуімнен ең көп қорқады."),
                WH("I touch down from a dark cloud, spinning like a top.", "Я спускаюсь из тёмной тучи, кружась, как волчок.", "Мен қара бұлттан қоба сияқты айналып түсемін.")),
            WW('hurricane',
                WH("I'm born warm, over open ocean water.", "Я рождаюсь тёплой, над открытой водой океана.", "Мен мұхиттың ашық суының үстінде жылы болып тумын."),
                WH("I have a strangely calm eye right in my center.", "У меня в самом центре странно спокойный глаз.", "Менің дәл ортамда таңғаларлықтай тыныш көзім бар."),
                WH("Coastal towns board up their windows when I'm coming.", "Прибрежные города заколачивают окна, когда я приближаюсь.", "Мен келе жатқанда жағалаудағы қалалар терезелерін тақтаймен жабады.")),
            WW('earthquake',
                WH("You never see me coming - I strike without warning.", "Ты никогда не увидишь, как я приближаюсь — я бью без предупреждения.", "Сен менің келгенімді ешқашан алдын ала көрмейсің — мен ескертусіз соғамын."),
                WH("Deep underground, two pieces of the Earth suddenly slip.", "Глубоко под землёй два куска Земли вдруг сдвигаются.", "Жердің тереңінде екі бөлік кенеттен жылжиды."),
                WH("Buildings shake and car alarms go off the moment I arrive.", "Здания трясутся, а автомобильные сигнализации срабатывают в момент моего прихода.", "Мен келген сәтте ғимараттар діріл, көлік дабылдары шырылдайды.")),
            WW('desert',
                WH("Water is the rarest gift you'll find in me.", "Вода — самый редкий подарок, который ты найдёшь во мне.", "Су — менен табатын ең сирек сыйың."),
                WH("By day I burn, by night I freeze.", "Днём я обжигаю, ночью я замерзаю.", "Күндіз мен қыздырамын, түнде қатамын."),
                WH("Camels and cactuses call my sand their home.", "Верблюды и кактусы называют мой песок своим домом.", "Түйелер мен кактустар менің құмымды үй дейді.")),
            WW('oasis',
                WH("In the middle of endless sand, I'm a small green surprise.", "Посреди бескрайнего песка я маленький зелёный сюрприз.", "Шексіз құмның ортасында мен кішкентай жасыл тосынсыйымын."),
                WH("Travelers cross miles of desert just to find me.", "Путники пересекают мили пустыни только для того, чтобы найти меня.", "Саяхатшылар мені табу үшін шөлдің мильдерін кесіп өтеді."),
                WH("Wherever I appear, water and palm trees follow.", "Где бы я ни появился, за мной следуют вода и пальмы.", "Мен қай жерде пайда болсам да, су мен пальмалар ілеседі.")),
            WW('canyon',
                WH("A river carved me out over millions of years.", "Река вырезала меня за миллионы лет.", "Мені өзен миллиондаған жыл бойы қашап жасады."),
                WH("Shout into me, and I'll shout right back.", "Крикни в меня, и я крикну в ответ.", "Маған айқайлап қара, мен саған қайта айқайлаймын."),
                WH("My walls of rock can stretch deeper than a skyscraper is tall.", "Мои каменные стены могут уходить глубже, чем высота небоскрёба.", "Тас қабырғаларым аспан асты ғимараттан да тереңірек созылуы мүмкін.")),
            WW('cave',
                WH("Step inside me, and the sunlight disappears completely.", "Войди внутрь меня, и солнечный свет полностью исчезнет.", "Менің ішіме кірсең, күн сәулесі мүлдем жоғалады."),
                WH("Bats often choose me as their daytime home.", "Летучие мыши часто выбирают меня своим домом на день.", "Жарқанаттар мені көбіне күндізгі үйі етіп таңдайды."),
                WH("Ancient humans once painted pictures on my walls.", "Древние люди когда-то рисовали картины на моих стенах.", "Ежелгі адамдар бір кездері менің қабырғама сурет салған.")),
            WW('island',
                WH("Water surrounds me on every single side.", "Вода окружает меня со всех сторон.", "Су мені барлық жағынан қоршап тұрады."),
                WH("You need a boat or a plane to reach me.", "Чтобы добраться до меня, нужна лодка или самолёт.", "Маған жету үшін қайық немесе ұшақ керек."),
                WH("Some of me are tiny; others hold entire countries.", "Некоторые из нас крошечные, а другие вмещают целые страны.", "Кейбіреуіміз кішкентай, ал басқалары тұтас елдерді сыйдырады.")),
            WW('peninsula',
                WH("Water wraps around me on three sides, not four.", "Вода окружает меня с трёх сторон, а не с четырёх.", "Су мені төрт емес, үш жағынан қоршайды."),
                WH("I stick out from the mainland like an arm reaching into the sea.", "Я выступаю от материка, как рука, тянущаяся в море.", "Мен теңізге созылған қол сияқты құрлықтан шығып тұрамын."),
                WH("Florida and Korea are both famous examples of me.", "Флорида и Корея — оба известные примеры меня.", "Флорида мен Корея — екеуі де менің белгілі мысалдарым.")),
            WW('harbor',
                WH("Ships come to me to hide from rough seas.", "Корабли приходят ко мне, чтобы укрыться от бурного моря.", "Кемелер қатты толқыннан жасыну үшін маған келеді."),
                WH("I'm calmer water, protected from the open ocean.", "Я — более спокойная вода, защищённая от открытого океана.", "Мен ашық мұхиттан қорғалған тыныш сумын."),
                WH("Fishing boats return to me every evening, loaded with their catch.", "Рыбацкие лодки возвращаются ко мне каждый вечер с уловом.", "Балықшы қайықтары кешкісін аулаған балықпен маған қайтады.")),
            WW('windmill',
                WH("I do nothing at all until the air starts moving.", "Я ничего не делаю, пока воздух не начнёт двигаться.", "Ауа қозғалмайынша мен ештеңе істемеймін."),
                WH("My arms spin round and round, powered by nothing but wind.", "Мои крылья крутятся и крутятся, приводимые в движение только ветром.", "Қанаттарым тек желмен айналады."),
                WH("Old ones like me once ground wheat into flour.", "Старые вроде меня когда-то мололи пшеницу в муку.", "Менің көне түрлерім бидайды ұнға тартатын.")),
            WW('castle',
                WH("Thick stone walls have kept me standing for centuries.", "Толстые каменные стены держат меня стоящим уже века.", "Қалың тас қабырғалар мені ғасырлар бойы тұрғызып келеді."),
                WH("Kings and queens once called me home.", "Короли и королевы когда-то называли меня домом.", "Патшалар мен патшайымдар мені бір кездері үй деген."),
                WH("I often come with a moat and a drawbridge.", "Часто вместе со мной идёт ров и подъёмный мост.", "Менімен көбіне ор мен көтерілмелі көпір бірге жүреді.")),
            WW('maze',
                WH("Enter me, and finding the way out isn't easy.", "Войди в меня, и найти выход будет непросто.", "Менің ішіме кірсең, шығуды табу оңай емес."),
                WH("My paths twist and turn, and many lead nowhere.", "Мои дорожки петляют и поворачивают, и многие ведут в никуда.", "Жолдарым бұрылып, ирелеңдейді, көбі еш жерге апармайды."),
                WH("Gardens sometimes grow me out of tall, trimmed hedges.", "Иногда меня выращивают в садах из высоких подстриженных кустов.", "Кейде мені бақтарда биік қиылған бұталардан өсіреді.")),
            WW('kite',
                WH("Give me a string and a breezy day, and I'm happy.", "Дай мне нитку и ветреный день — и я счастлив.", "Маған жіп пен желді күн берсең, мен қуаныштымын."),
                WH("I dance in the sky, but I'm tied to the ground.", "Я танцую в небе, но привязан к земле.", "Мен аспанда билеймін, бірақ жерге байлаулымын."),
                WH("Children run across parks just to keep me flying.", "Дети бегают по паркам, лишь бы удержать меня в полёте.", "Балалар мені ұшырып тұру үшін саябақта жүгіреді.")),
            WW('sundial',
                WH("I tell time without a single battery or gear.", "Я показываю время без единой батарейки или шестерёнки.", "Мен бір де бір батарея немесе тісті доңғалақсыз уақытты көрсетемін."),
                WH("My shadow moves slowly as the sun crosses the sky.", "Моя тень медленно движется, пока солнце пересекает небо.", "Күн аспанмен жүргенде менің көлеңкем баяу қозғалады."),
                WH("Ancient people read the hour by looking at my shadow.", "Древние люди узнавали час, глядя на мою тень.", "Ежелгі адамдар менің көлеңкеме қарап уақытты білген.")),
            WW('anchor',
                WH("I'm heavy on purpose - that's my entire job.", "Я тяжёлый специально — в этом вся моя работа.", "Мен әдейі ауырмын — бұл менің бүкіл жұмысым."),
                WH("I drop into the water to keep a ship from drifting.", "Я опускаюсь в воду, чтобы корабль не унесло течением.", "Кеменің ағыспен кетпеуі үшін суға түсемін."),
                WH("Sailors trust me to hold their whole ship in place.", "Моряки доверяют мне удерживать весь корабль на месте.", "Теңізшілер бүкіл кемені орнында ұстауды маған сенеді.")),
            WW('globe',
                WH("I'm a whole world, small enough to sit on your desk.", "Я целый мир, но достаточно маленький, чтобы стоять на твоём столе.", "Мен бүкіл әлеммін, бірақ үстеліңе сыятындай кішкентаймын."),
                WH("Spin me, and you can travel every country in seconds.", "Покрути меня, и ты объедешь все страны за секунды.", "Мені айналдырсаң, барлық елді секундтарда аралайсың."),
                WH("I'm shaped exactly like the planet you're standing on.", "Я имею точно такую же форму, как планета, на которой ты стоишь.", "Мен дәл сен тұрған планета сияқты пішіндемін.")),
            WW('atlas',
                WH("I hold every country between just two covers.", "Я вмещаю все страны всего между двумя обложками.", "Мен барлық елді екі мұқабаның арасына сыйдырамын."),
                WH("Before phones, travelers flipped through my pages to find their way.", "До телефонов путешественники листали мои страницы, чтобы найти дорогу.", "Телефонға дейін саяхатшылар жол табу үшін менің беттерімді ақтарған."),
                WH("I'm a whole world of maps, bound together like a book.", "Я целый мир карт, переплетённых вместе, как книга.", "Мен кітап сияқты түптелген карталардың бүкіл әлеміімін.")),
            WW('binoculars',
                WH("I make faraway birds feel close enough to touch.", "Я делаю так, что далёкие птицы кажутся совсем близко.", "Мен алыстағы құстарды қолмен ұстайтындай жақын сезіндіремін."),
                WH("Look through me with both eyes for the best view.", "Смотри через меня обоими глазами для лучшего обзора.", "Ең жақсы көрініс үшін маған екі көзіңмен қара."),
                WH("Hikers and bird-watchers rarely leave home without me.", "Туристы и любители птиц редко выходят из дома без меня.", "Туристер мен құс бақылаушылар үйден мені алмай сирек шығады.")),
        ];
    }
    if ($level === 'pre-intermediate') {
        return [
            WW('stethoscope',
                WH("I let someone listen to a secret sound hidden inside your chest.", "Я позволяю кому-то услышать тайный звук, спрятанный внутри твоей груди.", "Мен біреуге кеудеңнің ішінде жасырылған құпия дыбысты естуге мүмкіндік беремін."),
                WH("A doctor hangs me around their neck between patients.", "Врач вешает меня на шею между приёмами пациентов.", "Дәрігер науқастар арасында мені мойнына іледі."),
                WH("Through me, you can hear a heart beating from the outside.", "Через меня можно услышать, как бьётся сердце, находясь снаружи.", "Мен арқылы сырттан жүректің соғысын естуге болады.")),
            WW('parachute',
                WH("I'm useless until the moment someone jumps out of something very high.", "Я бесполезен, пока кто-то не прыгнет с чего-то очень высокого.", "Біреу өте биіктен секірмейінше, менен пайда жоқ."),
                WH("I stay folded and forgotten until I suddenly open wide above your head.", "Я остаюсь сложенным и забытым, пока вдруг не раскрываюсь широко над твоей головой.", "Мен басыңның үстінде кенеттен кең ашылғанша бүктеулі және ұмытылған күйде жатамын."),
                WH("Without me, a jump from an airplane would end very badly.", "Без меня прыжок из самолёта закончился бы очень плохо.", "Мен болмасам, ұшақтан секіру өте жаман аяқталар еді.")),
            WW('hourglass',
                WH("I have no hands, yet I still tell you something about time.", "У меня нет стрелок, но я всё равно рассказываю тебе о времени.", "Менің тілшелерім жоқ, бірақ мен саған уақыт туралы бәрібір айтамын."),
                WH("Tiny grains fall through my narrow waist, and when they stop, so does my job.", "Крошечные песчинки падают через мою узкую талию, и когда они останавливаются, моя работа тоже заканчивается.", "Кішкентай құм түйіршіктері менің тар белімнен түседі, олар тоқтағанда менің жұмысым да тоқтайды."),
                WH("Turn me upside down, and I start counting all over again.", "Переверни меня, и я снова начинаю отсчёт.", "Мені төңкерсең, мен қайтадан санай бастаймын.")),
            WW('chameleon',
                WH("I can agree with my surroundings without saying a single word.", "Я могу соглашаться с окружением, не сказав ни единого слова.", "Мен бір ауыз сөз айтпай-ақ қоршаған ортаммен келісе аламын."),
                WH("Blend into a leaf, a rock, or a branch - it's all the same to me.", "Слиться с листом, камнем или веткой — для меня без разницы.", "Жапыраққа, тасқа немесе бұтаққа сіңіп кету — мен үшін бәрібір."),
                WH("My skin changes color so well that predators often walk right past me.", "Моя кожа меняет цвет так хорошо, что хищники часто проходят мимо меня.", "Менің терім түсті соншалықты жақсы өзгертеді, жыртқыштар көбіне менің қасымнан өтіп кетеді.")),
            WW('boomerang',
                WH("Throw me away, and I take that personally - I always come back.", "Выбрось меня, и я восприму это лично — я всегда возвращаюсь.", "Мені лақтырып жібер, мен мұны жеке қабылдаймын — мен әрқашан қайтып ораламын."),
                WH("I curve through the air in a way that no straight stick ever could.", "Я изгибаюсь в воздухе так, как никогда не смогла бы прямая палка.", "Мен ауада түзу таяқша ешқашан жасай алмайтындай иіліп ұшамын."),
                WH("Ancient hunters from Australia trusted me to return to their hand.", "Древние охотники из Австралии доверяли, что я вернусь к ним в руку.", "Аустралиялық ежелгі аңшылар менің қолдарына қайта оралатыныма сенген.")),
            WW('tsunami',
                WH("I start as something small and quiet, far out where no one can see me.", "Я начинаюсь как что-то маленькое и тихое, далеко там, где меня никто не видит.", "Мен ешкім көре алмайтын алыс жерде кішкентай және тыныш нәрсе ретінде басталамын."),
                WH("An earthquake under the ocean is often the reason I wake up.", "Землетрясение под океаном часто становится причиной того, что я просыпаюсь.", "Мұхит астындағы жер сілкінісі көбіне менің оянуыма себеп болады."),
                WH("By the time I reach the shore, I've grown into a wall of water.", "К тому времени, как я достигаю берега, я превращаюсь в стену воды.", "Мен жағаға жеткенше, су қабырғасына айналамын.")),
            WW('periscope',
                WH("I let you peek over a wall without ever standing up.", "Я позволяю тебе заглянуть за стену, даже не вставая.", "Мен саған тұрмай-ақ қабырғаның арғы жағын көруге мүмкіндік беремін."),
                WH("Submarine crews use me to see the surface from below.", "Экипажи подводных лодок используют меня, чтобы видеть поверхность снизу.", "Су асты қайығының экипажы мені бетті төменнен көру үшін пайдаланады."),
                WH("Mirrors inside me bend your view around a corner.", "Зеркала внутри меня изгибают твой взгляд за угол.", "Ішімдегі айналар көзқарасыңды бұрышпен бұрады.")),
            WW('kaleidoscope',
                WH("Turn me, and my whole world rearranges into new patterns.", "Поверни меня, и весь мой мир перестроится в новые узоры.", "Мені бұрасаң, бүкіл әлемім жаңа өрнектерге өзгереді."),
                WH("Tiny colored pieces tumble inside me with every twist.", "Крошечные цветные кусочки пересыпаются внутри меня с каждым поворотом.", "Әр бұрылыста ішімде кішкентай түрлі-түсті бөлшектер сырғанайды."),
                WH("Look through me and no two views are ever the same.", "Посмотри через меня — и два вида никогда не будут одинаковыми.", "Маған қарасаң, ешқашан бірдей екі көрініс болмайды.")),
            WW('wheelchair',
                WH("I move on wheels instead of legs.", "Я передвигаюсь на колёсах вместо ног.", "Мен аяқтың орнына дөңгелекпен жүремін."),
                WH("I give someone their independence back.", "Я возвращаю кому-то его независимость.", "Мен біреуге тәуелсіздігін қайтарамын."),
                WH("Push me, or someone can roll themselves using my wheels.", "Толкай меня, или человек сам покатится на моих колёсах.", "Мені итер, немесе адам дөңгелегімді өзі айналдырады.")),
            WW('crutches',
                WH("You'll usually need two of me, one under each arm.", "Обычно нужны две меня, по одной под каждую руку.", "Әдетте екеуім керек, әр қолтығыңның астына біреу."),
                WH("I help take the weight off a hurting leg.", "Я помогаю снять вес с больной ноги.", "Мен ауырған аяқтан салмақты алуға көмектеседі."),
                WH("After a broken bone, I become a temporary best friend.", "После перелома я становлюсь временным лучшим другом.", "Сүйек сынғаннан кейін мен уақытша ең жақын досыңа айналамын.")),
            WW('thermostat',
                WH("I'm the reason your room isn't too hot or too cold.", "Из-за меня в твоей комнате не слишком жарко и не слишком холодно.", "Бөлмеңнің тым ыстық немесе тым суық болмауының себебі — менмін."),
                WH("Set a number on me, and the whole house obeys.", "Установи на мне число, и весь дом подчинится.", "Маған сан қойсаң, бүкіл үй бағынады."),
                WH("I quietly control the heating and cooling without you noticing.", "Я тихо управляю отоплением и охлаждением, а ты этого даже не замечаешь.", "Мен жылыту мен салқындатуды сен байқамай басқарамын.")),
            WW('generator',
                WH("When the lights go out, I'm the backup plan.", "Когда гаснет свет, я — запасной план.", "Жарық өшкенде, мен қосалқы жоспармын."),
                WH("Fuel goes in, and electricity comes out of me.", "Топливо входит, а электричество выходит из меня.", "Отын кіреді, ал электр меннен шығады."),
                WH("Campers and hospitals both keep me close for emergencies.", "И туристы, и больницы держат меня рядом на случай чрезвычайной ситуации.", "Туристер мен ауруханалар мені төтенше жағдай үшін жанында ұстайды.")),
            WW('turbine',
                WH("Wind or water pushes me, and I spin without stopping.", "Ветер или вода толкают меня, и я кручусь без остановки.", "Жел немесе су мені итереді, мен тоқтаусыз айналамын."),
                WH("My spinning is quietly turned into electricity.", "Моё вращение тихо превращается в электричество.", "Менің айналуым тыныш электрге айналады."),
                WH("You'll find me standing tall in wind farms or hidden inside dams.", "Меня можно найти высоко стоящей на ветряных станциях или спрятанной внутри плотин.", "Мені жел станцияларында биік тұрғанда немесе бөгеттің ішінде жасырын табасың.")),
            WW('satellite',
                WH("I circle far above you, and I never come down.", "Я кружу далеко над тобой и никогда не спускаюсь.", "Мен сенің үстіңде алыста айналамын және ешқашан түспеймін."),
                WH("Your GPS and TV signals often pass through me first.", "Твои сигналы GPS и телевидения часто сначала проходят через меня.", "GPS пен теледидар сигналдарың көбіне алдымен мен арқылы өтеді."),
                WH("Humans launched me into space, and I've been orbiting ever since.", "Люди запустили меня в космос, и с тех пор я на орбите.", "Адамдар мені ғарышқа ұшырды, содан бері мен орбитадамын.")),
            WW('spacesuit',
                WH("Step outside without me, and space would be instantly deadly.", "Выйди наружу без меня, и космос мгновенно станет смертельным.", "Мінсіз сыртқа шықсаң, ғарыш бірден өлімге әкеледі."),
                WH("I carry your air supply everywhere you go.", "Я ношу твой запас воздуха, куда бы ты ни пошёл.", "Мен ауа қорыңды қайда барсаң да алып жүремін."),
                WH("Astronauts trust me with their life the moment they leave the ship.", "Космонавты доверяют мне свою жизнь в тот момент, когда покидают корабль.", "Ғарышкерлер кемеден шыққан сәтте өмірін маған сенеді.")),
            WW('submarine',
                WH("I dive deep underwater and disappear from sight.", "Я ныряю глубоко под воду и исчезаю из виду.", "Мен судың астына терең сүңгіп, көзден жоғаламын."),
                WH("I hold my breath for weeks, carrying a whole crew inside.", "Я задерживаю дыхание на недели, неся внутри целый экипаж.", "Ішімде бүкіл экипажды алып жүріп, апталап дем алмаймын."),
                WH("Silent and hidden, I explore the ocean where ships can't follow.", "Тихая и скрытая, я исследую океан там, куда кораблям не добраться.", "Үнсіз және жасырын түрде кемелер бара алмайтын мұхитты зерттеймін.")),
            WW('radar',
                WH("I bounce invisible waves off things I can't even see.", "Я отражаю невидимые волны от вещей, которые даже не вижу.", "Мен өзім көре алмайтын заттардан көрінбейтін толқындарды қайтарамын."),
                WH("Airports trust me to track planes in the darkest night.", "Аэропорты доверяют мне отслеживать самолёты в самую тёмную ночь.", "Әуежайлар маған ең қараңғы түнде ұшақтарды бақылауды сенеді."),
                WH("Police sometimes use me to catch cars driving too fast.", "Полиция иногда использует меня, чтобы ловить машины, едущие слишком быстро.", "Полиция кейде мені тым жылдам жүрген көліктерді ұстау үшін пайдаланады.")),
            WW('sonar',
                WH("I 'see' using sound instead of light.", "Я «вижу» с помощью звука, а не света.", "Мен жарықтың орнына дыбыс арқылы 'көремін'."),
                WH("Ships use me to find out how deep the ocean really is.", "Корабли используют меня, чтобы узнать настоящую глубину океана.", "Кемелер мұхиттың нақты тереңдігін білу үшін мені пайдаланады."),
                WH("Dolphins use a natural version of me to hunt in the dark.", "Дельфины используют свою природную версию меня, чтобы охотиться в темноте.", "Дельфиндер қараңғыда аң аулау үшін менің табиғи нұсқамды қолданады.")),
            WW('microscope',
                WH("I make the invisible world suddenly impossible to ignore.", "Я делаю невидимый мир вдруг невозможным игнорировать.", "Мен көрінбейтін әлемді кенеттен елемеуге болмайтын етемін."),
                WH("A single drop of water becomes a whole universe through me.", "Одна капля воды становится целой вселенной через меня.", "Судың бір тамшысы мен арқылы бүкіл ғаламға айналады."),
                WH("Scientists press their eye to me to study tiny cells.", "Учёные прижимаются глазом ко мне, чтобы изучать крошечные клетки.", "Ғалымдар кішкентай жасушаларды зерттеу үшін көзін маған тақайды.")),
            WW('vaccine',
                WH("I teach your body to fight an enemy it hasn't met yet.", "Я учу твоё тело бороться с врагом, которого оно ещё не встречало.", "Мен денеңді әлі кездеспеген жаумен күресуге үйретемін."),
                WH("A tiny piece of the threat is my secret weapon.", "Крошечная часть угрозы — моё секретное оружие.", "Қауіптің кішкентай бөлігі — менің құпия қаруым."),
                WH("One small injection of me can prevent a serious illness.", "Один маленький укол мной может предотвратить серьёзную болезнь.", "Менің бір кішкентай уколым ауыр ауруды болдырмауы мүмкін.")),
            WW('incubator',
                WH("I keep the tiniest, most fragile lives warm and safe.", "Я сохраняю самые крошечные, самые хрупкие жизни в тепле и безопасности.", "Мен ең кішкентай, ең нәзік өмірлерді жылы және қауіпсіз ұстаймын."),
                WH("Premature babies often spend their first days inside me.", "Недоношенные малыши часто проводят свои первые дни внутри меня.", "Мерзімінен бұрын туған нәрестелер алғашқы күндерін көбіне менің ішімде өткізеді."),
                WH("I copy the warmth of a mother's body when a baby can't feel it yet.", "Я копирую тепло материнского тела, когда малыш ещё не может его почувствовать.", "Нәресте әлі сезбегенде мен ана денесінің жылуын қайталаймын.")),
            WW('pacemaker',
                WH("I live quietly inside someone's chest, keeping time.", "Я тихо живу внутри чьей-то груди, отсчитывая время.", "Мен біреудің кеудесінде тыныш өмір сүріп, уақытты санаймын."),
                WH("When a heart forgets its rhythm, I remind it.", "Когда сердце забывает свой ритм, я ему напоминаю.", "Жүрек ырғағын ұмытқанда, мен оны еске саламын."),
                WH("A tiny battery inside me keeps a heartbeat steady for years.", "Крошечная батарейка внутри меня годами поддерживает ровный пульс.", "Ішімдегі кішкентай батарея жүрек соғысын жылдар бойы тұрақты ұстайды.")),
            WW('escalator',
                WH("I climb for you, so your legs don't have to.", "Я поднимаюсь за тебя, чтобы твоим ногам не пришлось этого делать.", "Аяғың жұмыс істемес үшін мен сен үшін көтеріледі."),
                WH("My steps appear from nowhere and disappear just as fast.", "Мои ступени появляются из ниоткуда и исчезают так же быстро.", "Баспалдақтарым еш жерден пайда болып, дәл солай тез жоғалады."),
                WH("Malls and airports move thousands of tired feet using me.", "Торговые центры и аэропорты перемещают тысячи усталых ног с моей помощью.", "Сауда орталықтары мен әуежайлар мыңдаған шаршаған аяқты мен арқылы жылжытады.")),
            WW('elevator',
                WH("Step inside me, and I'll lift you floors in seconds.", "Зайди в меня, и я подниму тебя на этажи за секунды.", "Менің ішіме кірсең, қабаттарды секундта көтеремін."),
                WH("I travel straight up and down, never sideways.", "Я двигаюсь строго вверх и вниз, никогда в сторону.", "Мен тек тік жоғары-төмен жүремін, бүйірге ешқашан."),
                WH("Skyscrapers would be exhausting to climb without someone like me.", "Небоскрёбы было бы изнурительно подниматься без кого-то вроде меня.", "Мен сияқтысыз аспан асты ғимараттарға шығу титықтатар еді.")),
            WW('greenhouse',
                WH("Inside my glass walls, summer never really ends.", "Внутри моих стеклянных стен лето никогда по-настоящему не заканчивается.", "Менің шыны қабырғамның ішінде жаз ешқашан шынымен бітпейді."),
                WH("I trap the sun's warmth to protect plants from the cold.", "Я улавливаю тепло солнца, чтобы защитить растения от холода.", "Өсімдіктерді суықтан қорғау үшін күн жылуын ұстап қаламын."),
                WH("Tomatoes can grow inside me even in the middle of winter.", "Помидоры могут расти внутри меня даже посреди зимы.", "Ішімде қыстың ортасында да қызанақ өсе алады.")),
            WW('scarecrow',
                WH("I stand in a field all day, and I never move.", "Я стою в поле весь день и никогда не двигаюсь.", "Мен күні бойы даланың ортасында тұрамын және қозғалмаймын."),
                WH("Birds are supposed to be afraid of me, though I have no bones.", "Птицы должны меня бояться, хотя у меня нет костей.", "Сүйегім болмаса да, құстар менен қорқуы керек."),
                WH("Farmers dress me in old clothes and give me a straw heart.", "Фермеры одевают меня в старую одежду и дают мне соломенное сердце.", "Диқандар мені ескі киіммен киіндіріп, сабан жүрек береді.")),
        ];
    }
    if ($level === 'intermediate') {
        return [
            WW('algorithm',
                WH("I live inside computers, but you'll never see my face.", "Я живу внутри компьютеров, но ты никогда не увидишь моё лицо.", "Мен компьютерлердің ішінде өмір сүремін, бірақ сен менің бетімді ешқашан көрмейсің."),
                WH("I'm just a list of steps, followed exactly, in exactly the right order.", "Я всего лишь список шагов, которым следуют точно и в правильном порядке.", "Мен тек дәл және дұрыс ретпен орындалатын қадамдар тізімімін."),
                WH("Without me, your phone wouldn't know how to sort your photos or suggest a video.", "Без меня твой телефон не знал бы, как отсортировать фотографии или предложить видео.", "Мен болмасам, телефоның суреттерді сұрыптауды немесе бейне ұсынуды білмес еді.")),
            WW('ecosystem',
                WH("I'm not one living thing - I'm an entire community that depends on itself.", "Я не одно живое существо — я целое сообщество, которое зависит само от себя.", "Мен бір тірі жәндік емеспін — мен өзіне-өзі тәуелді тұтас қауымдастықпын."),
                WH("Remove one small piece of me, and the rest of me can start to collapse.", "Убери одну маленькую часть меня, и остальное может начать разрушаться.", "Менің бір кішкентай бөлігімді алып тастасаң, қалғаны құлдырай бастауы мүмкін."),
                WH("A forest, a coral reef, and even a puddle can each be one of me.", "Лес, коралловый риф и даже лужа — каждый из них может быть мной.", "Орман, маржан рифі және тіпті шалшық судың әрқайсысы мен бола алады.")),
            WW('hypothesis',
                WH("I'm not a fact yet - I'm just a guess dressed up in scientific clothes.", "Я ещё не факт — я всего лишь догадка, одетая в научную одежду.", "Мен әлі факт емеспін — мен тек ғылыми киім киген болжаммын."),
                WH("Scientists build me before they even run a single experiment.", "Учёные создают меня ещё до того, как проведут хотя бы один эксперимент.", "Ғалымдар бір ғана тәжірибе жасамай тұрып-ақ мені құрастырады."),
                WH("An experiment's whole job is to prove me right or prove me wrong.", "Вся задача эксперимента — доказать, что я права, или доказать, что я неправа.", "Тәжірибенің бүкіл міндеті — менің дұрыс немесе бұрыс екенімді дәлелдеу.")),
            WW('metaphor',
                WH("I compare two things without ever using the word 'like' or 'as'.", "Я сравниваю две вещи, никогда не используя слово «как» или «словно».", "Мен «сияқты» немесе «тәрізді» деген сөзді қолданбай-ақ екі затты салыстырамын."),
                WH("Poets and writers love to hide me inside their most beautiful lines.", "Поэты и писатели любят прятать меня в своих самых красивых строках.", "Ақындар мен жазушылар мені өздерінің ең әдемі жолдарының ішіне жасыруды жақсы көреді."),
                WH("When someone says 'time is money,' they're actually using me.", "Когда кто-то говорит «время — деньги», он на самом деле использует меня.", "Біреу «уақыт — ақша» дегенде, ол шын мәнінде мені қолданып тұр.")),
            WW('adrenaline',
                WH("I rush through you the moment you're scared or excited - you can't call me on purpose.", "Я мчусь по тебе в момент страха или волнения — ты не можешь вызвать меня специально.", "Сен қорыққанда немесе қуанғанда мен арқылы жүгіремін — сен мені әдейі шақыра алмайсың."),
                WH("Skydivers and roller coaster riders chase the feeling I give them.", "Парашютисты и любители американских горок гоняются за чувством, которое я им дарю.", "Парашютшылар мен аттракционда жүретіндер мен беретін сезімнің соңынан қуады."),
                WH("Your body secretly makes me the instant it senses danger.", "Твоё тело тайно вырабатывает меня в тот миг, когда чувствует опасность.", "Денең қауіпті сезген сәтте мені жасырын түрде шығарады.")),
            WW('gravity',
                WH("I've been pulling on you since the moment you were born, and I never let go.", "Я тяну тебя с самого твоего рождения и никогда не отпускаю.", "Мен сені дүниеге келген сәттен бастап тартып келемін және ешқашан жібермеймін."),
                WH("Drop anything, and I'm the invisible reason it falls instead of floating.", "Урони что угодно, и я — невидимая причина того, что оно падает, а не парит.", "Кез келген затты түсір, мен оның қалықтамай құлауының көрінбейтін себебімін."),
                WH("Without me, everything on Earth - including you - would drift off into space.", "Без меня всё на Земле, включая тебя, унеслось бы в космос.", "Мен болмасам, Жердегінің бәрі, соның ішінде сен де, ғарышқа ұшып кетер едің.")),
            WW('inflation',
                WH("Every year, your money quietly buys a little less because of me.", "Каждый год твои деньги из-за меня незаметно покупают чуть меньше.", "Жыл сайын ақшаң менің салдарымнан аздап азырақ сатып алады."),
                WH("Prices creep upward, and I'm usually the reason why.", "Цены медленно ползут вверх, и обычно причина в этом — я.", "Бағалар жоғарылайды, әдетте себебі — менмін."),
                WH("Economists watch me closely - too much of me can hurt everyone.", "Экономисты внимательно следят за мной — слишком много меня может навредить всем.", "Экономистер мені мұқият бақылайды — меннің тым көбі бәріне зиян тигізуі мүмкін.")),
            WW('recession',
                WH("When I arrive, businesses slow down and jobs get harder to find.", "Когда я прихожу, бизнес замедляется, а работу найти становится труднее.", "Мен келгенде бизнес баяулайды, жұмыс табу қиындайды."),
                WH("I follow a period when the economy stops growing and starts shrinking.", "Я наступаю, когда экономика перестаёт расти и начинает сжиматься.", "Экономика өсуді тоқтатып, кішірее бастағанда мен пайда боламын."),
                WH("Governments try everything they can to avoid or shorten me.", "Правительства делают всё возможное, чтобы избежать меня или сократить моё время.", "Үкіметтер меннен аулақ болу немесе қысқарту үшін бар күшін салады.")),
            WW('entrepreneur',
                WH("I turn a risky idea into a real business.", "Я превращаю рискованную идею в настоящий бизнес.", "Мен тәуекел идеяны нақты бизнеске айналдырамын."),
                WH("I'm not afraid to fail before I finally succeed.", "Я не боюсь потерпеть неудачу, прежде чем наконец добьюсь успеха.", "Ақыры сәтке жеткенше сәтсіздіктен қорықпаймын."),
                WH("Every company you know started because someone like me took a chance.", "Каждая компания, которую ты знаешь, началась, потому что кто-то вроде меня рискнул.", "Білетін әрбір компания мен сияқты біреу тәуекел еткендіктен басталды.")),
            WW('momentum',
                WH("The heavier and faster something is, the more of me it carries.", "Чем тяжелее и быстрее что-то, тем больше меня оно несёт.", "Зат неғұрлым ауыр әрі жылдам болса, соғұрлым менен көп алып жүреді."),
                WH("Once something gets me moving, stopping it isn't easy.", "Как только что-то приводит меня в движение, остановить это нелегко.", "Бір нәрсе мені қозғалысқа келтірсе, тоқтату оңай емес."),
                WH("A rolling boulder has plenty of me; a still one has none.", "У катящегося валуна меня много, у неподвижного — совсем нет.", "Домалап жатқан тастың меннен көбі бар, тыныш жатқанда мүлде жоқ.")),
            WW('friction',
                WH("I'm the invisible force that slows things down when they rub together.", "Я невидимая сила, которая замедляет вещи, когда они трутся друг о друга.", "Мен заттар үйкелгенде оларды баяулататын көрінбейтін күшпін."),
                WH("Without me, walking would be nearly impossible - you'd just slide.", "Без меня ходьба была бы почти невозможной — ты бы просто скользил.", "Мен болмасам, жүру мүмкін емес дерлік еді — сен жай сырғанар едің."),
                WH("Rub your hands together fast, and you'll feel me as heat.", "Потри руки друг о друга быстро, и ты почувствуешь меня как тепло.", "Қолыңды тез үйкесең, мені жылу ретінде сезінесің.")),
            WW('velocity',
                WH("I'm not just how fast you go - I care which way, too.", "Я не просто скорость — мне важно ещё и направление.", "Мен жай ғана жылдамдық емеспін — бағыт та маңызды."),
                WH("Speed alone isn't enough to describe me; direction matters just as much.", "Одной скорости недостаточно, чтобы описать меня; направление важно так же.", "Мені сипаттауға жылдамдықтың өзі жеткіліксіз, бағыт та маңызды."),
                WH("A car going 60 mph north has a different me than one going 60 mph south.", "У машины, едущей на север со скоростью 60 миль в час, я не такая, как у едущей на юг.", "Солтүстікке 60 миль/сағ жылдамдықпен бара жатқан көліктің мені оңтүстікке баратыннан өзгеше.")),
            WW('acceleration',
                WH("I'm what you feel when a car suddenly speeds up.", "Я то, что ты чувствуешь, когда машина вдруг набирает скорость.", "Мен көлік кенеттен жылдамдағанда сезінетін нәрсемін."),
                WH("Any change in speed, faster or slower, is really me.", "Любое изменение скорости, быстрее или медленнее, — это на самом деле я.", "Жылдамдықтың кез келген өзгерісі, тез немесе баяу, шын мәнінде менмін."),
                WH("Roller coasters are thrilling because of how much of me they create.", "Американские горки захватывают дух именно из-за того, сколько меня они создают.", "Аттракциондар қызықты, себебі олар меннен көп жасайды.")),
            WW('radiation',
                WH("I can travel invisibly through walls that seem completely solid.", "Я могу невидимо проходить сквозь стены, которые кажутся совершенно твёрдыми.", "Мен мүлде қатты көрінетін қабырғалардан көрінбей өте аламын."),
                WH("Too much of me is dangerous, but doctors also use small amounts to heal.", "Слишком много меня опасно, но врачи также используют небольшое количество меня для лечения.", "Меннің тым көбі қауіпті, бірақ дәрігерлер емдеу үшін аз мөлшерін де қолданады."),
                WH("The sun sends me to Earth every single day as light and warmth.", "Солнце посылает меня на Землю каждый день в виде света и тепла.", "Күн мені жарық пен жылу түрінде әр күні Жерге жібереді.")),
            WW('evolution',
                WH("I work so slowly, no single lifetime is long enough to watch me happen.", "Я работаю так медленно, что ни одной человеческой жизни не хватит, чтобы увидеть меня.", "Мен соншалықты баяу жұмыс істеймін, бір өмір мені көруге жетпейді."),
                WH("Small changes add up across countless generations because of me.", "Маленькие изменения накапливаются через бесчисленные поколения благодаря мне.", "Кішкентай өзгерістер сансыз ұрпақ бойы менің салдарымнан жинақталады."),
                WH("Darwin is the name most people connect with discovering how I work.", "Дарвин — имя, с которым большинство людей связывает открытие того, как я работаю.", "Дарвин деген есім көпшілік үшін меннің қалай жұмыс істейтінін ашумен байланысты.")),
            WW('photosynthesis',
                WH("I happen quietly inside every green leaf you've ever seen.", "Я тихо происходит внутри каждого зелёного листа, который ты когда-либо видел.", "Мен көрген әрбір жасыл жапырақтың ішінде тыныш болып жатамын."),
                WH("Sunlight, water, and air are my only ingredients.", "Солнечный свет, вода и воздух — мои единственные ингредиенты.", "Күн сәулесі, су және ауа — менің жалғыз құрамдастарым."),
                WH("Without me, plants couldn't make their own food - or oxygen for you.", "Без меня растения не смогли бы делать свою еду — или кислород для тебя.", "Мен болмасам, өсімдіктер өз тағамын да, саған оттегі де жасай алмас еді.")),
            WW('osmosis',
                WH("I move water where it's needed, without anyone pushing it.", "Я перемещаю воду туда, где она нужна, без чьего-либо толчка.", "Мен суды ешкім итермей қажет жерге жеткіземін."),
                WH("I always travel from watery to less watery, never the other way.", "Я всегда двигаюсь от более водянистого к менее водянистому, никогда наоборот.", "Мен әрқашан сулырақтан аз сулыға қарай жүремін, керісінше емес."),
                WH("A wilting plant perks back up because of me and a good watering.", "Увядшее растение оживает благодаря мне и хорошему поливу.", "Солған өсімдік мен және жақсы суару арқылы қайта тіріледі.")),
            WW('metabolism',
                WH("I quietly turn your lunch into the energy you're using right now.", "Я тихо превращаю твой обед в энергию, которую ты используешь прямо сейчас.", "Мен түскі асыңды дәл қазір пайдаланып жатқан энергияға тыныш айналдырамын."),
                WH("Some people say mine runs fast; others say mine runs slow.", "Одни говорят, что мой темп быстрый, другие — что медленный.", "Кейбіреулер меннің жылдам дейді, басқалары баяу дейді."),
                WH("Even while you sleep, I never fully stop working.", "Даже пока ты спишь, я никогда полностью не прекращаю работать.", "Сен ұйықтап жатқанда да мен толық тоқтамаймын.")),
            WW('immunity',
                WH("I remember every invader that's ever tried to make you sick.", "Я помню каждого захватчика, который когда-либо пытался тебя заразить.", "Мен сені ауыртуға тырысқан әрбір жауды есте сақтаймын."),
                WH("Once I've fought something off, I often recognize it instantly next time.", "Как только я с чем-то справился, в следующий раз я часто узнаю это мгновенно.", "Бір нәрсемен күресіп жеңгеннен кейін, келесі жолы оны бірден танимын."),
                WH("Vaccines work by giving me a preview of the enemy.", "Вакцины работают, давая мне предварительный просмотр врага.", "Вакциналар маған жаудың алдын ала көрінісін беру арқылы жұмыс істейді.")),
            WW('bacteria',
                WH("I'm so small, a single drop of water can hold millions of me.", "Я такая маленькая, что одна капля воды может вместить миллионы меня.", "Мен соншалықты кішкентаймын, судың бір тамшысында миллиондаған меннен болуы мүмкін."),
                WH("Some of me can make you sick; others quietly help you digest food.", "Некоторые из нас могут заразить тебя, другие тихо помогают переваривать пищу.", "Кейбіреуіміз сені ауыртады, басқалары тамақ қорытуға тыныш көмектеседі."),
                WH("I was here on Earth long before anything you'd call an animal.", "Я была на Земле задолго до всего, что ты назвал бы животным.", "Мен сен жануар дейтін кез келген нәрседен әлдеқайда бұрын Жерде болғанмын.")),
            WW('virus',
                WH("I can't even survive on my own - I need to borrow a living cell.", "Я даже не могу выжить сам по себе — мне нужно позаимствовать живую клетку.", "Мен өз бетімше өмір сүре де алмаймын — маған тірі жасуша керек."),
                WH("I'm smaller than bacteria, and even trickier to fight.", "Я меньше бактерии, и со мной ещё труднее бороться.", "Мен бактериядан кішкентаймын, менімен күресу одан да қиынырақ."),
                WH("A cold, the flu, and chickenpox are all caused by versions of me.", "Простуда, грипп и ветрянка вызваны разновидностями меня.", "Тұмау, грипп және суық тию менің түрлерімнен пайда болады.")),
            WW('antibody',
                WH("I'm shaped perfectly to grab onto one specific invader.", "Я идеально сформирована, чтобы схватить одного конкретного захватчика.", "Мен белгілі бір жауды ұстау үшін дәл пішінделгенмін."),
                WH("Your body builds an army of me after I first meet a threat.", "Твоё тело строит целую армию меня после того, как я впервые встречаю угрозу.", "Денең қаупті алғаш кездестіргеннен кейін меннің әскерін құрады."),
                WH("Blood tests look for me to see what illnesses you've already fought.", "Анализы крови ищут меня, чтобы узнать, с какими болезнями ты уже боролся.", "Қан анализі қандай аурулармен күрескеніңді білу үшін мені іздейді.")),
            WW('enzyme',
                WH("I speed things up without ever getting used up myself.", "Я ускоряю процессы, при этом сама никогда не расходуюсь.", "Мен өзім жұмсалмай-ақ процестерді жылдамдатамын."),
                WH("Without me, digesting your dinner would take far, far longer.", "Без меня переваривание твоего ужина заняло бы гораздо, гораздо дольше.", "Мен болмасам, кешкі асыңды қорыту әлдеқайда ұзаққа созылар еді."),
                WH("Every chemical reaction in your body has one of me helping it along.", "В каждой химической реакции твоего тела мне помогает одна из моих версий.", "Денеңдегі әрбір химиялық реакцияға меннің бір түрі көмектеседі.")),
            WW('chlorophyll',
                WH("I'm the reason leaves are green instead of some other color.", "Из-за меня листья зелёные, а не какого-то другого цвета.", "Жапырақтардың басқа емес, жасыл болуының себебі — менмін."),
                WH("Sunlight and I work together to feed an entire plant.", "Солнечный свет и я вместе работаем, чтобы накормить целое растение.", "Күн сәулесі мен мен бірге бүкіл өсімдікті қоректендіреміз."),
                WH("In autumn, when I start to fade, other colors in the leaf show through.", "Осенью, когда я начинаю исчезать, проступают другие цвета листа.", "Күзде мен азая бастағанда, жапырақтың басқа түстері көрінеді.")),
            WW('magnet',
                WH("I have an invisible pull that reaches things without ever touching them.", "У меня есть невидимая тяга, которая достаёт до вещей, даже не касаясь их.", "Менде затқа тимей-ақ жететін көрінбейтін тартылысым бар."),
                WH("Bring two of me close, and we'll either snap together or push apart.", "Сблизь двух меня, и мы либо притянемся, либо оттолкнёмся.", "Екеуімізді жақындатсаң, немесе бір-бірімізге жабысамыз, немесе итерілеміз."),
                WH("I'm the reason a compass needle always knows which way is north.", "Из-за меня стрелка компаса всегда знает, где север.", "Компас көрсеткішінің әрқашан солтүстікті білуінің себебі — менмін.")),
            WW('pendulum',
                WH("Push me once, and I'll swing back and forth long after you let go.", "Толкни меня один раз, и я буду качаться туда-сюда ещё долго после того, как ты отпустишь.", "Мені бір рет итерсең, жібергеннен кейін де ұзақ уақыт тербеле беремін."),
                WH("Old clocks trusted my steady rhythm to count every second.", "Старые часы доверяли моему устойчивому ритму отсчитывать каждую секунду.", "Ескі сағаттар әр секундты санау үшін менің тұрақты ырғағыма сенген."),
                WH("I always swing in a perfect arc, returning to where I started.", "Я всегда качаюсь по идеальной дуге, возвращаясь туда, откуда начал.", "Мен әрқашан мінсіз доғамен тербеліп, бастаған жеріме қайта ораламын.")),
        ];
    }
    // beginner (and fallback)
    return [
        WW('moon',
            WH("At night, I often watch over the world while everyone sleeps.", "Ночью я часто наблюдаю за миром, пока все спят.", "Түнде барлығы ұйықтап жатқанда мен әлемді жиі бақылаймын."),
            WH("I don't make my own light - I only borrow it from a brighter friend.", "Я не создаю свой собственный свет — я лишь одалживаю его у более яркого друга.", "Мен өз жарығымды жасамаймын — оны жарқын досымнан ғана қарызға аламын."),
            WH("Humans have walked on my surface and left footprints that will never blow away.", "Люди ходили по моей поверхности и оставили следы, которые никогда не сдует ветром.", "Адамдар менің бетімде жүріп, желмен ешқашан ұшпайтын іздер қалдырды.")),
        WW('umbrella',
            WH("People forget about me until the sky starts to cry.", "Люди забывают обо мне, пока небо не начинает плакать.", "Аспан жылай бастағанша адамдар мені ұмытып кетеді."),
            WH("I open my wings above your head, but I never fly.", "Я раскрываю крылья над твоей головой, но никогда не летаю.", "Мен басыңның үстінде қанатымды жаямын, бірақ ешқашан ұшпаймын."),
            WH("Rain slides right off my back while you stay dry underneath.", "Дождь стекает прямо с моей спины, пока ты остаёшься сухим под ней.", "Сен астымда құрғақ қалғанда, жаңбыр менің арқамнан сырғып түседі.")),
        WW('volcano',
            WH("I look calm for years, but deep inside I'm always a little angry.", "Я выгляжу спокойным годами, но внутри всегда немного зол.", "Мен жылдар бойы тыныш көрінемін, бірақ ішімде әрқашан аздап ашулымын."),
            WH("When I lose my temper, I spit fire and turn the sky grey.", "Когда я теряю терпение, я извергаю огонь и делаю небо серым.", "Мен ашуланғанда, от шашырата бастаймын және аспанды сұр етемін."),
            WH("Ancient cities have been buried under what I breathe out.", "Древние города были погребены под тем, что я выдыхаю.", "Ежелгі қалалар мен тыныстап шығарған заттың астында қалды.")),
        WW('kangaroo',
            WH("I carry my baby everywhere, but never in my arms.", "Я ношу своего малыша везде, но никогда на руках.", "Мен баламды қайда барса да алып жүремін, бірақ ешқашан қолымда емес."),
            WH("My legs are so strong I never need to walk - I just bounce.", "Мои ноги настолько сильные, что мне никогда не нужно ходить — я просто прыгаю.", "Аяқтарым сонша мықты, маған жүрудің қажеті жоқ — мен жай ғана секіремін."),
            WH("I come from a faraway land full of red desert and strange animals.", "Я родом из далёкой земли, полной красной пустыни и странных животных.", "Мен қызыл шөл мен ғажайып жануарларға толы алыс жерден келемін.")),
        WW('rainbow',
            WH("You can never touch me, no matter how close I look.", "Ты никогда не сможешь меня коснуться, каким бы близким я ни казался.", "Мен қаншалықты жақын көрінсем де, сен маған ешқашан қол тигізе алмайсың."),
            WH("I only show my face after the rain and the sun make peace.", "Я показываю своё лицо только после того, как дождь и солнце помирятся.", "Мен жаңбыр мен күн татуласқаннан кейін ғана бетімді көрсетемін."),
            WH("I wear every color at once, arched like a bridge in the sky.", "Я ношу все цвета сразу, изгибаясь, как мост в небе.", "Мен барлық түстерді бірден киемін, аспандағы көпір сияқты иіліп тұрамын.")),
        WW('spider',
            WH("I have more legs than you, and I'm not shy about showing them.", "У меня больше ног, чем у тебя, и я не стесняюсь их показывать.", "Менің аяғым сенікінен көп, және мен оларды көрсетуден тартынбаймын."),
            WH("I build a beautiful trap, but I never mean to scare you.", "Я строю красивую ловушку, но никогда не хочу тебя напугать.", "Мен әдемі тор құрамын, бірақ сені қорқытуды ешқашан ойламаймын."),
            WH("Many people jump on a chair the moment they spot me.", "Многие люди запрыгивают на стул, как только замечают меня.", "Көптеген адамдар мені байқаған сәтте орындыққа секіріп шығады.")),
        WW('elephant',
            WH("I never forget a face, they say.", "Говорят, я никогда не забываю лица.", "Мен ешқашан бетті ұмытпаймын дейді."),
            WH("My nose is long enough to lift a log.", "Мой нос достаточно длинный, чтобы поднять бревно.", "Менің мұрным бөренені көтеретіндей ұзын."),
            WH("I'm the biggest animal that still walks on land.", "Я самое большое животное, которое до сих пор ходит по земле.", "Мен құрлықта жүретін ең үлкен жануармын.")),
        WW('giraffe',
            WH("Clouds feel closer to me than to you.", "Облака кажутся мне ближе, чем тебе.", "Бұлттар маған сенен гөрі жақынырақ сияқты."),
            WH("My neck alone is taller than most doors.", "Одна только моя шея выше большинства дверей.", "Тек мойным ғана көптеген есіктен биік."),
            WH("I nibble leaves that no other animal can reach.", "Я щиплю листья, до которых не дотянется ни одно другое животное.", "Мен басқа ешбір жануар жете алмайтын жапырақтарды жеймін.")),
        WW('zebra',
            WH("I wear the same two colors, forever.", "Я ношу одни и те же два цвета навсегда.", "Мен әрқашан сол екі түсті киемін."),
            WH("No two of my patterns are exactly alike.", "Ни один из моих узоров не похож на другой.", "Менің ешбір өрнегім бір-біріне ұқсамайды."),
            WH("From far away, I look like a horse in pajamas.", "Издалека я похожа на лошадь в пижаме.", "Алыстан мен пижама киген атқа ұқсаймын.")),
        WW('octopus',
            WH("I have three hearts, and I never share them.", "У меня три сердца, и я ими ни с кем не делюсь.", "Менің үш жүрегім бар, оларды ешкіммен бөліспеймін."),
            WH("I can squeeze through a hole the size of a coin.", "Я могу протиснуться в дыру размером с монету.", "Мен тиынның мөлшеріндей тесіктен өте аламын."),
            WH("Count my arms - you'll need all eight fingers and more.", "Посчитай мои руки — понадобятся все восемь пальцев и даже больше.", "Қолдарымды санашы — сегіз саусағыңның бәрі керек болады.")),
        WW('dolphin',
            WH("I talk in clicks that humans can't understand.", "Я разговариваю щелчками, которые люди не понимают.", "Мен адамдар түсінбейтін сырт еткен дыбыстармен сөйлесемін."),
            WH("I leap out of the water just for the joy of it.", "Я выпрыгиваю из воды просто ради удовольствия.", "Мен судан жай ғана қуаныштан секіріп шығамын."),
            WH("Sailors call me one of the smartest swimmers in the sea.", "Моряки называют меня одним из самых умных пловцов в море.", "Теңізшілер мені теңіздегі ең ақылды жүзушілердің бірі дейді.")),
        WW('shark',
            WH("I lose teeth all the time, and I never mind.", "Я постоянно теряю зубы, и меня это совсем не беспокоит.", "Мен тісімді үнемі жоғалтамын, бірақ бұған мән бермеймін."),
            WH("I've been swimming these waters since before the dinosaurs.", "Я плаваю в этих водах ещё с времён до динозавров.", "Мен бұл суларда динозаврларға дейін жүзіп келемін."),
            WH("One fin above the water is enough to clear a beach.", "Одного моего плавника над водой достаточно, чтобы опустел весь пляж.", "Судың бетіндегі бір қанатым жағажайды босатуға жеткілікті.")),
        WW('eagle',
            WH("I can spot my dinner from impossibly far away.", "Я замечаю свой обед с невероятно большого расстояния.", "Мен түскі асымды таңғаларлық алыстан байқаймын."),
            WH("I build my home at the very top of the world.", "Я строю свой дом на самой вершине мира.", "Мен үйімді әлемнің ең биік жерінде саламын."),
            WH("Some countries put my picture on their flag and money.", "Некоторые страны помещают моё изображение на флаг и деньги.", "Кейбір елдер менің суретімді туы мен ақшасына салады.")),
        WW('owl',
            WH("I'm wide awake while you're fast asleep.", "Я совсем не сплю, пока ты крепко спишь.", "Сен қатты ұйықтап жатқанда мен сергек жүремін."),
            WH("My head can turn further around than yours ever could.", "Моя голова поворачивается дальше, чем когда-либо сможет твоя.", "Менің басым сенікінен әлдеқайда алысқа бұрылады."),
            WH("People call me wise, though I've never taken a test.", "Люди называют меня мудрой, хотя я никогда не сдавала экзамен.", "Адамдар мені дана дейді, бірақ мен ешқашан емтихан тапсырған емеспін.")),
        WW('bat',
            WH("I sleep upside down and I'm proud of it.", "Я сплю вверх ногами, и я этим горжусь.", "Мен теріс бас болып ұйықтаймын және мұны мақтан тұтамын."),
            WH("I see the world through sound, not light.", "Я вижу мир с помощью звука, а не света.", "Мен әлемді жарық арқылы емес, дыбыс арқылы көремін."),
            WH("I'm the only mammal that can truly fly.", "Я единственное млекопитающее, которое действительно умеет летать.", "Мен шынымен ұша алатын жалғыз сүтқоректімін.")),
        WW('snail',
            WH("I carry my house wherever I go.", "Я ношу свой дом с собой повсюду.", "Мен қайда барсам да үйімді өзіммен алып жүремін."),
            WH("I leave a shiny trail behind me everywhere.", "Я оставляю за собой блестящий след везде.", "Мен қайда барсам да жылтыр із қалдырамын."),
            WH("Nobody has ever accused me of being fast.", "Никто никогда не обвинял меня в быстроте.", "Мені ешкім жылдам деп айыптаған емес.")),
        WW('ant',
            WH("Alone I'm tiny, but together we build kingdoms.", "В одиночку я крошечный, но вместе мы строим целые царства.", "Жалғыз болсам кішкентаймын, бірақ бірге патшалық құрамыз."),
            WH("I can lift many times my own weight.", "Я могу поднять вес, во много раз больше своего собственного.", "Мен өз салмағымнан бірнеше есе ауыр затты көтере аламын."),
            WH("You'll rarely find just one of me at a picnic.", "На пикнике ты редко найдёшь только одну меня.", "Демалыста мені жалғыз кездестіру екіталай.")),
        WW('bee',
            WH("I wear yellow and black like a tiny uniform.", "Я ношу жёлтый и чёрный, как маленькую форму.", "Мен сары мен қараны кішкентай форма сияқты киемін."),
            WH("I dance to tell my friends where the flowers are.", "Я танцую, чтобы рассказать друзьям, где растут цветы.", "Мен достарыма гүлдердің қайда екенін билеп көрсетемін."),
            WH("Without me, most fruits would never grow at all.", "Без меня большинство фруктов никогда бы не выросли.", "Мен болмасам, көптеген жемістер мүлде өспес еді.")),
        WW('camel',
            WH("I can go without a drink for shockingly long.", "Я могу обходиться без питья невероятно долго.", "Мен таңғаларлықтай ұзақ уақыт сусыз жүре аламын."),
            WH("I carry my food supply right on my back.", "Я ношу запас еды прямо у себя на спине.", "Тамақ қорымды тікелей арқамда алып жүремін."),
            WH("The desert is my home, and sand doesn't bother me.", "Пустыня — мой дом, и песок меня совсем не беспокоит.", "Шөл — менің үйім, құм мені мазаламайды.")),
        WW('hedgehog',
            WH("Touch me wrong and you'll regret it instantly.", "Тронь меня не так, и сразу пожалеешь.", "Маған дұрыс тимесең, бірден өкінесің."),
            WH("I curl into a spiky little ball when scared.", "Когда я напугана, я сворачиваюсь в маленький колючий шарик.", "Қорыққанда мен кішкентай тікенекті шарға айналамын."),
            WH("I look soft until you get a little too close.", "Я кажусь мягким, пока ты не подойдёшь слишком близко.", "Тым жақындамайынша мен жұмсақ болып көрінемін.")),
        WW('koala',
            WH("I sleep for most of the day, and I'm not sorry.", "Я сплю большую часть дня, и ничуть об этом не жалею.", "Мен күннің көп бөлігін ұйықтаймын және өкінбеймін."),
            WH("One kind of leaf is basically my entire diet.", "Один вид листьев — это практически весь мой рацион.", "Бір түрлі жапырақ менің тамағымның негізгісі."),
            WH("I hug trees in Australia for a living.", "Я зарабатываю на жизнь, обнимая деревья в Австралии.", "Мен Аустралияда ағаштарды құшақтап күн көремін.")),
        WW('peacock',
            WH("I open my tail like a fan of a hundred eyes.", "Я раскрываю хвост, как веер из сотни глаз.", "Мен құйрығымды жүздеген көзі бар желпуіш сияқты жаямын."),
            WH("The males of my kind are the show-offs.", "Самцы моего вида — настоящие хвастуны.", "Менің тегімнің еркектері мақтаншақ келеді."),
            WH("My feathers shimmer with colors most birds can't match.", "Мои перья переливаются цветами, с которыми не сравнится большинство птиц.", "Қауырсындарым көптеген құс жете алмайтын түстермен жарқырайды.")),
        WW('flamingo',
            WH("I stand on one leg like it's no effort at all.", "Я стою на одной ноге, будто это совсем не трудно.", "Мен бір аяғымда еш қиындықсыз тұрамын."),
            WH("My pink color comes from the food I eat.", "Мой розовый цвет — от еды, которую я ем.", "Қызғылт түсім жейтін тағамымнан пайда болады."),
            WH("You'll usually find me standing in shallow water.", "Обычно меня можно найти стоящей на мелководье.", "Мені әдетте таяз суда тұрғанда табасың.")),
        WW('crocodile',
            WH("I can wait so still, you'd think I was a log.", "Я могу лежать так неподвижно, что меня примут за бревно.", "Мен соншалықты қозғалмай жата аламын, мені бөрене деп ойлайсың."),
            WH("My smile has more teeth than you'd want to count.", "В моей улыбке зубов больше, чем захочется считать.", "Менің тісім санағың келмейтіндей көп."),
            WH("I've barely changed since the age of the dinosaurs.", "Я почти не изменился со времён динозавров.", "Мен динозаврлар заманынан бері әрең өзгердім.")),
        WW('jellyfish',
            WH("I have no brain, and I still get by fine.", "У меня нет мозга, и всё равно я прекрасно справляюсь.", "Менің миым жоқ, бірақ бәрібір жақсы өмір сүремін."),
            WH("I'm mostly made of water, drifting wherever the current takes me.", "Я почти полностью состою из воды, дрейфуя туда, куда несёт течение.", "Мен негізінен судан тұрамын, ағыс апарған жаққа жүземін."),
            WH("Touch me and you might regret it - I can sting.", "Тронь меня — и можешь пожалеть, я умею жалить.", "Маған тисең өкінуің мүмкін — мен шағамын.")),
        WW('scorpion',
            WH("I carry my weapon curled up over my own back.", "Я ношу своё оружие, свёрнутое над собственной спиной.", "Қаруымды өз арқамның үстінде бүктеп алып жүремін."),
            WH("I glow under a special kind of light at night.", "Ночью я свечусь под особым видом света.", "Түнде арнайы жарықтың астында жарқыраймын."),
            WH("My sting is the last thing you want to feel.", "Мой укус — последнее, что тебе захочется почувствовать.", "Менің шағуым сенің сезінгің келмейтін нәрсе.")),
    ];
}

// Not level-partitioned for uniqueness like Hangman - riddles are meant to
// feel fresh/random each playthrough rather than guaranteed non-repeating
// across every lesson at a level.
function extract_whoami_words(int $lessonId, string $level, int $count = 4): array {
    $bank = build_whoami_bank($level);
    mt_srand($lessonId + 9973);
    shuffle($bank);
    return array_slice($bank, 0, min($count, count($bank)));
}
