CREATE TABLE IF NOT EXISTS vocab_images (
    word VARCHAR(190) NOT NULL PRIMARY KEY,
    image_path VARCHAR(255) NOT NULL,
    credit_name VARCHAR(150) NULL,
    credit_url VARCHAR(255) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
